# Generates nvidia/tests/e2e/mma_forms.cu: one kernel per mma.sync /
# mma.sp form the RTX 3060 (sm_86) can run, each fed deterministic per-lane
# fragments and its D hashed over three seeds. Floating-point inputs are small
# multiples of 1/4, exact in every format, so a hash pins where each element
# goes rather than how the hardware orders a sum; f64, the integers and .b1 are
# random bits. To record, on a machine with the GPU:
#
#   python3 gen_mma_forms.py mma_forms.cu
#   nvcc -std=c++17 -O1 -arch=sm_86 mma_forms.cu -o mma_hw
#   MMA_FORMS_RECORD=1 ./mma_hw > hw.txt
#   python3 gen_mma_forms.py mma_forms.cu hw.txt     # embeds the hashes
#
# The test then runs the same program on the simulator and compares.
import sys
forms = []  # (name, ptx_opcode, M, K, atype, btype, ctype, dtype, extra)
def F(name, op, M, K, at, bt, ct, dt, cvar="small"):
    forms.append(dict(name=name, op=op, M=M, K=K, at=at, bt=bt, ct=ct, dt=dt, cvar=cvar))
bits = dict(f16=16, bf16=16, tf32=32, s8=8, u8=8, s4=4, u4=4, b1=1, f64=64, e4m3=8, e5m2=8)
def shape(M, K): return f"m{M}n8k{K}"
# float
for K in (8, 16):
    for ct in ("f32", "f16"):
        F(f"f16_m16n8k{K}_{ct}", f"mma.sync.aligned.m16n8k{K}.row.col.{ct}.f16.f16.{ct}", 16, K, "f16", "f16", ct, ct)
for K in (8, 16):
    F(f"bf16_m16n8k{K}", f"mma.sync.aligned.m16n8k{K}.row.col.f32.bf16.bf16.f32", 16, K, "bf16", "bf16", "f32", "f32")
for K in (4, 8):
    F(f"tf32_m16n8k{K}", f"mma.sync.aligned.m16n8k{K}.row.col.f32.tf32.tf32.f32", 16, K, "tf32", "tf32", "f32", "f32")
# All 23 mantissa bits random: the tensor core drops the low 13. Only k4,
# where four products and C add up the same in any order; how the hardware
# orders or widens a longer sum is unspecified, and at k8 it differs.
F("tf32_m16n8k4_fullbits", "mma.sync.aligned.m16n8k4.row.col.f32.tf32.tf32.f32", 16, 4, "tf32full", "tf32full", "f32", "f32")
for al in ("row", "col"):
    for bl in ("row", "col"):
        for (dt, ct) in (("f32", "f32"), ("f16", "f16"), ("f32", "f16")):
            F(f"f16_m8n8k4_{al}_{bl}_{dt}_{ct}", f"mma.sync.aligned.m8n8k4.{al}.{bl}.{dt}.f16.f16.{ct}", 8, 4, "f16", "f16", ct, dt)
for rnd in ("", ".rz", ".rm", ".rp"):
    F(f"f64_m8n8k4{rnd.replace('.', '_')}", f"mma.sync.aligned.m8n8k4.row.col{rnd}.f64.f64.f64.f64", 8, 4, "f64", "f64", "f64", "f64")
for (M, K) in ((8, 16), (16, 16), (16, 32)):
    for at in ("s8", "u8"):
        for bt in ("s8", "u8"):
            F(f"{at}{bt}_{shape(M,K)}", f"mma.sync.aligned.{shape(M,K)}.row.col.s32.{at}.{bt}.s32", M, K, at, bt, "s32", "s32")
    F(f"s8_{shape(M,K)}_satfinite", f"mma.sync.aligned.{shape(M,K)}.row.col.satfinite.s32.s8.s8.s32", M, K, "s8", "s8", "s32", "s32", "big")
for (M, K) in ((8, 32), (16, 32), (16, 64)):
    for at in ("s4", "u4"):
        for bt in ("s4", "u4"):
            F(f"{at}{bt}_{shape(M,K)}", f"mma.sync.aligned.{shape(M,K)}.row.col.s32.{at}.{bt}.s32", M, K, at, bt, "s32", "s32")
    F(f"s4_{shape(M,K)}_satfinite", f"mma.sync.aligned.{shape(M,K)}.row.col.satfinite.s32.s4.s4.s32", M, K, "s4", "s4", "s32", "s32", "big")
for (M, K) in ((8, 128), (16, 128), (16, 256)):
    for bop in ("xor", "and"):
        F(f"b1_{shape(M,K)}_{bop}", f"mma.sync.aligned.{shape(M,K)}.row.col.s32.b1.b1.s32.{bop}.popc", M, K, "b1", "b1", "s32", "s32")

for (at, shapes, dt) in (("f16", ((16, 4), (32, 2)), "f32"), ("bf16", ((16, 4), (32, 2)), "f32"),
                         ("tf32", ((8, 4), (16, 2)), "f32"), ("s8", ((32, 2), (64, 1)), "s32"),
                         ("u8", ((32, 2), (64, 1)), "s32"), ("s4", ((64, 2), (128, 1)), "s32"),
                         ("u4", ((64, 2), (128, 1)), "s32")):
    for (K, nsel) in shapes:
        for sel in range(nsel):
            for variant in ("sp", "sp::ordered_metadata"):
                v = "sp" if variant == "sp" else "spo"
                F(f"{v}_{at}_m16n8k{K}_sel{sel}", f"mma.{variant}.sync.aligned.m16n8k{K}.row.col.{dt}.{at}.{at}.{dt}",
                  16, K, at, at, dt, dt, cvar="sparse:%d" % sel)
    if at == "f16":
        for K in (16, 32):
            F(f"sp_f16_m16n8k{K}_f16acc", f"mma.sp.sync.aligned.m16n8k{K}.row.col.f16.f16.f16.f16", 16, K, "f16", "f16", "f16", "f16", cvar="sparse:0")

def regs(f, which):
    M, K = f["M"], f["K"]
    if f["name"].startswith("f16_m8n8k4"):
        return {"a": 2, "b": 2, "c": 4 if f["ct"] == "f16" else 8, "d": 4 if f["dt"] == "f16" else 8}[which]
    t = f["at"].replace("full", "")
    b = bits[t]
    if which in "ab":
        n = (M * K if which == "a" else K * 8)
        if which == "a" and f["cvar"].startswith("sparse"): n //= 2
        return n // 32 if t == "f64" else n * b // (32 * 32)
    ty = f["ct"] if which == "c" else f["dt"]
    elems = M * 8 // 32
    return elems // 2 if ty == "f16" else elems

out = []
out.append('''// Generated by nvidia/tools/gen_mma_forms.py; the hashes are an RTX 3060's.
#include <cstdio>
#include <cstdint>
#include <cstring>
#include <cstdlib>
#include <cuda_fp16.h>
#include <cuda_bf16.h>
#include <cuda_runtime.h>
__device__ __forceinline__ uint32_t mix(uint32_t x) {
  x ^= x >> 16; x *= 0x7feb352dU; x ^= x >> 15; x *= 0x846ca68bU; x ^= x >> 16; return x;
}
__device__ __forceinline__ uint32_t H(uint32_t seed, uint32_t lane, uint32_t idx) {
  return mix(seed * 0x9E3779B9U ^ mix(lane * 131 + idx * 7919 + 17));
}
// A small multiple of 1/4 in [-2, 2]: exact in every float format here.
__device__ __forceinline__ float small(uint32_t h) { return (float)((int)(h % 17) - 8) * 0.25f; }
__device__ uint32_t elem_word(const char t, uint32_t seed, uint32_t lane, uint32_t reg) {
  // t: 'h' f16, 'b' bf16, 't' tf32 exact, 'T' tf32 full bits, 'i' raw bits
  uint32_t w = 0;
  if (t == 'h' || t == 'b') {
    for (int e = 0; e < 2; ++e) {
      float v = small(H(seed, lane, reg * 2 + e));
      uint16_t u = t == 'h' ? __half_as_ushort(__float2half(v)) : __bfloat16_as_ushort(__float2bfloat16(v));
      w |= (uint32_t)u << (16 * e);
    }
  } else if (t == 't') {
    float v = small(H(seed, lane, reg));
    w = __float_as_uint(v);
  } else if (t == 'T') {
    // a normal float in [-2, 2) with all 23 mantissa bits random
    uint32_t h = H(seed, lane, reg);
    w = (h & 0x807FFFFFu) | 0x3F800000u;
  } else {
    w = H(seed, lane, reg);
  }
  return w;
}
__device__ double f64val(uint32_t seed, uint32_t lane, uint32_t reg) {
  uint64_t h = ((uint64_t)H(seed, lane, reg) << 32) | H(seed + 1, lane, reg);
  return ((double)(h >> 11) / 9007199254740992.0) * 2.0 - 1.0;
}
''')
tchar = dict(f16='h', bf16='b', tf32='t', tf32full='T', s8='i', u8='i', s4='i', u4='i', b1='i')
for f in forms:
    na, nb, nc, nd = (regs(f, x) for x in "abcd")
    f.update(na=na, nb=nb, nc=nc, nd=nd)
    is64 = f["at"] == "f64"
    L = []
    L.append(f'__global__ void k_{f["name"]}(uint32_t seed, unsigned long long* out) {{')
    L.append('  const uint32_t lane = threadIdx.x;')
    if is64:
        L.append(f'  double a[{na}], b[{nb}], c[{nc}], d[{nd}];')
        L.append(f'  for (int i = 0; i < {na}; ++i) a[i] = f64val(seed, lane, i);')
        L.append(f'  for (int i = 0; i < {nb}; ++i) b[i] = f64val(seed + 7, lane, i);')
        L.append(f'  for (int i = 0; i < {nc}; ++i) c[i] = f64val(seed + 13, lane, i);')
    else:
        L.append(f'  uint32_t a[{na}], b[{nb}], c[{nc}], d[{nd}];')
        L.append(f'  for (int i = 0; i < {na}; ++i) a[i] = elem_word(\'{tchar[f["at"]]}\', seed, lane, i);')
        L.append(f'  for (int i = 0; i < {nb}; ++i) b[i] = elem_word(\'{tchar[f["bt"]]}\', seed + 7, lane, i);')
        if f["ct"] == "f16":
            L.append(f'  for (int i = 0; i < {nc}; ++i) c[i] = elem_word(\'h\', seed + 13, lane, i);')
        elif f["ct"] == "f32":
            L.append(f'  for (int i = 0; i < {nc}; ++i) c[i] = __float_as_uint(small(H(seed + 13, lane, i)) * 2.0f);')
        elif f["cvar"] == "big":
            L.append(f'  for (int i = 0; i < {nc}; ++i) {{ uint32_t h = H(seed + 13, lane, i); c[i] = (h & 1) ? 0x7FFFF000u + (h >> 20) : 0x80000FFFu - (h >> 20); }}')
        else:
            L.append(f'  for (int i = 0; i < {nc}; ++i) c[i] = (int32_t)(H(seed + 13, lane, i) % 2001) - 1000;')
    sparse = f["cvar"].startswith("sparse")
    if sparse:
        nib = "0x4u, 0xEu" if f["at"] == "tf32" else "0x4u, 0x8u, 0x9u, 0xCu, 0xDu, 0xEu"
        L.append(f'  const uint32_t nibs[] = {{{nib}}}; uint32_t meta = 0;')
        L.append(f'  for (int i = 0; i < 8; ++i) meta |= nibs[H(seed + 29, lane, i) % (sizeof nibs / 4)] << (4 * i);')
    rc = "d" if is64 else "r"
    dl = ", ".join(f"%{i}" for i in range(nd))
    n = nd
    al = ", ".join(f"%{n + i}" for i in range(na)); n += na
    bl = ", ".join(f"%{n + i}" for i in range(nb)); n += nb
    cl = ", ".join(f"%{n + i}" for i in range(nc)); n += nc
    outs = ", ".join(f'"={rc}"(d[{i}])' for i in range(nd))
    ins = ", ".join([f'"{rc}"(a[{i}])' for i in range(na)] + [f'"{rc}"(b[{i}])' for i in range(nb)] + [f'"{rc}"(c[{i}])' for i in range(nc)])
    if sparse:
        sel = int(f["cvar"].split(":")[1])
        L.append(f'  asm volatile("{f["op"]} {{{dl}}}, {{{al}}}, {{{bl}}}, {{{cl}}}, %{n}, {sel};" : {outs} : {ins}, "r"(meta));')
    else:
        L.append(f'  asm volatile("{f["op"]} {{{dl}}}, {{{al}}}, {{{bl}}}, {{{cl}}};" : {outs} : {ins});')
    if is64:
        L.append(f'  for (int i = 0; i < {nd}; ++i) {{ unsigned long long u; memcpy(&u, &d[i], 8); out[lane * {nd} + i] = u; }}')
    else:
        L.append(f'  for (int i = 0; i < {nd}; ++i) out[lane * {nd} + i] = d[i];')
    L.append('}')
    out.append("\n".join(L))
out.append('''
static uint64_t fnv(const unsigned long long* p, size_t n) {
  uint64_t h = 1469598103934665603ull;
  for (size_t i = 0; i < n; ++i)
    for (int b = 0; b < 8; ++b) { h ^= (p[i] >> (8 * b)) & 0xFF; h *= 1099511628211ull; }
  return h;
}
struct Form { const char* name; void (*k)(uint32_t, unsigned long long*); int nd; unsigned long long want; };
static const Form kForms[] = {''')
for f in forms:
    out.append(f'  {{"{f["name"]}", k_{f["name"]}, {f["nd"]}, 0x@@{f["name"]}@@ull}},')
out.append('''};
int main(int argc, char** argv) {
  unsigned long long* dout;
  cudaMalloc(&dout, 32 * 8 * sizeof(unsigned long long));
  const char* only = argc > 1 ? argv[1] : nullptr;
  const bool record = getenv("MMA_FORMS_RECORD") != nullptr;
  int fails = 0, ran = 0;
  for (const Form& f : kForms) {
    if (only && !strstr(f.name, only)) continue;
    ++ran;
    uint64_t h = 1469598103934665603ull;
    for (uint32_t seed = 1; seed <= 3; ++seed) {
      cudaMemset(dout, 0, 32 * 8 * sizeof(unsigned long long));
      f.k<<<1, 32>>>(seed, dout);
      cudaError_t e = cudaDeviceSynchronize();
      if (e != cudaSuccess) { printf("FAIL %s: %s\\n", f.name, cudaGetErrorString(e)); return 1; }
      unsigned long long host[32 * 8];
      cudaMemcpy(host, dout, 32 * f.nd * sizeof(unsigned long long), cudaMemcpyDeviceToHost);
      h ^= fnv(host, 32 * f.nd) + seed;
      h *= 1099511628211ull;
    }
    if (record) { printf("%s %016llx\\n", f.name, (unsigned long long)h); continue; }
    if (h != f.want) {
      printf("FAIL %s: %016llx, the RTX 3060 gives %016llx\\n", f.name, (unsigned long long)h, f.want);
      ++fails;
    }
  }
  if (!record) printf("%s: %d of %d mma forms match the RTX 3060\\n", fails ? "FAIL" : "PASS", ran - fails, ran);
  return fails ? 1 : 0;
}
''')
expected = {}
if len(sys.argv) > 2:
    for line in open(sys.argv[2]):
        name, h = line.split()
        expected[name] = h
import re
text = "\n".join(out)
text = re.sub(r"@@(\w+)@@", lambda m: expected.get(m.group(1), "0"), text)
open(sys.argv[1], "w").write(text)
print(len(forms), "forms")
