#!/usr/bin/env python3
"""Generates the thin cuBLAS entry points that are pure argument translation.

  gen_cublas_wrappers.py <cuda include dir> <out dir>

reads NVIDIA's public cublas_api.h and cublas.h (CUDA 13.0's were used for
the committed output) and writes, into <out dir>:

  cublas_64.cpp      the 64-bit-index (ILP64) forms, cublasSgemv_v2_64 and
                     the rest: each checks that every int64_t size, increment
                     and leading dimension fits an int and calls the 32-bit
                     form; one that does not fit is NOT_SUPPORTED, as the
                     hand-written _64 forms in cublas_api.cpp answer.
  cublas_legacy.cpp  the legacy (cublas.h, pre-_v2) API's handle-less BLAS
                     routines: each runs the _v2 routine on the library's
                     legacy handle (cublas_legacy_core.cpp), its scalars by
                     value turned into host pointers, its char options
                     ('N', 'T', 'U', 'L', ...) into the enums, and a value it
                     returns read back through the _v2 routine's result
                     pointer. The status lands where cublasGetError reports it.

Only declarations are read from the headers -- names, parameter lists and
types, the API itself -- and every body is written here. Forms whose
parameters differ in more than int -> int64_t (i?amax_64's int64_t result, the
grouped GEMMs' arrays) are written by hand in cublas_api.cpp and listed in
HAND_WRITTEN so they are skipped.
"""
import os
import re
import sys

# The _64 forms cublas_api.cpp (and its .inc files) define by hand.
HAND_WRITTEN = {
    "cublasAsumEx_64", "cublasAxpyEx_64", "cublasCcopy_v2_64", "cublasCgeam_64", "cublasCgemm3mEx_64",
    "cublasCgemmEx_64", "cublasCherk3mEx_64", "cublasCherkEx_64", "cublasCopyEx_64", "cublasCrot_v2_64",
    "cublasCsrot_v2_64", "cublasCswap_v2_64", "cublasCsyrk3mEx_64", "cublasCsyrkEx_64", "cublasDasum_v2_64",
    "cublasDaxpy_v2_64", "cublasDcopy_v2_64", "cublasDdot_v2_64", "cublasDgeam_64", "cublasDgemmGroupedBatched_64",
    "cublasDnrm2_v2_64", "cublasDotEx_64", "cublasDotcEx_64", "cublasDrot_v2_64", "cublasDrotm_v2_64",
    "cublasDscal_v2_64", "cublasDswap_v2_64", "cublasDzasum_v2_64", "cublasDznrm2_v2_64", "cublasGemmBatchedEx_64",
    "cublasGemmEx_64", "cublasGemmGroupedBatchedEx_64", "cublasGemmStridedBatchedEx_64", "cublasIamaxEx_64",
    "cublasIaminEx_64", "cublasIcamax_v2_64", "cublasIcamin_v2_64", "cublasIdamax_v2_64", "cublasIdamin_v2_64",
    "cublasIsamax_v2_64", "cublasIsamin_v2_64", "cublasIzamax_v2_64", "cublasIzamin_v2_64", "cublasNrm2Ex_64",
    "cublasRotEx_64", "cublasRotmEx_64", "cublasSasum_v2_64", "cublasSaxpy_v2_64", "cublasScalEx_64",
    "cublasScasum_v2_64", "cublasScnrm2_v2_64", "cublasScopy_v2_64", "cublasSdot_v2_64", "cublasSgeam_64",
    "cublasSgemmEx_64", "cublasSgemmGroupedBatched_64", "cublasSnrm2_v2_64", "cublasSrot_v2_64",
    "cublasSrotm_v2_64", "cublasSscal_v2_64", "cublasSswap_v2_64", "cublasSwapEx_64", "cublasZcopy_v2_64",
    "cublasZdrot_v2_64", "cublasZgeam_64", "cublasZrot_v2_64", "cublasZswap_v2_64",
}

HEADER = """// GENERATED by nvidia/tools/gen_cublas_wrappers.py from the declarations in
// NVIDIA's {hdr} (CUDA 13.0). Do not edit; change the generator.
"""


def declarations(path):
    """(return type, name, [(type, name)]) for every function a header declares."""
    text = open(path).read()
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    text = re.sub(r"//[^\n]*", " ", text)
    text = re.sub(r"^\s*#[^\n]*", " ", text, flags=re.M)
    text = re.sub(r"\s+", " ", text)
    out = []
    for m in re.finditer(r"([A-Za-z_][\w ]*?\**)\s*CUBLASWINAPI\s+(cublas\w+)\s*\(([^()]*)\)\s*;", text):
        ret, name, params = m.group(1).strip(), m.group(2), m.group(3).strip()
        plist = []
        if params and params != "void":
            for p in params.split(","):
                p = p.strip()
                pm = re.match(r"(.*?)(\w+)\s*(\[\s*\])?$", p)
                ptype, pname, arr = pm.group(1).strip(), pm.group(2), pm.group(3)
                plist.append((ptype + (" []" if arr else ""), pname, p))
        out.append((ret, name, plist))
    return out


def norm(t):
    return re.sub(r"\s+", " ", t.replace("*", " * ")).strip()


def gen_64(api):
    decl = {name: (ret, params) for ret, name, params in api}
    lines = [HEADER.format(hdr="cublas_api.h"), """//
// The 64-bit-index (ILP64) forms CUDA 12 added, onto the 32-bit ones: a size,
// increment, leading dimension or batch count beyond the range of int is
// refused as NOT_SUPPORTED rather than truncated (a host-computed operand that
// large would not fit in memory anyway), and everything else -- argument
// checks, pointer modes, graph capture -- is the 32-bit routine's.
#include <cublas_v2.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>

#include <cstdint>

#define VGPU_EXPORT extern "C" __attribute__((visibility("default")))

namespace {
inline bool fits(int64_t v) { return v >= INT32_MIN && v <= INT32_MAX; }
}  // namespace
"""]
    count = 0
    for ret, name, params in api:
        if not name.endswith("_64") or name in HAND_WRITTEN:
            continue
        base = name[:-3]
        if base not in decl:
            continue
        bret, bparams = decl[base]
        if bret != ret or len(bparams) != len(params):
            continue
        checks, args, ok = [], [], True
        for (t64, n64, _), (t32, _, _) in zip(params, bparams):
            if norm(t64) == norm(t32):
                args.append(n64)
            elif norm(t64) == "int64_t" and norm(t32) == "int":
                checks.append(n64)
                args.append("(int)" + n64)
            else:
                ok = False
                break
        if not ok:
            continue
        sig = ", ".join(full for _, _, full in params)
        body = []
        if checks:
            body.append("  if (!(" + " && ".join(f"fits({c})" for c in checks) + ")) return CUBLAS_STATUS_NOT_SUPPORTED;")
        body.append(f"  return {base}({', '.join(args)});")
        lines.append(f"VGPU_EXPORT {ret} {name}({sig}) {{\n" + "\n".join(body) + "\n}")
        count += 1
    return "\n".join(lines) + "\n", count


# The enum a legacy char option becomes, by the _v2 parameter's type.
CHAR_ENUMS = {
    "cublasOperation_t": "vgpu_legacy::op",
    "cublasFillMode_t": "vgpu_legacy::fill",
    "cublasSideMode_t": "vgpu_legacy::side",
    "cublasDiagType_t": "vgpu_legacy::diag",
}
# The legacy routines that are not BLAS: written by hand in cublas_legacy_core.cpp.
LEGACY_CORE = {"cublasInit", "cublasShutdown", "cublasGetError", "cublasGetVersion", "cublasAlloc", "cublasFree",
               "cublasSetKernelStream"}


def gen_legacy(legacy, api):
    decl = {name: (ret, params) for ret, name, params in api}
    lines = [HEADER.format(hdr="cublas.h"), """//
// The legacy cuBLAS API's handle-less BLAS routines (cublas.h), which
// NVIDIA's libcublas.so.13 still exports: each is the _v2 routine run on the
// legacy handle cublasInit created. A status other than success is kept for
// cublasGetError, and a routine that returns a value returns 0 when it fails.
#include <cublas.h>

#include "cublas_legacy.hpp"

#define VGPU_EXPORT extern "C" __attribute__((visibility("default")))
"""]
    count = 0
    for ret, name, params in legacy:
        if name in LEGACY_CORE:
            continue
        target = name + "_v2" if name + "_v2" in decl else None
        if target is None:
            raise SystemExit(f"no _v2 form for legacy {name}")
        tret, tparams = decl[target]
        has_result = ret != "void"
        want = len(params) + 1 + (1 if has_result else 0)
        # The legacy trmm writes B in place; the _v2 form writes a C, given B.
        in_place = name.endswith("trmm") and len(tparams) == want + 2
        if in_place:
            tparams = tparams[:-2]
        if len(tparams) != want:
            raise SystemExit(f"{name}: {len(params)} legacy params vs {len(tparams)} in {target}")
        body, args = [], ["h"]
        for (lt, ln, _), (vt, _, _) in zip(params, tparams[1:]):
            lt_n, vt_n = norm(lt), norm(vt)
            if lt_n == "char":
                enum = CHAR_ENUMS[vt_n]
                if name.endswith("gemv") and enum == "vgpu_legacy::op":
                    enum = "vgpu_legacy::op_gemv"   # lenient on the card, see cublas_legacy.hpp
                body.append(f"  {vt_n} {ln}_;")
                body.append(f"  if (!{enum}({ln}, &{ln}_)) return vgpu_legacy::fail<{ret}>(CUBLAS_STATUS_INVALID_VALUE);")
                args.append(ln + "_")
            elif lt_n == vt_n or norm("const " + lt_n) == vt_n:
                args.append(ln)
            elif norm("const " + lt_n + " *") == vt_n or norm(lt_n + " *") == vt_n:
                args.append("&" + ln)   # a scalar by value, the _v2 form takes its address
            else:
                raise SystemExit(f"{name}: cannot map {lt} {ln} onto {vt}")
        if in_place:
            args += ["B", "ldb"]
        if has_result:
            args.append("&result")
        sig = ", ".join(full for _, _, full in params) or "void"
        pre = ["  cublasHandle_t h = vgpu_legacy::handle();",
               f"  if (!h) return vgpu_legacy::fail<{ret}>(CUBLAS_STATUS_NOT_INITIALIZED);"]
        if has_result:
            pre.append(f"  {ret} result{{}};")
            post = [f"  const cublasStatus_t st = {target}({', '.join(args)});",
                    "  vgpu_legacy::record(st);",
                    f"  return st == CUBLAS_STATUS_SUCCESS ? result : {ret}{{}};"]
        else:
            post = [f"  vgpu_legacy::record({target}({', '.join(args)}));"]
        lines.append(f"VGPU_EXPORT {ret} {name}({sig}) {{\n" + "\n".join(pre + body + post) + "\n}")
        count += 1
    return "\n".join(lines) + "\n", count


def main():
    inc, out = sys.argv[1], sys.argv[2]
    api = declarations(os.path.join(inc, "cublas_api.h"))
    legacy = declarations(os.path.join(inc, "cublas.h"))
    text, n64 = gen_64(api)
    open(os.path.join(out, "cublas_64.cpp"), "w").write(text)
    text, nleg = gen_legacy(legacy, api)
    open(os.path.join(out, "cublas_legacy.cpp"), "w").write(text)
    print(f"{n64} _64 forms, {nleg} legacy routines")


if __name__ == "__main__":
    main()
