#!/usr/bin/env python3
"""Writes nvidia/src/hevc_tables.inc: the constant tables of Rec. ITU-T H.265 that the HEVC decoder
needs, read out of the Recommendation itself (v4, 12/2016) rather than typed in:

  Table 8-?? (8.6.4.2)   the 32x32 transform matrix transMatrix
  Table 9-5 .. 9-37      the CABAC context initialisation values initValue, for every ctxIdx of a syntax element
                         (the decoder maps them to initType with Table 9-4)

usage: gen_hevc_tables.py <T-REC-H.265-201612-S.pdf> <out.inc>
The PDF is the ITU-T's free download (itu.int/rec/T-REC-H.265); it is not kept in the repository.
Needs PyMuPDF (pip install pymupdf).
"""
import re
import sys

import fitz


def main():
    doc = fitz.open(sys.argv[1])
    text = '\n'.join(p.get_text() for p in doc)

    # ---- the transform matrix: 32 rows of 16 columns in each of two tables ----
    a = text.index('transMatrixCol0to15 =')
    b = text.index('transMatrixCol16to31 =')
    c = text.index('8.6.5', b)

    def rows(s):
        s = s.replace('−', '-')
        out = []
        for m in re.finditer(r'\{([^{}]*)\}', s):
            nums = [int(x) for x in re.findall(r'-?\d+', m.group(1))]
            if len(nums) == 16:
                out.append(nums)
        return out

    r1, r2 = rows(text[a:b]), rows(text[b:c])
    assert len(r1) == 32 and len(r2) == 32
    matrix = [r1[i] + r2[i] for i in range(32)]
    for k in range(32):   # even rows are symmetric, odd rows antisymmetric
        for n in range(16):
            assert matrix[k][31 - n] == (1 if k % 2 == 0 else -1) * matrix[k][n]

    # ---- context initialisation values ----
    names = {
        5: 'sao_merge', 6: 'sao_type_idx', 7: 'split_cu_flag', 8: 'cu_transquant_bypass_flag', 9: 'cu_skip_flag', 10: 'pred_mode_flag',
        11: 'part_mode', 12: 'prev_intra_luma_pred_flag', 13: 'intra_chroma_pred_mode', 14: 'rqt_root_cbf', 15: 'merge_flag', 16: 'merge_idx',
        17: 'inter_pred_idc', 18: 'ref_idx', 19: 'mvp_flag', 20: 'split_transform_flag', 21: 'cbf_luma', 22: 'cbf_chroma', 23: 'abs_mvd',
        24: 'cu_qp_delta_abs', 25: 'transform_skip_flag', 26: 'last_sig_coeff_x_prefix', 27: 'last_sig_coeff_y_prefix', 28: 'coded_sub_block_flag',
        29: 'sig_coeff_flag', 30: 'coeff_abs_level_greater1_flag', 31: 'coeff_abs_level_greater2_flag', 32: 'explicit_rdpcm_flag',
        33: 'explicit_rdpcm_dir_flag', 34: 'cu_chroma_qp_offset_flag', 35: 'cu_chroma_qp_offset_idx', 36: 'log2_res_scale_abs_plus1',
        37: 'res_scale_sign_flag'}
    body = {}
    for n in names:
        # the title occurs in the list of tables and then in the body; take the last one
        starts = [m.start() for m in re.finditer(r'Table 9-%d – Values of initValue' % n, text)]
        s = starts[-1]
        e = text.find('Table 9-%d – Values of initValue' % (n + 1), s + 10)
        nxt = re.search(r'Table 9-\d+ – ', text[s + 10:])
        end = s + 10 + nxt.start() if nxt else len(text)
        chunk = text[text.index('\n', s):end]
        chunk = re.sub(r'=====PAGE[^\n]*\n', ' ', chunk)
        chunk = re.sub(r'Rec\. ITU-T H\.265 v4 \(12/2016\)', ' ', chunk)
        toks = chunk.split()
        # segments between the 'initValue' markers: the first holds the header and the first run of ctxIdx numbers; every
        # later one starts with as many values as the run before it had and ends with the next run of ctxIdx numbers
        segs = []
        cur = []
        for t in toks:
            if t == 'initValue':
                segs.append(cur)
                cur = []
            else:
                cur.append(t)
        segs.append(cur)
        run = []
        for t in reversed(segs[0]):
            if re.fullmatch(r'\d+', t):
                run.insert(0, int(t))
            else:
                break
        assert run and run[0] == 0 and run == list(range(len(run))), (n, run)
        vals = []
        for k in range(1, len(segs)):
            take = segs[k][:len(run)]
            assert len(take) == len(run) and all(re.fullmatch(r'\d+', t) for t in take), (n, k, take)
            vals += [int(t) for t in take]
            rest = [int(t) for t in segs[k][len(run):] if re.fullmatch(r'\d+', t)]
            run = rest if k + 1 < len(segs) else []
        body[n] = vals

    with open(sys.argv[2], 'w') as f:
        f.write('// Generated by nvidia/tools/gen_hevc_tables.py from Rec. ITU-T H.265 v4 (12/2016); do not edit.\n\n')
        f.write('// 8.6.4.2: transMatrix[ frequency ][ position ]\n')
        f.write('static const int8_t kTransMatrix[32][32] = {\n')
        for row in matrix:
            f.write('    {' + ', '.join(str(x) for x in row) + '},\n')
        f.write('};\n\n')
        f.write('// Tables 9-5 to 9-37: initValue for every ctxIdx of the syntax element, in the order of the Recommendation.\n')
        for n, nm in sorted(names.items()):
            v = body[n]
            f.write('static const uint8_t kInit_%s[%d] = {%s};\n' % (nm, len(v), ', '.join(str(x) for x in v)))


main()
