#!/usr/bin/env python3
"""Generates the NVML getter probe (nvml_card_probe.c) from an nvml.h.

The probe calls every getter nvml.h declares on ONE device of whatever
libnvidia-ml.so.1 it is run against -- NVIDIA's driver on a card, or our shim --
and prints "<function> <return code> <first bytes of the first output>" per line.
It never calls anything that writes: names containing Set, Clear, Reset, Create,
Destroy, Modify, Remove, Discover, Validate, Register, Update, Activate or Freeze
are skipped, as are the PRM read/write and vGPU force-unload entry points.

usage: nvml_card_probe_gen.py <nvml.h> > nvml_card_probe.c
       cc -o probe nvml_card_probe.c -I<dir of nvml.h> -ldl
       probe <path to libnvidia-ml.so.1> <device index>
The arguments are generic: handles, zeroed 64 KiB buffers for every pointer,
the current version in the first word of every versioned struct, zero for every
scalar except where OVERRIDES says otherwise (a string length, a CPU-set size).
"""
import re, sys

SKIP = re.compile(r"Set|Clear|Reset|Create|Destroy|Modify|Remove|Discover|Validate|Register|Update|"
                  r"Activate|Freeze|ForceGspUnload|ReadWritePRM|ReadPRMCounters|Init|Shutdown|"
                  r"EventSet|Free|Alloc|GpmSampleGet|GpmMigSampleGet|GpmMetricsGet|ErrorString|"
                  r"ExportTable|ProcessName")
# Argument values for scalars that must not be zero to get a real answer.
OVERRIDES = {
    "length": 128, "size": 128, "cpuSetSize": 2, "nodeSetSize": 2,
}
def protos(path):
    t = open(path, errors="ignore").read()
    t = re.sub(r"/\*.*?\*/", "", t, flags=re.S)
    t = re.sub(r"//[^\n]*", "", t)
    out = {}
    for m in re.finditer(r"(?:nvmlReturn_t|const char\s*\*|unsigned int)\s+DECLDIR\s+(nvml\w+)\s*\(([^;{]*?)\)\s*;", t, flags=re.S):
        out[m.group(1)] = " ".join(m.group(2).split())
    return out, t

def main():
    hdr = sys.argv[1]
    P, text = protos(hdr)
    vers = {}
    for m in re.finditer(r"#define\s+(nvml\w+?)_v(\d+)\s+NVML_STRUCT_VERSION", open(hdr).read()):
        vers[m.group(1)] = max(vers.get(m.group(1), 0), int(m.group(2)))
    print("// generated by nvml_card_probe_gen.py from", hdr)
    print('#include <dlfcn.h>\n#include <stdint.h>\n#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <nvml.h>')
    print("typedef long (*gen_fn)(uintptr_t,uintptr_t,uintptr_t,uintptr_t,uintptr_t,uintptr_t);")
    print("typedef struct { const char* name; int nargs; int kind[6]; uintptr_t val[6]; unsigned ver[6]; } Call;")
    print("// kind: 0 value, 1 device, 2 buffer, 3 second device (the same one)")
    print("static const Call kCalls[] = {")
    n = 0
    for name in sorted(P):
        if SKIP.search(name):
            continue
        args = [a.strip() for a in P[name].split(",")] if P[name] not in ("void", "") else []
        if any("nvmlUnit_t" in a or "nvmlGpuInstance_t" in a or "nvmlComputeInstance_t" in a or
               "nvmlVgpuInstance_t" in a or "nvmlGpmSample_t" in a or "nvmlEventSet_t" in a or
               "nvmlVgpuTypeId_t" in a for a in args):
            continue    # handles that need an object we do not have; their ids are documented
        kinds, vals, vs = [], [], []
        seen_dev = 0
        for a in args:
            a_clean = re.sub(r"\bconst\b", "", a).strip()
            pname = re.search(r"(\w+)\s*$", a_clean).group(1)
            if "nvmlDevice_t" in a_clean and "*" not in a_clean:
                kinds.append(1 if seen_dev == 0 else 3); seen_dev += 1; vals.append(0); vs.append("0")
            elif "*" in a_clean:
                tm = re.search(r"(nvml\w+_t)\s*\*", a_clean)
                v = "0"
                if tm:
                    base = re.sub(r"(_v\d+)?_t$", "", tm.group(1))
                    explicit = re.search(r"_v(\d+)_t$", tm.group(1))
                    if explicit and (base + "_v" + explicit.group(1)) in vers or base in vers:
                        n_ = int(explicit.group(1)) if explicit else vers[base]
                        if re.search(r"^%s_v%d\b" % (base, n_), "\n".join(re.findall(r"#define\s+(%s_v%d)\s" % (base, n_), open(hdr).read()))):
                            v = "%s_v%d" % (base, n_)
                kinds.append(2); vals.append(0); vs.append(v)
            else:
                kinds.append(0); vals.append(OVERRIDES.get(pname, 0)); vs.append("0")
        print('  {"%s", %d, {%s}, {%s}, {%s}},' % (name, len(args), ",".join(map(str, kinds + [0]*(6-len(kinds)))),
              ",".join(map(str, vals + [0]*(6-len(vals)))), ",".join(vs + ["0"]*(6-len(vs)))))
        n += 1
    print("};")
    print(r'''
static unsigned char g_bufs[6][65536];
int main(int argc, char** argv) {
  void* h = dlopen(argv[1], RTLD_NOW);
  if (!h) { fprintf(stderr, "dlopen: %s\n", dlerror()); return 2; }
  long (*init)(void) = dlsym(h, "nvmlInit_v2");
  long (*byidx)(unsigned, void**) = dlsym(h, "nvmlDeviceGetHandleByIndex_v2");
  if (!init || !byidx) return 2;
  long rc = init();
  if (rc) { printf("INIT %ld\n", rc); return 1; }
  void* dev = 0;
  rc = byidx((unsigned)atoi(argv[2]), &dev);
  if (rc) { printf("HANDLE %ld\n", rc); return 1; }
  for (size_t i = 0; i < sizeof kCalls / sizeof kCalls[0]; ++i) {
    const Call* c = &kCalls[i];
    gen_fn f = (gen_fn)dlsym(h, c->name);
    if (!f) { printf("%s MISSING\n", c->name); continue; }
    uintptr_t a[6] = {0};
    for (int k = 0; k < c->nargs; ++k) {
      memset(g_bufs[k], 0, sizeof g_bufs[k]);
      switch (c->kind[k]) {
        case 1: case 3: a[k] = (uintptr_t)dev; break;
        case 2: a[k] = (uintptr_t)g_bufs[k]; if (c->ver[k]) *(unsigned*)g_bufs[k] = c->ver[k]; break;
        default: a[k] = c->val[k];
      }
    }
    long r = f(a[0], a[1], a[2], a[3], a[4], a[5]);
    printf("%s %ld", c->name, r);
    if (r == 0) {
      for (int k = 0; k < c->nargs; ++k) if (c->kind[k] == 2) {
        printf(" ");
        for (int b = 0; b < 48; ++b) printf("%02x", g_bufs[k][b]);
        break;
      }
    }
    printf("\n");
  }
  return 0;
}''')
main()
