#!/usr/bin/env python3
"""Lists the functions of AMD SMI's library, for VirtualGPU's libamd_smi.

AMD's Python package (amdsmi) binds every function of libamd_smi when it is
imported, so a library standing in for it must export each one, even those it
answers AMDSMI_STATUS_NOT_SUPPORTED. This reads the declarations from AMD's
public header (amd_smi/amdsmi.h, MIT license) and writes the list that
amd/src/amd_smi_stubs.cpp turns into those answers.

    amd/tools/amdsmi-symbols.py path/to/amdsmi.h > amd/src/amd_smi_symbols.inc

The header is AMD SMI's at the release the list names (rocm-7.2.3, library
26.2): github.com/ROCm/amdsmi, include/amd_smi/amdsmi.h.
"""
import re
import sys

# Bound by the Python package though the header does not declare it.
EXTRA = ["amdsmi_free_name_value_pairs"]


def functions(header: str) -> list:
    text = re.sub(r"/\*[\s\S]*?\*/", "", header)
    text = re.sub(r"//.*", "", text)
    names = re.findall(r"\bamdsmi_status_t\s+(amdsmi_\w+)\s*\([^;{]*?\)\s*;", text)
    return sorted(set(names) | set(EXTRA))


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    header = open(sys.argv[1], encoding="utf-8").read()
    version = re.search(r"#define AMDSMI_LIB_VERSION_MAJOR (\d+)[\s\S]*?#define AMDSMI_LIB_VERSION_MINOR (\d+)", header)
    names = functions(header)
    print("// Generated by amd/tools/amdsmi-symbols.py from AMD SMI's amdsmi.h")
    if version:
        print(f"// (library {version.group(1)}.{version.group(2)}): every function its Python package binds.")
    for n in names:
        print(f"AMDSMI_SYMBOL({n})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
