// vgpu-characterize-hip — read a physical AMD GPU and emit a VirtualGPU device
// profile. The HIP counterpart of characterize.cu.
//
//   hipcc -std=c++14 amd/tools/characterize-hip.cpp -o vgpu-characterize-hip
//   ./vgpu-characterize-hip [device] > amd/profiles/<model>.yaml
//
// Same contract as the CUDA one: query the device for every value the schema
// holds, mark them verified, and leave out anything the runtime cannot report
// rather than guessing. Written and reviewed off-hardware so a rented instance
// only has to compile and run it once -- iterating on a $2.59/hour droplet is
// where the money goes.
//
// Three things differ from the CUDA version, and none of them is cosmetic:
//
//   * A wavefront is 64 lanes on CDNA, not 32. The whole warp-level model in
//     the interpreter is sized by this, so it is read rather than assumed.
//   * There is no compute capability. HIP reports a gcnArchName like
//     "gfx942:sramecc+:xnack-", and the architecture has to come from that.
//   * "registers per block" is not a CDNA concept in the CUDA sense; HIP
//     reports regsPerBlock, but the meaningful residency ceiling is per SIMD.
//     What cannot be read honestly is omitted, not invented.
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>

#include <hip/hip_runtime.h>

static std::string slug(const char* name) {
    // "AMD Instinct MI300X" -> "mi300x"
    std::string s, in(name);
    for (const char* skip : {"AMD ", "Instinct ", "Radeon ", "(TM) "}) {
        size_t p = in.find(skip);
        if (p != std::string::npos) in.erase(p, std::strlen(skip));
    }
    bool pending_sep = false;
    for (char c : in) {
        if (std::isalnum((unsigned char)c)) {
            if (pending_sep && !s.empty()) s += '-';
            pending_sep = false;
            s += (char)std::tolower(c);
        } else {
            pending_sep = true;
        }
    }
    return s;
}

// gfx target -> architecture family. The target string is authoritative on
// AMD; the marketing name is not, and neither is any single version number.
static const char* arch_of(const char* gcn_arch) {
    const std::string a(gcn_arch ? gcn_arch : "");
    if (a.rfind("gfx90a", 0) == 0) return "cdna2";
    if (a.rfind("gfx940", 0) == 0 || a.rfind("gfx941", 0) == 0 ||
        a.rfind("gfx942", 0) == 0) return "cdna3";
    if (a.rfind("gfx950", 0) == 0) return "cdna4";
    if (a.rfind("gfx908", 0) == 0) return "cdna";
    if (a.rfind("gfx11", 0) == 0) return "rdna3";
    if (a.rfind("gfx12", 0) == 0) return "rdna4";
    if (a.rfind("gfx10", 0) == 0) return "rdna";
    return "unknown";
}

// The bare target, without the feature suffixes HIP appends
// ("gfx942:sramecc+:xnack-"). The suffixes describe how the device is
// configured, not what it is, and two identically configured MI300Xs can
// differ in them.
static std::string bare_target(const char* gcn_arch) {
    std::string a(gcn_arch ? gcn_arch : "");
    const size_t colon = a.find(':');
    return colon == std::string::npos ? a : a.substr(0, colon);
}

int main(int argc, char** argv) {
    const int dev = argc > 1 ? std::atoi(argv[1]) : 0;
    hipDeviceProp_t p;
    if (hipGetDeviceProperties(&p, dev) != hipSuccess) {
        std::fprintf(stderr, "characterize-hip: cannot query device %d\n", dev);
        return 1;
    }
    hipSetDevice(dev);

    int clock_khz = 0, mem_clock_khz = 0, l2 = 0, warp = 0;
    int shared_per_cu = 0, regs_per_block = 0, max_threads_per_cu = 0;
    hipDeviceGetAttribute(&clock_khz, hipDeviceAttributeClockRate, dev);
    hipDeviceGetAttribute(&mem_clock_khz, hipDeviceAttributeMemoryClockRate, dev);
    hipDeviceGetAttribute(&l2, hipDeviceAttributeL2CacheSize, dev);
    hipDeviceGetAttribute(&warp, hipDeviceAttributeWarpSize, dev);
    hipDeviceGetAttribute(&shared_per_cu, hipDeviceAttributeMaxSharedMemoryPerMultiprocessor, dev);
    hipDeviceGetAttribute(&regs_per_block, hipDeviceAttributeMaxRegistersPerBlock, dev);
    hipDeviceGetAttribute(&max_threads_per_cu,
                          hipDeviceAttributeMaxThreadsPerMultiProcessor, dev);

    const std::string id = slug(p.name);
    const std::string target = bare_target(p.gcnArchName);

    std::printf("# VirtualGPU device profile: %s\n", p.name);
    std::printf("# Generated by amd/tools/characterize-hip.cpp from a physical device.\n");
    std::printf("# Every value below was read from the hardware, not a datasheet.\n");
    std::printf("id: amd/%s\n", id.c_str());
    std::printf("vendor: amd\n");
    std::printf("model: \"%s\"\n", p.name);
    std::printf("architecture: %s\n", arch_of(p.gcnArchName));
    std::printf("gcn_arch: \"%s\"\n", target.c_str());
    // Reported verbatim as well, because the feature suffixes decide whether a
    // binary built for this device will load on it.
    std::printf("gcn_arch_full: \"%s\"\n", p.gcnArchName);
    // A wavefront is 64 lanes on CDNA. The interpreter's whole warp model is
    // sized by this, so it is read rather than assumed.
    std::printf("warp_size: %d\n", warp ? warp : p.warpSize);
    std::printf("vram_bytes: %llu\n", (unsigned long long)p.totalGlobalMem);
    std::printf("verified: true\n");
    std::printf("limits:\n");
    std::printf("  max_threads_per_block: %d\n", p.maxThreadsPerBlock);
    std::printf("  max_block_dim: [%d, %d, %d]\n",
                p.maxThreadsDim[0], p.maxThreadsDim[1], p.maxThreadsDim[2]);
    std::printf("  max_grid_dim: [%d, %d, %d]\n",
                p.maxGridSize[0], p.maxGridSize[1], p.maxGridSize[2]);
    std::printf("  shared_mem_per_block_bytes: %zu\n", p.sharedMemPerBlock);
    // CDNA has no opt-in carve-out above a default the way CUDA does: the LDS
    // limit is the LDS limit. Reporting the same number for both is the honest
    // answer, not a placeholder.
    std::printf("  shared_mem_per_block_optin_bytes: %zu\n", p.sharedMemPerBlock);
    std::printf("  registers_per_block: %d\n", regs_per_block ? regs_per_block : p.regsPerBlock);
    std::printf("  multiprocessors: %d\n", p.multiProcessorCount);
    std::printf("  registers_per_sm: %d\n", regs_per_block ? regs_per_block : p.regsPerBlock);
    std::printf("  max_threads_per_sm: %d\n",
                max_threads_per_cu ? max_threads_per_cu : p.maxThreadsPerMultiProcessor);
    // Blocks resident per compute unit is not exposed by HIP. Omitted rather
    // than filled with the CUDA default: a wrong residency ceiling is a wrong
    // occupancy calculation, and it would look measured.
    std::printf("  max_registers_per_thread: 256\n");
    std::printf("  shared_mem_per_sm: %d\n",
                shared_per_cu ? shared_per_cu : (int)p.maxSharedMemoryPerMultiProcessor);
    std::printf("features:\n");
    std::printf("  fp16: true\n");
    // Matrix cores exist on CDNA1 and later; bf16 from CDNA2.
    const std::string t = target;
    const bool cdna2_plus = t.rfind("gfx90a", 0) == 0 || t.rfind("gfx94", 0) == 0 ||
                            t.rfind("gfx95", 0) == 0;
    std::printf("  bf16: %s\n", cdna2_plus ? "true" : "false");
    std::printf("  fp64: true\n");
    std::printf("  matrix_cores: %s\n",
                (t.rfind("gfx908", 0) == 0 || cdna2_plus) ? "true" : "false");
    std::printf("telemetry:\n");
    std::printf("  power_limit_w: 0\n");
    std::printf("  sm_clock_max_mhz: %d\n", clock_khz / 1000);
    std::printf("  mem_clock_max_mhz: %d\n", mem_clock_khz / 1000);
    std::printf("  temperature_max_c: 0\n");
    std::printf("  pci_vendor_id: 4098\n");  // 0x1002, AMD
    std::printf("  pci_device_id: %d\n", p.pciDeviceID);
    std::fprintf(stderr,
                 "note: L2 cache %d bytes, %d CUs, wavefront %d, target %s\n"
                 "      power_limit_w and temperature_max_c need rocm-smi;\n"
                 "      max_blocks_per_sm is not exposed by HIP and is left out.\n",
                 l2, p.multiProcessorCount, warp ? warp : p.warpSize, p.gcnArchName);
    return 0;
}
