#!/usr/bin/env python3
"""Writes amd/src/rocprofiler_hip_ids.inc: the number rocprofiler-sdk gives each
HIP runtime function, which a trace record names its call by. Taken from
rocprofiler-sdk's hip/runtime_api_id.h, so VirtualGPU's records and AMD's
profiler agree on which call is which.

  amd/tools/rocprofiler-hip-ids.py <rocprofiler-sdk include dir> [out]
"""
import re
import sys

HEADER = '''// The number rocprofiler-sdk gives each HIP runtime function, from its
// hip/runtime_api_id.h (MIT licence, Copyright (c) 2023-2025 Advanced Micro
// Devices, Inc.; the notice is in vgpu/rocprofiler_abi.hpp). Generated by
// amd/tools/rocprofiler-hip-ids.py; do not edit.
'''


def main():
    inc = sys.argv[1]
    dest = sys.argv[2] if len(sys.argv) > 2 else 'amd/src/rocprofiler_hip_ids.inc'
    text = open(f'{inc}/rocprofiler-sdk/hip/runtime_api_id.h').read()
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
    text = re.sub(r'//[^\n]*', '', text)
    body = text[text.index('typedef enum'):]
    value = -1
    rows = []
    for m in re.finditer(r'ROCPROFILER_HIP_RUNTIME_API_ID_(\w+)\s*(?:=\s*([^,\n]+))?,', body):
        name, given = m.group(1), m.group(2)
        if given is not None:
            given = given.strip()
            if given.startswith('ROCPROFILER_HIP_RUNTIME_API_ID_'):
                value = dict(rows)[given[len('ROCPROFILER_HIP_RUNTIME_API_ID_'):]]
            else:
                value = int(given, 0)
        else:
            value += 1
        rows.append((name, value))
    lines = [HEADER]
    for name, value in rows:
        if name in ('NONE', 'LAST'):
            continue
        lines.append(f'{{"{name}", {value}}},')
    last = dict(rows)['LAST']
    lines.append(f'// ROCPROFILER_HIP_RUNTIME_API_ID_LAST = {last}')
    open(dest, 'w').write('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
