// vgpu-characterize — read a physical GPU and emit a VirtualGPU device profile.
//
// This is the "hardware as oracle" step ARCHITECTURE.md describes: instead of
// transcribing spec sheets, query a real device for every value the profile
// schema holds and write it out. Values obtained this way are marked
// verified: true; anything the runtime cannot report is left out rather than
// guessed.
//
//   nvcc -std=c++14 tools/characterize.cu -o vgpu-characterize
//   ./vgpu-characterize [device] > profiles/nvidia/<model>.yaml
//
// Run it on each GPU you want to support. It needs a real device; it is not
// built as part of the normal (GPU-free) build.
#include <cstdio>
#include <cstring>
#include <cctype>
#include <string>
#include <cuda_runtime.h>
#include <cuda.h>

static std::string slug(const char* name) {
    // "NVIDIA GeForce RTX 3060" -> "rtx3060"; "NVIDIA A100-SXM4-80GB" -> "a100-sxm4-80gb"
    std::string s, in(name);
    for (const char* skip : {"NVIDIA ", "GeForce ", "Tesla "}) {
        size_t p = in.find(skip);
        if (p != std::string::npos) in.erase(p, std::strlen(skip));
    }
    // Separators become hyphens rather than vanishing: dropping them turned
    // "H100 80GB HBM3" into "h10080gbhbm3".
    bool pending_sep = false;
    for (char c : in) {
        if (std::isalnum((unsigned char)c)) {
            if (pending_sep && !s.empty()) s += '-';
            pending_sep = false;
            s += (char)std::tolower(c);
        } else {
            pending_sep = true;
        }
    }
    return s;
}

// Architecture name from compute capability, for the profile's semantics layer.
static const char* arch_of(int major, int minor) {
    switch (major) {
        case 6: return "pascal";
        case 7: return minor < 5 ? "volta" : "turing";
        case 8: return minor == 0 ? "ampere" : (minor == 9 ? "ada" : "ampere");
        case 9: return "hopper";
        case 10: return "blackwell";
        case 12: return "blackwell";
        default: return "unknown";
    }
}

int main(int argc, char** argv) {
    int dev = argc > 1 ? atoi(argv[1]) : 0;
    cudaDeviceProp p;
    if (cudaGetDeviceProperties(&p, dev) != cudaSuccess) {
        std::fprintf(stderr, "characterize: cannot query device %d\n", dev);
        return 1;
    }
    cudaSetDevice(dev);

    // Driver-API attributes that cudaDeviceProp does not carry.
    CUdevice cud; int optin_shared = 0, clock_khz = 0, mem_clock_khz = 0, l2 = 0;
    if (cuInit(0) == CUDA_SUCCESS && cuDeviceGet(&cud, dev) == CUDA_SUCCESS) {
        cuDeviceGetAttribute(&optin_shared,
            CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK_OPTIN, cud);
        cuDeviceGetAttribute(&clock_khz, CU_DEVICE_ATTRIBUTE_CLOCK_RATE, cud);
        cuDeviceGetAttribute(&mem_clock_khz, CU_DEVICE_ATTRIBUTE_MEMORY_CLOCK_RATE, cud);
        cuDeviceGetAttribute(&l2, CU_DEVICE_ATTRIBUTE_L2_CACHE_SIZE, cud);
    }

    std::string id = slug(p.name);
    std::printf("# VirtualGPU device profile: %s\n", p.name);
    std::printf("# Generated by tools/characterize.cu from a physical device.\n");
    std::printf("# Every value below was read from the hardware, not a datasheet.\n");
    std::printf("id: nvidia/%s\n", id.c_str());
    std::printf("vendor: nvidia\n");
    std::printf("model: \"%s\"\n", p.name);
    std::printf("architecture: %s\n", arch_of(p.major, p.minor));
    std::printf("compute_capability: \"%d.%d\"\n", p.major, p.minor);
    std::printf("warp_size: %d\n", p.warpSize);
    std::printf("vram_bytes: %llu\n", (unsigned long long)p.totalGlobalMem);
    std::printf("verified: true\n");
    std::printf("limits:\n");
    std::printf("  max_threads_per_block: %d\n", p.maxThreadsPerBlock);
    std::printf("  max_block_dim: [%d, %d, %d]\n",
                p.maxThreadsDim[0], p.maxThreadsDim[1], p.maxThreadsDim[2]);
    std::printf("  max_grid_dim: [%d, %d, %d]\n",
                p.maxGridSize[0], p.maxGridSize[1], p.maxGridSize[2]);
    std::printf("  shared_mem_per_block_bytes: %zu\n", p.sharedMemPerBlock);
    std::printf("  shared_mem_per_block_optin_bytes: %d\n",
                optin_shared ? optin_shared : (int)p.sharedMemPerBlock);
    std::printf("  registers_per_block: %d\n", p.regsPerBlock);
    std::printf("  multiprocessors: %d\n", p.multiProcessorCount);
    // The residency ceilings, which decide occupancy. They were being written
    // in by hand after the fact, which is exactly the kind of value that ends
    // up carrying a datasheet's number instead of the device's.
    int regs_per_sm = 0, blocks_per_sm = 0, shared_per_sm = 0;
    cudaDeviceGetAttribute(&regs_per_sm, cudaDevAttrMaxRegistersPerMultiprocessor, dev);
    cudaDeviceGetAttribute(&blocks_per_sm, cudaDevAttrMaxBlocksPerMultiprocessor, dev);
    cudaDeviceGetAttribute(&shared_per_sm, cudaDevAttrMaxSharedMemoryPerMultiprocessor, dev);
    std::printf("  registers_per_sm: %d\n", regs_per_sm ? regs_per_sm : p.regsPerBlock);
    std::printf("  max_threads_per_sm: %d\n", p.maxThreadsPerMultiProcessor);
    std::printf("  max_blocks_per_sm: %d\n", blocks_per_sm ? blocks_per_sm : 16);
    std::printf("  max_registers_per_thread: 255\n");
    std::printf("  shared_mem_per_sm: %d\n",
                shared_per_sm ? shared_per_sm : (int)p.sharedMemPerMultiprocessor);
    std::printf("features:\n");
    std::printf("  fp16: %s\n", p.major >= 6 ? "true" : "false");
    std::printf("  bf16: %s\n", p.major >= 8 ? "true" : "false");
    std::printf("  fp64: true\n");
    std::printf("  tensor_cores: %s\n", p.major >= 7 ? "true" : "false");
    std::printf("telemetry:\n");
    std::printf("  power_limit_w: %d\n", 0);  // filled below from NVML if available
    std::printf("  sm_clock_max_mhz: %d\n", clock_khz / 1000);
    std::printf("  mem_clock_max_mhz: %d\n", mem_clock_khz / 1000);
    std::printf("  temperature_max_c: %d\n", 0);
    std::printf("  pci_vendor_id: 4318\n");
    std::printf("  pci_device_id: %d\n", 0);
    std::fprintf(stderr,
                 "note: power_limit_w, temperature_max_c and pci_device_id need NVML;\n"
                 "      run tools/characterize-telemetry.sh to fill them in.\n");
    return 0;
}
