// Warp, atomic, memory and 16/64-bit integer PTX forms, each variant run by
// 256 threads (eight warps) over the same operand triples, with a word of
// global and of shared memory per thread; each variant's results and the
// memory it left are hashed and compared with an RTX 3060's (sm_86), recorded
// in ptx_warp_mem_expected.inc (`ptx_warp_mem --print` prints them; `--dump N`
// prints variant N's values). Generated by ptx_warp_mem_gen.py. Prints PASS on
// the last line, and runs the same on a GPU.
#include <cstdio>
#include <cstdlib>
#include <cstring>
struct Expected { const char* tag; unsigned long long hash; };
static const Expected kExpected[] = {
#include "ptx_warp_mem_expected.inc"
};
constexpr int kN = 256;
__global__ void k(int v, const unsigned* in, unsigned* out, unsigned long long* g) {
  __shared__ unsigned sh[kN];
  const int i = threadIdx.x;
  const unsigned a = in[3 * i], b = in[3 * i + 1], c = in[3 * i + 2];
  g[i] = c | ((unsigned long long)b << 32);
  sh[i] = c;
  __syncthreads();
  const unsigned sa = (unsigned)__cvta_generic_to_shared(sh);
  unsigned d = 0;
  switch (v) {
    case 0: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.up.b32 %0, %1, l, 0x1f, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 1: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.up.b32 %0, %1, l, 0x1c1f, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 2: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.up.b32 %0, %1, l, 0x0, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 3: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.up.b32 %0, %1, l, 0x101f, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 4: asm volatile("{ .reg .pred p; .reg .u32 l; and.b32 l, %2, 31; shfl.sync.up.b32 %0|p, %1, l, 0x1f, 0xffffffff; @!p add.u32 %0, %0, 1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 5: asm volatile("shfl.sync.up.b32 %0, %1, 5, 0x1f, 0xffffffff;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 6: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.down.b32 %0, %1, l, 0x1f, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 7: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.down.b32 %0, %1, l, 0x1c1f, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 8: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.down.b32 %0, %1, l, 0x0, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 9: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.down.b32 %0, %1, l, 0x101f, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 10: asm volatile("{ .reg .pred p; .reg .u32 l; and.b32 l, %2, 31; shfl.sync.down.b32 %0|p, %1, l, 0x1f, 0xffffffff; @!p add.u32 %0, %0, 1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 11: asm volatile("shfl.sync.down.b32 %0, %1, 5, 0x1f, 0xffffffff;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 12: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.bfly.b32 %0, %1, l, 0x1f, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 13: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.bfly.b32 %0, %1, l, 0x1c1f, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 14: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.bfly.b32 %0, %1, l, 0x0, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 15: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.bfly.b32 %0, %1, l, 0x101f, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 16: asm volatile("{ .reg .pred p; .reg .u32 l; and.b32 l, %2, 31; shfl.sync.bfly.b32 %0|p, %1, l, 0x1f, 0xffffffff; @!p add.u32 %0, %0, 1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 17: asm volatile("shfl.sync.bfly.b32 %0, %1, 5, 0x1f, 0xffffffff;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 18: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.idx.b32 %0, %1, l, 0x1f, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 19: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.idx.b32 %0, %1, l, 0x1c1f, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 20: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.idx.b32 %0, %1, l, 0x0, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 21: asm volatile("{ .reg .u32 l; and.b32 l, %2, 31; shfl.sync.idx.b32 %0, %1, l, 0x101f, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 22: asm volatile("{ .reg .pred p; .reg .u32 l; and.b32 l, %2, 31; shfl.sync.idx.b32 %0|p, %1, l, 0x1f, 0xffffffff; @!p add.u32 %0, %0, 1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 23: asm volatile("shfl.sync.idx.b32 %0, %1, 5, 0x1f, 0xffffffff;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 24: asm volatile("{ .reg .pred p, q; and.b32 %0, %1, 1; setp.ne.u32 p, %0, 0; vote.sync.all.pred q, p, 0xffffffff; selp.u32 %0, 1, 0, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 25: asm volatile("{ .reg .pred p, q; setp.ne.u32 p, %1, 0; vote.sync.all.pred q, p, 0xffffffff; selp.u32 %0, 1, 0, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 26: asm volatile("{ .reg .pred p, q; and.b32 %0, %1, 1; setp.ne.u32 p, %0, 0; vote.sync.any.pred q, p, 0xffffffff; selp.u32 %0, 1, 0, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 27: asm volatile("{ .reg .pred p, q; setp.ne.u32 p, %1, 0; vote.sync.any.pred q, p, 0xffffffff; selp.u32 %0, 1, 0, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 28: asm volatile("{ .reg .pred p, q; and.b32 %0, %1, 1; setp.ne.u32 p, %0, 0; vote.sync.uni.pred q, p, 0xffffffff; selp.u32 %0, 1, 0, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 29: asm volatile("{ .reg .pred p, q; setp.ne.u32 p, %1, 0; vote.sync.uni.pred q, p, 0xffffffff; selp.u32 %0, 1, 0, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 30: asm volatile("{ .reg .pred p; and.b32 %0, %1, 1; setp.ne.u32 p, %0, 0; vote.sync.ballot.b32 %0, p, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 31: asm volatile("{ .reg .pred p; and.b32 %0, %1, 3; setp.ne.u32 p, %0, 0; vote.sync.ballot.b32 %0, !p, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 32: asm volatile("{ .reg .u32 x; and.b32 x, %1, 3; match.any.sync.b32 %0, x, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 33: asm volatile("{ .reg .u32 x; .reg .pred p; and.b32 x, %1, 1; match.all.sync.b32 %0|p, x, 0xffffffff; @p add.u32 %0, %0, 7; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 34: asm volatile("{ .reg .b64 x; mov.b64 x, {%1, %2}; and.b64 x, x, 0x0000000100000001; match.any.sync.b64 %0, x, 0xffffffff; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 35: asm volatile("redux.sync.add.u32 %0, %1, 0xffffffff;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 36: asm volatile("redux.sync.add.s32 %0, %1, 0xffffffff;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 37: asm volatile("redux.sync.min.u32 %0, %1, 0xffffffff;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 38: asm volatile("redux.sync.min.s32 %0, %1, 0xffffffff;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 39: asm volatile("redux.sync.max.u32 %0, %1, 0xffffffff;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 40: asm volatile("redux.sync.max.s32 %0, %1, 0xffffffff;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 41: asm volatile("redux.sync.and.b32 %0, %1, 0xffffffff;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 42: asm volatile("redux.sync.or.b32 %0, %1, 0xffffffff;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 43: asm volatile("redux.sync.xor.b32 %0, %1, 0xffffffff;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 44: asm volatile("mov.u32 %0, %laneid;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 45: asm volatile("mov.u32 %0, %lanemask_eq;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 46: asm volatile("mov.u32 %0, %lanemask_lt;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 47: asm volatile("mov.u32 %0, %lanemask_le;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 48: asm volatile("mov.u32 %0, %lanemask_gt;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 49: asm volatile("mov.u32 %0, %lanemask_ge;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 50: asm volatile("activemask.b32 %0;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 51: asm volatile("{ .reg .pred p; and.b32 %0, %1, 1; setp.ne.u32 p, %0, 0; bar.red.popc.u32 %0, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 52: asm volatile("{ .reg .pred p, q; setp.ne.u32 p, %1, 0; bar.red.and.pred q, 0, p; selp.u32 %0, 1, 0, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 53: asm volatile("{ .reg .pred p, q; and.b32 %0, %1, 0x100; setp.ne.u32 p, %0, 0; bar.red.or.pred q, 0, p; selp.u32 %0, 1, 0, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 54: asm volatile("atom.global.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 55: asm volatile("red.global.add.u32 [%4], %1; mov.u32 %0, 0;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 56: asm volatile("atom.global.add.s32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 57: asm volatile("red.global.add.s32 [%4], %1; mov.u32 %0, 0;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 58: asm volatile("atom.global.min.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 59: asm volatile("red.global.min.u32 [%4], %1; mov.u32 %0, 0;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 60: asm volatile("atom.global.min.s32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 61: asm volatile("red.global.min.s32 [%4], %1; mov.u32 %0, 0;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 62: asm volatile("atom.global.max.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 63: asm volatile("red.global.max.u32 [%4], %1; mov.u32 %0, 0;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 64: asm volatile("atom.global.max.s32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 65: asm volatile("red.global.max.s32 [%4], %1; mov.u32 %0, 0;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 66: asm volatile("atom.global.inc.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 67: asm volatile("red.global.inc.u32 [%4], %1; mov.u32 %0, 0;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 68: asm volatile("atom.global.dec.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 69: asm volatile("red.global.dec.u32 [%4], %1; mov.u32 %0, 0;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 70: asm volatile("atom.global.and.b32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 71: asm volatile("red.global.and.b32 [%4], %1; mov.u32 %0, 0;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 72: asm volatile("atom.global.or.b32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 73: asm volatile("red.global.or.b32 [%4], %1; mov.u32 %0, 0;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 74: asm volatile("atom.global.xor.b32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 75: asm volatile("red.global.xor.b32 [%4], %1; mov.u32 %0, 0;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 76: asm volatile("atom.global.exch.b32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 77: asm volatile("atom.global.cas.b32 %0, [%4], %2, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 78: asm volatile("{ .reg .u32 o; ld.global.u32 o, [%4]; atom.global.cas.b32 %0, [%4], o, %1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 79: asm volatile("{ .reg .f32 x, o; mov.b32 x, %1; atom.global.add.f32 o, [%4], x; mov.b32 %0, o; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 80: asm volatile("atom.global.add.noftz.f16x2 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 81: asm volatile("{ .reg .b16 x, o; mov.b32 {x, _}, %1; atom.global.add.noftz.f16 o, [%4], x; mov.b32 %0, {o, o}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 82: asm volatile("{ .reg .u64 x, o; mov.b64 x, {%1, %2}; atom.global.add.u64 o, [%4], x; mov.b64 {%0, _}, o; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 83: asm volatile("{ .reg .b64 x, o; mov.b64 x, {%1, %2}; atom.global.exch.b64 o, [%4], x; mov.b64 {_, %0}, o; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 84: asm volatile("{ .reg .s64 x, o; mov.b64 x, {%1, %2}; atom.global.max.s64 o, [%4], x; mov.b64 {%0, _}, o; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 85: asm volatile("{ .reg .f64 x, o; mov.b64 x, {%1, %2}; atom.global.add.f64 o, [%4], x; mov.b64 {_, %0}, o; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 86: asm volatile("{ .reg .u32 o; atom.shared.add.u32 o, [%5], %1; bar.sync 0; ld.shared.u32 %0, [%5]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 87: asm volatile("{ .reg .u32 o; atom.shared.min.u32 o, [%5], %1; bar.sync 0; ld.shared.u32 %0, [%5]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 88: asm volatile("{ .reg .u32 o; atom.shared.max.s32 o, [%5], %1; bar.sync 0; ld.shared.u32 %0, [%5]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 89: asm volatile("{ .reg .u32 o; atom.shared.and.b32 o, [%5], %1; bar.sync 0; ld.shared.u32 %0, [%5]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 90: asm volatile("{ .reg .u32 o; atom.shared.or.b32 o, [%5], %1; bar.sync 0; ld.shared.u32 %0, [%5]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 91: asm volatile("{ .reg .u32 o; atom.shared.xor.b32 o, [%5], %1; bar.sync 0; ld.shared.u32 %0, [%5]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 92: asm volatile("{ .reg .u32 o; atom.shared.inc.u32 o, [%5], 1000; bar.sync 0; ld.shared.u32 %0, [%5]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 93: asm volatile("{ .reg .f32 x, o; .reg .u32 ad; mov.b32 x, %1; shl.b32 ad, %6, 2; add.u32 ad, ad, %5; atom.shared.add.f32 o, [ad], x; mov.b32 %0, o; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 94: asm volatile("{ .reg .s16 x; st.global.u32 [%4], %1; ld.global.s8 x, [%4+1]; cvt.s32.s16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 95: asm volatile("{ .reg .u16 x; st.global.u32 [%4], %1; ld.global.u8 x, [%4+3]; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 96: asm volatile("{ .reg .s16 x; st.global.u32 [%4], %1; ld.global.s16 x, [%4+2]; cvt.s32.s16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 97: asm volatile("{ st.global.u32 [%4], %1; ld.global.s8 %0, [%4+2]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 98: asm volatile("{ st.global.u32 [%4], %1; ld.global.u16 %0, [%4+2]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 99: asm volatile("{ st.global.b8 [%4+2], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 100: asm volatile("{ st.global.b16 [%4+2], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 101: asm volatile("{ .reg .b16 x, y; mov.b32 {x, y}, %1; st.global.v2.b16 [%4], {y, x}; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 102: asm volatile("{ .reg .u16 x, y; cvt.u16.u32 x, %1; cvt.u16.u32 y, %2; add.u16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 103: asm volatile("{ .reg .s16 x, y; cvt.s16.u32 x, %1; cvt.s16.u32 y, %2; add.s16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 104: asm volatile("{ .reg .u16 x, y; cvt.u16.u32 x, %1; cvt.u16.u32 y, %2; sub.u16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 105: asm volatile("{ .reg .s16 x, y; cvt.s16.u32 x, %1; cvt.s16.u32 y, %2; sub.s16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 106: asm volatile("{ .reg .u16 x, y; cvt.u16.u32 x, %1; cvt.u16.u32 y, %2; min.u16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 107: asm volatile("{ .reg .s16 x, y; cvt.s16.u32 x, %1; cvt.s16.u32 y, %2; min.s16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 108: asm volatile("{ .reg .u16 x, y; cvt.u16.u32 x, %1; cvt.u16.u32 y, %2; max.u16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 109: asm volatile("{ .reg .s16 x, y; cvt.s16.u32 x, %1; cvt.s16.u32 y, %2; max.s16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 110: asm volatile("{ .reg .u16 x, y; cvt.u16.u32 x, %1; cvt.u16.u32 y, %2; mul.lo.u16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 111: asm volatile("{ .reg .u16 x, y; cvt.u16.u32 x, %1; cvt.u16.u32 y, %2; mul.hi.u16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 112: asm volatile("{ .reg .u16 x, y; cvt.u16.u32 x, %1; cvt.u16.u32 y, %2; div.u16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 113: asm volatile("{ .reg .u16 x, y; cvt.u16.u32 x, %1; cvt.u16.u32 y, %2; rem.u16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 114: asm volatile("{ .reg .u16 x; cvt.u16.u32 x, %1; shr.u16 x, x, %2; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 115: asm volatile("{ .reg .u16 x, y, z; cvt.u16.u32 x, %1; cvt.u16.u32 y, %2; cvt.u16.u32 z, %3; mad.lo.u16 x, x, y, z; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 116: asm volatile("{ .reg .s16 x, y; cvt.s16.u32 x, %1; cvt.s16.u32 y, %2; mul.lo.s16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 117: asm volatile("{ .reg .s16 x, y; cvt.s16.u32 x, %1; cvt.s16.u32 y, %2; mul.hi.s16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 118: asm volatile("{ .reg .s16 x, y; cvt.s16.u32 x, %1; cvt.s16.u32 y, %2; div.s16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 119: asm volatile("{ .reg .s16 x, y; cvt.s16.u32 x, %1; cvt.s16.u32 y, %2; rem.s16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 120: asm volatile("{ .reg .s16 x; cvt.s16.u32 x, %1; shr.s16 x, x, %2; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 121: asm volatile("{ .reg .s16 x, y, z; cvt.s16.u32 x, %1; cvt.s16.u32 y, %2; cvt.s16.u32 z, %3; mad.lo.s16 x, x, y, z; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 122: asm volatile("{ .reg .b16 x; cvt.u16.u32 x, %1; shl.b16 x, x, %2; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 123: asm volatile("{ .reg .s16 x; cvt.s16.u32 x, %1; abs.s16 x, x; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 124: asm volatile("{ .reg .s16 x; cvt.s16.u32 x, %1; neg.s16 x, x; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 125: asm volatile("{ .reg .b16 x; cvt.u16.u32 x, %1; not.b16 x, x; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 126: asm volatile("cnot.b32 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 127: asm volatile("{ .reg .b16 x; cvt.u16.u32 x, %1; and.b16 x, x, 3; cnot.b16 x, x; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 128: asm volatile("{ .reg .b16 x, y; cvt.u16.u32 x, %1; cvt.u16.u32 y, %2; and.b16 x, x, y; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 129: asm volatile("{ .reg .s64 x, y; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; add.s64 x, x, y; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 130: asm volatile("{ .reg .s64 x, y; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; mul.lo.s64 x, x, y; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 131: asm volatile("{ .reg .s64 x, y; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; mad.lo.s64 x, x, y, y; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 132: asm volatile("{ .reg .s64 x, y; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; mad.hi.s64 x, x, y, y; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 133: asm volatile("{ .reg .s64 x; mov.b64 x, {%1, %2}; shr.s64 x, x, %3; mov.b64 {%0, _}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 134: asm volatile("{ .reg .s64 x; mov.b64 x, {%1, %2}; bfe.s64 x, x, %3, %1; mov.b64 {%0, _}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 135: asm volatile("{ .reg .s64 x, y; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; min.s64 x, x, y; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 136: asm volatile("{ .reg .u64 x, y; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; add.u64 x, x, y; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 137: asm volatile("{ .reg .u64 x, y; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; mul.lo.u64 x, x, y; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 138: asm volatile("{ .reg .u64 x, y; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; mad.lo.u64 x, x, y, y; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 139: asm volatile("{ .reg .u64 x, y; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; mad.hi.u64 x, x, y, y; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 140: asm volatile("{ .reg .u64 x; mov.b64 x, {%1, %2}; shr.u64 x, x, %3; mov.b64 {%0, _}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 141: asm volatile("{ .reg .u64 x; mov.b64 x, {%1, %2}; bfe.u64 x, x, %3, %1; mov.b64 {%0, _}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 142: asm volatile("{ .reg .u64 x, y; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; min.u64 x, x, y; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 143: asm volatile("{ .reg .b64 x, y; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; bfi.b64 x, x, y, %3, %2; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 144: asm volatile("{ .reg .u64 x, y; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; add.cc.u64 x, x, y; addc.u32 %0, %3, 0; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 145: asm volatile("{ .reg .u64 w; mul.wide.u32 w, %1, %2; mov.b64 {%0, _}, w; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 146: asm volatile("{ .reg .s64 x; mov.b64 x, {%1, %2}; abs.s64 x, x; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 147: asm volatile("{ .reg .s64 x; mov.b64 x, {%1, %2}; neg.s64 x, x; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 148: asm volatile("{ .reg .f64 x, y; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; copysign.f64 x, x, y; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 149: asm volatile("{ .reg .f64 x, y; .reg .pred p; mov.b64 x, {%1, %2}; mov.b64 y, {%3, %1}; setp.ne.u32 p, %3, 0; selp.f64 x, x, y, p; mov.b64 {_, %0}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 150: asm volatile("{ .reg .f32 x, y, z; mov.b32 x, %1; mov.b32 y, %2; mov.b32 z, %3; slct.f32.f32 x, x, y, z; mov.b32 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 151: asm volatile("{ .reg .b16 x, y; mov.b32 {x, y}, %1; mov.b32 %0, {y, x}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 152: asm volatile("{ .reg .b64 w; .reg .b32 x, y; mov.b64 w, {%1, %2}; mov.b64 {x, y}, w; add.u32 %0, x, y; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
  }
  out[2 * i] = d;
  out[2 * i + 1] = (unsigned)g[i] ^ (unsigned)(g[i] >> 32);
}
static const char* kTags[] = {
  "shfl.up c=0x1f",
  "shfl.up c=0x1c1f",
  "shfl.up c=0x0",
  "shfl.up c=0x101f",
  "shfl.up p",
  "shfl.up imm",
  "shfl.down c=0x1f",
  "shfl.down c=0x1c1f",
  "shfl.down c=0x0",
  "shfl.down c=0x101f",
  "shfl.down p",
  "shfl.down imm",
  "shfl.bfly c=0x1f",
  "shfl.bfly c=0x1c1f",
  "shfl.bfly c=0x0",
  "shfl.bfly c=0x101f",
  "shfl.bfly p",
  "shfl.bfly imm",
  "shfl.idx c=0x1f",
  "shfl.idx c=0x1c1f",
  "shfl.idx c=0x0",
  "shfl.idx c=0x101f",
  "shfl.idx p",
  "shfl.idx imm",
  "vote.all",
  "vote.all mostly",
  "vote.any",
  "vote.any mostly",
  "vote.uni",
  "vote.uni mostly",
  "vote.ballot",
  "vote.ballot !p",
  "match.any",
  "match.all",
  "match.any.b64",
  "redux.add.u32",
  "redux.add.s32",
  "redux.min.u32",
  "redux.min.s32",
  "redux.max.u32",
  "redux.max.s32",
  "redux.and.b32",
  "redux.or.b32",
  "redux.xor.b32",
  "%laneid",
  "%lanemask_eq",
  "%lanemask_lt",
  "%lanemask_le",
  "%lanemask_gt",
  "%lanemask_ge",
  "activemask",
  "bar.red.popc",
  "bar.red.and",
  "bar.red.or",
  "atom.global.add.u32",
  "red.global.add.u32",
  "atom.global.add.s32",
  "red.global.add.s32",
  "atom.global.min.u32",
  "red.global.min.u32",
  "atom.global.min.s32",
  "red.global.min.s32",
  "atom.global.max.u32",
  "red.global.max.u32",
  "atom.global.max.s32",
  "red.global.max.s32",
  "atom.global.inc.u32",
  "red.global.inc.u32",
  "atom.global.dec.u32",
  "red.global.dec.u32",
  "atom.global.and.b32",
  "red.global.and.b32",
  "atom.global.or.b32",
  "red.global.or.b32",
  "atom.global.xor.b32",
  "red.global.xor.b32",
  "atom.global.exch.b32",
  "atom.global.cas.b32",
  "atom.global.cas.b32 hit",
  "atom.global.add.f32",
  "atom.global.add.noftz.f16x2",
  "atom.global.add.noftz.f16",
  "atom.global.add.u64 lo",
  "atom.global.exch.b64 hi",
  "atom.global.max.s64 lo",
  "atom.global.add.f64 hi",
  "atom.shared.add.u32 contended",
  "atom.shared.min.u32 contended",
  "atom.shared.max.s32 contended",
  "atom.shared.and.b32 contended",
  "atom.shared.or.b32 contended",
  "atom.shared.xor.b32 contended",
  "atom.shared.inc.u32 contended",
  "atom.shared.add.f32 lane",
  "ld.global.s8",
  "ld.global.u8",
  "ld.global.s16",
  "ld.global.s8 into s32",
  "ld.global.u16 into u32",
  "st.global.b8",
  "st.global.b16",
  "st.global.v2.b16",
  "add.u16",
  "add.s16",
  "sub.u16",
  "sub.s16",
  "min.u16",
  "min.s16",
  "max.u16",
  "max.s16",
  "mul.lo.u16",
  "mul.hi.u16",
  "div.u16",
  "rem.u16",
  "shr.u16",
  "mad.lo.u16",
  "mul.lo.s16",
  "mul.hi.s16",
  "div.s16",
  "rem.s16",
  "shr.s16",
  "mad.lo.s16",
  "shl.b16",
  "abs.s16",
  "neg.s16",
  "not.b16",
  "cnot.b32",
  "cnot.b16",
  "and.b16",
  "add.s64 hi",
  "mul.lo.s64 hi",
  "mad.lo.s64 hi",
  "mad.hi.s64 hi",
  "shr.s64 lo",
  "bfe.s64 lo",
  "min.s64 hi",
  "add.u64 hi",
  "mul.lo.u64 hi",
  "mad.lo.u64 hi",
  "mad.hi.u64 hi",
  "shr.u64 lo",
  "bfe.u64 lo",
  "min.u64 hi",
  "bfi.b64 hi",
  "add.cc.u64/addc hi",
  "mul.wide.u32 lo",
  "abs.s64 hi",
  "neg.s64 hi",
  "copysign.f64 hi",
  "selp.f64 hi",
  "slct.f32.f32",
  "mov.b32 unpack/pack b16",
  "mov.b64 unpack/pack b32",
};
int main(int argc, char** argv) {
  const bool print = argc > 1 && std::strcmp(argv[1], "--print") == 0;
  const int dump = argc > 2 && std::strcmp(argv[1], "--dump") == 0 ? atoi(argv[2]) : -1;
  const int nv = sizeof kTags / sizeof kTags[0];
  static const unsigned edge[] = {
      0x00000000u, 0x80000000u, 0x3f800000u, 0xbf800000u, 0x7fc00000u, 0xff800001u, 0x00000001u, 0x007fffffu,
      0x7f7fffffu, 0x3f7fffffu, 0x3f800001u, 0x3f801000u, 0x3dcccccdu, 0x40000000u, 0xc0400000u, 0x7f800000u,
      0x3c00bc00u, 0x7e003c00u, 0x00010002u, 0x7bff7c00u, 0x3bff3c01u, 0x80000000u, 0x3f80bf80u, 0x7fc0ff80u,
      0x12345678u, 0x9abcdef0u, 0x007fffffu, 0x7fffffffu, 0x00800000u, 0xffffffffu, 0x0f1e2d3cu, 0x00000003u};
  unsigned h[3 * kN];
  unsigned long long s = 0x9E3779B97F4A7C15ull;
  for (int i = 0; i < 3 * kN; ++i) {
    s ^= s << 13; s ^= s >> 7; s ^= s << 17;
    h[i] = static_cast<unsigned>(s);
    if ((s >> 40) % 3 == 0) h[i] = edge[(s >> 48) % 32];
  }
  unsigned *din, *dout;
  unsigned long long* dg;
  cudaMalloc(&din, sizeof h);
  cudaMalloc(&dout, 2 * kN * 4);
  cudaMalloc(&dg, kN * 8);
  cudaMemcpy(din, h, sizeof h, cudaMemcpyHostToDevice);
  int bad = 0;
  for (int v = 0; v < nv; ++v) {
    k<<<1, kN>>>(v, din, dout, dg);
    if (cudaDeviceSynchronize() != cudaSuccess) { printf("variant %d (%s) failed to run\n", v, kTags[v]); return 1; }
    unsigned o[2 * kN];
    cudaMemcpy(o, dout, sizeof o, cudaMemcpyDeviceToHost);
    unsigned long long hash = 1469598103934665603ull;
    for (unsigned x : o) { hash ^= x; hash *= 1099511628211ull; }
    if (v == dump) {
      for (int i = 0; i < kN; ++i)
        printf("%3d a=%08x b=%08x c=%08x d=%08x m=%08x\n", i, h[3 * i], h[3 * i + 1], h[3 * i + 2], o[2 * i], o[2 * i + 1]);
      return 0;
    }
    if (print) { printf("    {\"%s\", 0x%016llxull},\n", kTags[v], hash); continue; }
    if (dump >= 0) continue;
    const int ne = sizeof kExpected / sizeof kExpected[0];
    if (v >= ne || hash != kExpected[v].hash)
      if (bad++ < 40) printf("%s: 0x%016llx, the card gave 0x%016llx\n", kTags[v], hash, v < ne ? kExpected[v].hash : 0ull);
  }
  if (print) return 0;
  const int ne = sizeof kExpected / sizeof kExpected[0];
  printf("%d warp, atomic and memory forms, %d differ\n%s\n", nv, bad, bad || ne != nv ? "FAIL" : "PASS");
  return bad ? 1 : 0;
}
