// The everyday PTX instructions -- integer, bit, float with every rounding
// mode, conversions, comparisons, half precision -- each variant over the
// same 256 operand triples, its results hashed
// and compared with the card's (sm_86), recorded in ptx_sweep_expected.inc
// (`ptx_sweep --print` prints them; `--dump N` prints variant N's values).
// Generated by ptx_sweep_gen.py. Prints PASS on the last line, and runs the
// same on a GPU.
#include <cstdio>
#include <cstdlib>
#include <cstring>
struct Expected { const char* tag; unsigned long long hash; };
static const Expected kExpected[] = {
#include "ptx_sweep_expected.inc"
};
constexpr int kN = 256;
__global__ void k(int v, const unsigned* in, unsigned* out) {
  const int i = threadIdx.x;
  const unsigned a = in[3 * i], b = in[3 * i + 1], c = in[3 * i + 2];
  unsigned d = 0;
  switch (v) {
    case 0: asm volatile("div.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 1: asm volatile("rem.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 2: asm volatile("min.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 3: asm volatile("max.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 4: asm volatile("mul.hi.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 5: asm volatile("mad.hi.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 6: asm volatile("mad.lo.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 7: asm volatile("shr.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 8: asm volatile("bfe.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 9: asm volatile("bfind.u32 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 10: asm volatile("bfind.shiftamt.u32 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 11: asm volatile("dp2a.lo.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 12: asm volatile("dp2a.hi.u32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 13: asm volatile("dp4a.u32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 14: asm volatile("dp4a.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 15: asm volatile("sad.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 16: asm volatile("div.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 17: asm volatile("rem.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 18: asm volatile("min.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 19: asm volatile("max.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 20: asm volatile("mul.hi.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 21: asm volatile("mad.hi.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 22: asm volatile("mad.lo.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 23: asm volatile("shr.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 24: asm volatile("bfe.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 25: asm volatile("bfind.s32 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 26: asm volatile("bfind.shiftamt.s32 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 27: asm volatile("dp2a.lo.s32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 28: asm volatile("dp2a.hi.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 29: asm volatile("dp4a.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 30: asm volatile("dp4a.s32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 31: asm volatile("sad.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 32: asm volatile("shl.b32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 33: asm volatile("abs.s32 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 34: asm volatile("neg.s32 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 35: asm volatile("bfi.b32 %0, %1, %2, %3, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 36: asm volatile("brev.b32 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 37: asm volatile("popc.b32 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 38: asm volatile("clz.b32 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 39: asm volatile("fns.b32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 40: asm volatile("bmsk.clamp.b32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 41: asm volatile("bmsk.wrap.b32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 42: asm volatile("shf.l.wrap.b32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 43: asm volatile("shf.l.clamp.b32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 44: asm volatile("shf.r.wrap.b32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 45: asm volatile("shf.r.clamp.b32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 46: asm volatile("prmt.b32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 47: asm volatile("lop3.b32 %0, %1, %2, %3, 0x96;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 48: asm volatile("lop3.b32 %0, %1, %2, %3, 0xe8;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 49: asm volatile("{ add.cc.u32 %0, %1, %2; addc.cc.u32 %0, %0, %3; addc.u32 %0, %0, 0; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 50: asm volatile("{ sub.cc.u32 %0, %1, %2; subc.cc.u32 %0, %0, %3; subc.u32 %0, %0, 0; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 51: asm volatile("{ .reg .u32 t; mad.lo.cc.u32 t, %1, %2, %3; madc.hi.u32 %0, %1, %2, t; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 52: asm volatile("{ .reg .s16 x,y; cvt.s16.u32 x, %1; cvt.s16.u32 y, %2; mul.wide.s16 %0, x, y; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 53: asm volatile("{ .reg .u16 x,y; cvt.u16.u32 x, %1; cvt.u16.u32 y, %2; mul.wide.u16 %0, x, y; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 54: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; div.s64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 55: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; div.s64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 56: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; rem.s64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 57: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; rem.s64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 58: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; div.u64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 59: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; div.u64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 60: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; rem.u64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 61: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; rem.u64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 62: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; mul.hi.s64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 63: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; mul.hi.s64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 64: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; mul.hi.u64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 65: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; mul.hi.u64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 66: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; min.s64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 67: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; min.s64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 68: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; max.u64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 69: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; max.u64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 70: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; shr.s64 a, a, %3; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 71: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; shl.b64 a, a, %3; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 72: asm volatile("{ .reg .b64 a; mov.b64 a, {%1, %2}; popc.b64 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 73: asm volatile("{ .reg .b64 a; mov.b64 a, {%1, %2}; clz.b64 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 74: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; brev.b64 a, a; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 75: asm volatile("{ .reg .b64 a; mov.b64 a, {%1, %2}; bfind.s64 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 76: asm volatile("{ .reg .s64 w; mul.wide.s32 w, %1, %2; mov.b64 {_, %0}, w; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 77: asm volatile("{ .reg .u64 w, c; mov.b64 c, {%3, %1}; mad.wide.u32 w, %1, %2, c; mov.b64 {_, %0}, w; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 78: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; add.rn.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 79: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; sub.rn.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 80: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mul.rn.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 81: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; div.rn.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 82: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; sqrt.rn.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 83: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; rcp.rn.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 84: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; div.rn.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 85: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; add.rn.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 86: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mul.rn.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 87: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; add.rn.f64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 88: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; add.rn.f64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 89: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; mul.rn.f64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 90: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; mul.rn.f64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 91: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; div.rn.f64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 92: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; div.rn.f64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 93: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rn.f64 a, a, b, c; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 94: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rn.f64 a, a, b, c; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 95: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; sqrt.rn.f64 a, a; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 96: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; rcp.rn.f64 a, a; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 97: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; add.rz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 98: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; sub.rz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 99: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mul.rz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 100: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; div.rz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 101: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; sqrt.rz.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 102: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; rcp.rz.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 103: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; div.rz.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 104: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; add.rz.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 105: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mul.rz.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 106: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; add.rz.f64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 107: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; add.rz.f64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 108: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; mul.rz.f64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 109: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; mul.rz.f64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 110: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; div.rz.f64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 111: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; div.rz.f64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 112: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rz.f64 a, a, b, c; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 113: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rz.f64 a, a, b, c; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 114: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; sqrt.rz.f64 a, a; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 115: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; rcp.rz.f64 a, a; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 116: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; add.rm.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 117: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; sub.rm.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 118: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mul.rm.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 119: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; div.rm.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 120: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; sqrt.rm.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 121: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; rcp.rm.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 122: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; div.rm.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 123: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; add.rm.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 124: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mul.rm.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 125: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; add.rm.f64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 126: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; add.rm.f64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 127: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; mul.rm.f64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 128: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; mul.rm.f64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 129: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; div.rm.f64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 130: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; div.rm.f64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 131: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rm.f64 a, a, b, c; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 132: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rm.f64 a, a, b, c; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 133: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; sqrt.rm.f64 a, a; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 134: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; rcp.rm.f64 a, a; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 135: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; add.rp.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 136: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; sub.rp.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 137: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mul.rp.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 138: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; div.rp.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 139: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; sqrt.rp.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 140: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; rcp.rp.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 141: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; div.rp.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 142: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; add.rp.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 143: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mul.rp.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 144: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; add.rp.f64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 145: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; add.rp.f64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 146: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; mul.rp.f64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 147: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; mul.rp.f64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 148: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; div.rp.f64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 149: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; div.rp.f64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 150: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rp.f64 a, a, b, c; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 151: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rp.f64 a, a, b, c; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 152: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; sqrt.rp.f64 a, a; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 153: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; rcp.rp.f64 a, a; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 154: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; min.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 155: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; max.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 156: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; min.f64 a, a, b; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 157: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; max.f64 a, a, b; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 158: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; abs.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 159: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; neg.ftz.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 160: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; abs.ftz.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 161: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; copysign.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 162: asm volatile("{ .reg .f32 a,b,c; .reg .pred p; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; testp.finite.f32 p, a; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 163: asm volatile("{ .reg .f32 a,b,c; .reg .pred p; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; testp.infinite.f32 p, a; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 164: asm volatile("{ .reg .f32 a,b,c; .reg .pred p; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; testp.number.f32 p, a; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 165: asm volatile("{ .reg .f32 a,b,c; .reg .pred p; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; testp.notanumber.f32 p, a; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 166: asm volatile("{ .reg .f32 a,b,c; .reg .pred p; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; testp.normal.f32 p, a; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 167: asm volatile("{ .reg .f32 a,b,c; .reg .pred p; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; testp.subnormal.f32 p, a; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 168: asm volatile("{ .reg .pred p; setp.eq.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 169: asm volatile("{ .reg .pred p; setp.ne.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 170: asm volatile("{ .reg .pred p; setp.lt.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 171: asm volatile("{ .reg .pred p; setp.le.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 172: asm volatile("{ .reg .pred p; setp.gt.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 173: asm volatile("{ .reg .pred p; setp.ge.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 174: asm volatile("{ .reg .pred p; setp.lo.u32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 175: asm volatile("{ .reg .pred p; setp.ls.u32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 176: asm volatile("{ .reg .pred p; setp.hi.u32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 177: asm volatile("{ .reg .pred p; setp.hs.u32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 178: asm volatile("{ .reg .pred p; setp.equ.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 179: asm volatile("{ .reg .pred p; setp.neu.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 180: asm volatile("{ .reg .pred p; setp.ltu.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 181: asm volatile("{ .reg .pred p; setp.leu.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 182: asm volatile("{ .reg .pred p; setp.gtu.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 183: asm volatile("{ .reg .pred p; setp.geu.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 184: asm volatile("{ .reg .pred p; setp.num.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 185: asm volatile("{ .reg .pred p; setp.nan.f32 p, %1, %2; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 186: asm volatile("{ .reg .f32 a,b,d; mov.b32 a, %1; mov.b32 b, %2; set.lt.f32.f32 d, a, b; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 187: asm volatile("set.gtu.u32.f32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 188: asm volatile("{ .reg .pred p; setp.ne.u32 p, %3, 0; selp.b32 %0, %1, %2, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 189: asm volatile("slct.s32.f32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 190: asm volatile("slct.u32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 191: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rni.s32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 192: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rni.sat.s32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 193: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rzi.s32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 194: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rzi.sat.s32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 195: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rmi.s32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 196: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rmi.sat.s32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 197: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rpi.s32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 198: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rpi.sat.s32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 199: asm volatile("{ .reg .f64 a; .reg .b64 d; mov.b64 a, {%1, %2}; cvt.rzi.s32.f64 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 200: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rni.u32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 201: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rni.sat.u32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 202: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rzi.u32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 203: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rzi.sat.u32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 204: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rmi.u32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 205: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rmi.sat.u32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 206: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rpi.u32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 207: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rpi.sat.u32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 208: asm volatile("{ .reg .f64 a; .reg .b64 d; mov.b64 a, {%1, %2}; cvt.rzi.u32.f64 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 209: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rni.s16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 210: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rni.sat.s16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 211: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rzi.s16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 212: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rzi.sat.s16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 213: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rmi.s16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 214: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rmi.sat.s16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 215: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rpi.s16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 216: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rpi.sat.s16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 217: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rni.u16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 218: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rni.sat.u16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 219: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rzi.u16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 220: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rzi.sat.u16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 221: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rmi.u16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 222: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rmi.sat.u16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 223: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rpi.u16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 224: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rpi.sat.u16.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 225: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rni.s8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 226: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rni.sat.s8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 227: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rzi.s8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 228: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rzi.sat.s8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 229: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rmi.s8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 230: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rmi.sat.s8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 231: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rpi.s8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 232: asm volatile("{ .reg .f32 a; .reg .s16 d; mov.b32 a, %1; cvt.rpi.sat.s8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 233: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rni.u8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 234: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rni.sat.u8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 235: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rzi.u8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 236: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rzi.sat.u8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 237: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rmi.u8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 238: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rmi.sat.u8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 239: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rpi.u8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 240: asm volatile("{ .reg .f32 a; .reg .u16 d; mov.b32 a, %1; cvt.rpi.sat.u8.f32 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 241: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rni.s64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 242: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rni.s64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 243: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rni.sat.s64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 244: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rni.sat.s64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 245: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rzi.s64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 246: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rzi.s64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 247: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rzi.sat.s64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 248: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rzi.sat.s64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 249: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rmi.s64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 250: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rmi.s64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 251: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rmi.sat.s64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 252: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rmi.sat.s64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 253: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rpi.s64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 254: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rpi.s64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 255: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rpi.sat.s64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 256: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rpi.sat.s64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 257: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rni.u64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 258: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rni.u64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 259: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rni.sat.u64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 260: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rni.sat.u64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 261: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rzi.u64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 262: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rzi.u64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 263: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rzi.sat.u64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 264: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rzi.sat.u64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 265: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rmi.u64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 266: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rmi.u64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 267: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rmi.sat.u64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 268: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rmi.sat.u64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 269: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rpi.u64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 270: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rpi.u64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 271: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rpi.sat.u64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 272: asm volatile("{ .reg .f32 a; .reg .b64 d; mov.b32 a, %1; cvt.rpi.sat.u64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 273: asm volatile("{ .reg .f32 d; cvt.rn.f32.s32 d, %1; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 274: asm volatile("{ .reg .f32 d; cvt.rz.f32.s32 d, %1; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 275: asm volatile("{ .reg .f32 d; cvt.rm.f32.s32 d, %1; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 276: asm volatile("{ .reg .f32 d; cvt.rp.f32.s32 d, %1; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 277: asm volatile("{ .reg .f32 d; cvt.rn.f32.u32 d, %1; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 278: asm volatile("{ .reg .f32 d; cvt.rz.f32.u32 d, %1; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 279: asm volatile("{ .reg .f32 d; cvt.rm.f32.u32 d, %1; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 280: asm volatile("{ .reg .f32 d; cvt.rp.f32.u32 d, %1; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 281: asm volatile("{ .reg .f32 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rn.f32.s64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 282: asm volatile("{ .reg .f64 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rn.f64.s64 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 283: asm volatile("{ .reg .f32 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rz.f32.s64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 284: asm volatile("{ .reg .f64 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rz.f64.s64 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 285: asm volatile("{ .reg .f32 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rm.f32.s64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 286: asm volatile("{ .reg .f64 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rm.f64.s64 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 287: asm volatile("{ .reg .f32 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rp.f32.s64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 288: asm volatile("{ .reg .f64 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rp.f64.s64 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 289: asm volatile("{ .reg .f32 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rn.f32.u64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 290: asm volatile("{ .reg .f64 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rn.f64.u64 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 291: asm volatile("{ .reg .f32 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rz.f32.u64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 292: asm volatile("{ .reg .f64 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rz.f64.u64 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 293: asm volatile("{ .reg .f32 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rm.f32.u64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 294: asm volatile("{ .reg .f64 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rm.f64.u64 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 295: asm volatile("{ .reg .f32 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rp.f32.u64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 296: asm volatile("{ .reg .f64 d; .reg .b64 a; mov.b64 a, {%1, %2}; cvt.rp.f64.u64 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 297: asm volatile("{ .reg .f64 a; .reg .f32 d; mov.b64 a, {%1, %2}; cvt.rn.f32.f64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 298: asm volatile("{ .reg .f64 a; .reg .f32 d; mov.b64 a, {%1, %2}; cvt.rn.ftz.f32.f64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 299: asm volatile("{ .reg .f32 a; .reg .b16 h; mov.b32 a, %1; cvt.rn.f16.f32 h, a; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 300: asm volatile("{ .reg .f64 a; .reg .b16 h; mov.b64 a, {%1, %2}; cvt.rn.f16.f64 h, a; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 301: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; cvt.rni.f32.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 302: asm volatile("{ .reg .b16 h; cvt.rn.f16.s32 h, %1; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 303: asm volatile("{ .reg .f64 a; .reg .f32 d; mov.b64 a, {%1, %2}; cvt.rz.f32.f64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 304: asm volatile("{ .reg .f64 a; .reg .f32 d; mov.b64 a, {%1, %2}; cvt.rz.ftz.f32.f64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 305: asm volatile("{ .reg .f32 a; .reg .b16 h; mov.b32 a, %1; cvt.rz.f16.f32 h, a; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 306: asm volatile("{ .reg .f64 a; .reg .b16 h; mov.b64 a, {%1, %2}; cvt.rz.f16.f64 h, a; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 307: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; cvt.rzi.f32.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 308: asm volatile("{ .reg .b16 h; cvt.rz.f16.s32 h, %1; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 309: asm volatile("{ .reg .f64 a; .reg .f32 d; mov.b64 a, {%1, %2}; cvt.rm.f32.f64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 310: asm volatile("{ .reg .f64 a; .reg .f32 d; mov.b64 a, {%1, %2}; cvt.rm.ftz.f32.f64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 311: asm volatile("{ .reg .f32 a; .reg .b16 h; mov.b32 a, %1; cvt.rm.f16.f32 h, a; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 312: asm volatile("{ .reg .f64 a; .reg .b16 h; mov.b64 a, {%1, %2}; cvt.rm.f16.f64 h, a; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 313: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; cvt.rmi.f32.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 314: asm volatile("{ .reg .b16 h; cvt.rm.f16.s32 h, %1; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 315: asm volatile("{ .reg .f64 a; .reg .f32 d; mov.b64 a, {%1, %2}; cvt.rp.f32.f64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 316: asm volatile("{ .reg .f64 a; .reg .f32 d; mov.b64 a, {%1, %2}; cvt.rp.ftz.f32.f64 d, a; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 317: asm volatile("{ .reg .f32 a; .reg .b16 h; mov.b32 a, %1; cvt.rp.f16.f32 h, a; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 318: asm volatile("{ .reg .f64 a; .reg .b16 h; mov.b64 a, {%1, %2}; cvt.rp.f16.f64 h, a; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 319: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; cvt.rpi.f32.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 320: asm volatile("{ .reg .b16 h; cvt.rp.f16.s32 h, %1; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 321: asm volatile("{ .reg .b16 h; .reg .f32 d; mov.b32 {h, _}, %1; cvt.f32.f16 d, h; mov.b32 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 322: asm volatile("{ .reg .f32 a; .reg .f64 d; mov.b32 a, %1; cvt.f64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 323: asm volatile("{ .reg .f32 a; .reg .f64 d; mov.b32 a, %1; cvt.ftz.f64.f32 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 324: asm volatile("{ .reg .b16 h; mov.b32 {h, _}, %1; cvt.rzi.s32.f16 %0, h; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 325: asm volatile("{ .reg .f32 a; .reg .b16 h; mov.b32 a, %1; cvt.rn.bf16.f32 h, a; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 326: asm volatile("{ .reg .f32 a,b; mov.b32 a, %1; mov.b32 b, %2; cvt.rn.bf16x2.f32 %0, a, b; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 327: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; cvt.sat.f32.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 328: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; cvt.ftz.f32.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 329: asm volatile("{ .reg .s16 d; cvt.sat.s8.s32 d, %1; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 330: asm volatile("{ .reg .u16 d; cvt.sat.u8.u32 d, %1; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 331: asm volatile("{ .reg .s16 d; cvt.sat.s16.u32 d, %1; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 332: asm volatile("{ .reg .u16 d; cvt.sat.u16.s32 d, %1; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 333: asm volatile("{ .reg .s16 d; cvt.sat.s8.u32 d, %1; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 334: asm volatile("{ .reg .s8 x; .reg .u16 d; cvt.s8.u32 x, %1; cvt.sat.u8.s8 d, x; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 335: asm volatile("cvt.pack.sat.s16.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 336: asm volatile("cvt.pack.sat.u8.s32.b32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 337: asm volatile("add.rn.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 338: asm volatile("sub.rn.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 339: asm volatile("mul.rn.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 340: asm volatile("fma.rn.f16x2 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 341: asm volatile("fma.rn.bf16x2 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 342: asm volatile("min.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 343: asm volatile("min.bf16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 344: asm volatile("max.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 345: asm volatile("max.bf16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 346: asm volatile("neg.f16x2 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 347: asm volatile("abs.f16x2 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 348: asm volatile("neg.bf16x2 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 349: asm volatile("{ .reg .pred p, q; setp.lt.f16x2 p|q, %1, %2; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 350: asm volatile("set.lt.u32.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 351: asm volatile("{ .reg .f64 a; .reg .b64 d; mov.b64 a, {%1, %2}; cvt.rzi.s64.f64 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 352: asm volatile("{ .reg .f64 a; .reg .b64 d; mov.b64 a, {%1, %2}; cvt.rzi.s64.f64 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 353: asm volatile("{ .reg .f64 a; .reg .b64 d; mov.b64 a, {%1, %2}; cvt.rzi.u64.f64 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 354: asm volatile("{ .reg .f64 a; .reg .b64 d; mov.b64 a, {%1, %2}; cvt.rzi.u64.f64 d, a; mov.b64 {_, %0}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 355: asm volatile("{ .reg .f64 a; .reg .s16 d; mov.b64 a, {%1, %2}; cvt.rzi.s16.f64 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 356: asm volatile("{ .reg .f64 a; .reg .u16 d; mov.b64 a, {%1, %2}; cvt.rzi.u16.f64 d, a; cvt.u32.u16 %0, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 357: asm volatile("{ .reg .b16 h; mov.b32 {h, _}, %1; cvt.rzi.u32.f16 %0, h; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 358: asm volatile("{ .reg .f32 a; .reg .f64 d; mov.b32 a, %1; cvt.ftz.f64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 359: asm volatile("{ .reg .f32 a; .reg .f64 d; mov.b32 a, %1; cvt.f64.f32 d, a; mov.b64 {%0, _}, d; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 360: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; neg.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 361: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; abs.f64 a, a; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 362: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; neg.f64 a, a; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 363: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; abs.f64 a, a; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 364: asm volatile("{ .reg .b16 h; mov.b32 {h, _}, %1; neg.f16 h, h; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 365: asm volatile("{ .reg .b16 h; mov.b32 {h, _}, %1; abs.bf16 h, h; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 366: asm volatile("{ .reg .f64 a; .reg .pred p; mov.b64 a, {0, %2}; and.b64 a, a, 0x8000000000000000; testp.normal.f64 p, a; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 367: asm volatile("{ .reg .f64 a; .reg .pred p; mov.b64 a, {%1, %2}; testp.normal.f64 p, a; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 368: asm volatile("{ .reg .f64 a; .reg .pred p; mov.b64 a, {%1, %2}; testp.subnormal.f64 p, a; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 369: asm volatile("{ .reg .f64 a; .reg .pred p; mov.b64 a, {%1, %2}; testp.notanumber.f64 p, a; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 370: asm volatile("{ .reg .f64 a; .reg .pred p; mov.b64 a, {%1, %2}; testp.finite.f64 p, a; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 371: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; sqrt.rn.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 372: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; rcp.rn.ftz.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 373: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; sqrt.rn.ftz.f32 a, a; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 374: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; min.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 375: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; sub.rn.ftz.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 376: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; rem.u64 a, a, c; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 377: asm volatile("{ .reg .b64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; div.s64 a, a, c; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
  }
  out[i] = d;
}
static const char* kTags[] = {
  "div.u32",
  "rem.u32",
  "min.u32",
  "max.u32",
  "mul.hi.u32",
  "mad.hi.u32",
  "mad.lo.u32",
  "shr.u32",
  "bfe.u32",
  "bfind.u32",
  "bfind.shiftamt.u32",
  "dp2a.lo.u32.u32",
  "dp2a.hi.u32.s32",
  "dp4a.u32.s32",
  "dp4a.u32.u32",
  "sad.u32",
  "div.s32",
  "rem.s32",
  "min.s32",
  "max.s32",
  "mul.hi.s32",
  "mad.hi.s32",
  "mad.lo.s32",
  "shr.s32",
  "bfe.s32",
  "bfind.s32",
  "bfind.shiftamt.s32",
  "dp2a.lo.s32.u32",
  "dp2a.hi.s32.s32",
  "dp4a.s32.s32",
  "dp4a.s32.u32",
  "sad.s32",
  "shl.b32",
  "abs.s32",
  "neg.s32",
  "bfi.b32",
  "brev.b32",
  "popc.b32",
  "clz.b32",
  "fns.b32",
  "bmsk.clamp",
  "bmsk.wrap",
  "shf.l.wrap",
  "shf.l.clamp",
  "shf.r.wrap",
  "shf.r.clamp",
  "prmt",
  "lop3 0x96",
  "lop3 0xe8",
  "add.cc/addc",
  "sub.cc/subc",
  "mad.lo.cc/madc.hi",
  "mul.wide.s16",
  "mul.wide.u16",
  "div.s64 lo",
  "div.s64 hi",
  "rem.s64 lo",
  "rem.s64 hi",
  "div.u64 lo",
  "div.u64 hi",
  "rem.u64 lo",
  "rem.u64 hi",
  "mul.hi.s64 lo",
  "mul.hi.s64 hi",
  "mul.hi.u64 lo",
  "mul.hi.u64 hi",
  "min.s64 lo",
  "min.s64 hi",
  "max.u64 lo",
  "max.u64 hi",
  "shr.s64 lo",
  "shl.b64 lo",
  "popc.b64",
  "clz.b64",
  "brev.b64 hi",
  "bfind.s64",
  "mul.wide.s32 hi",
  "mad.wide.u32 hi",
  "add.rn.f32",
  "sub.rn.f32",
  "mul.rn.f32",
  "div.rn.f32",
  "sqrt.rn.f32",
  "rcp.rn.f32",
  "div.rn.ftz.f32",
  "add.rn.ftz.f32",
  "mul.rn.ftz.f32",
  "add.rn.f64 lo",
  "add.rn.f64 hi",
  "mul.rn.f64 lo",
  "mul.rn.f64 hi",
  "div.rn.f64 lo",
  "div.rn.f64 hi",
  "fma.rn.f64 lo",
  "fma.rn.f64 hi",
  "sqrt.rn.f64 hi",
  "rcp.rn.f64 hi",
  "add.rz.f32",
  "sub.rz.f32",
  "mul.rz.f32",
  "div.rz.f32",
  "sqrt.rz.f32",
  "rcp.rz.f32",
  "div.rz.ftz.f32",
  "add.rz.ftz.f32",
  "mul.rz.ftz.f32",
  "add.rz.f64 lo",
  "add.rz.f64 hi",
  "mul.rz.f64 lo",
  "mul.rz.f64 hi",
  "div.rz.f64 lo",
  "div.rz.f64 hi",
  "fma.rz.f64 lo",
  "fma.rz.f64 hi",
  "sqrt.rz.f64 hi",
  "rcp.rz.f64 hi",
  "add.rm.f32",
  "sub.rm.f32",
  "mul.rm.f32",
  "div.rm.f32",
  "sqrt.rm.f32",
  "rcp.rm.f32",
  "div.rm.ftz.f32",
  "add.rm.ftz.f32",
  "mul.rm.ftz.f32",
  "add.rm.f64 lo",
  "add.rm.f64 hi",
  "mul.rm.f64 lo",
  "mul.rm.f64 hi",
  "div.rm.f64 lo",
  "div.rm.f64 hi",
  "fma.rm.f64 lo",
  "fma.rm.f64 hi",
  "sqrt.rm.f64 hi",
  "rcp.rm.f64 hi",
  "add.rp.f32",
  "sub.rp.f32",
  "mul.rp.f32",
  "div.rp.f32",
  "sqrt.rp.f32",
  "rcp.rp.f32",
  "div.rp.ftz.f32",
  "add.rp.ftz.f32",
  "mul.rp.ftz.f32",
  "add.rp.f64 lo",
  "add.rp.f64 hi",
  "mul.rp.f64 lo",
  "mul.rp.f64 hi",
  "div.rp.f64 lo",
  "div.rp.f64 hi",
  "fma.rp.f64 lo",
  "fma.rp.f64 hi",
  "sqrt.rp.f64 hi",
  "rcp.rp.f64 hi",
  "min.f32",
  "max.ftz.f32",
  "min.f64 hi",
  "max.f64 lo",
  "abs.f32",
  "neg.ftz.f32",
  "abs.ftz.f32",
  "copysign.f32",
  "testp.finite",
  "testp.infinite",
  "testp.number",
  "testp.notanumber",
  "testp.normal",
  "testp.subnormal",
  "setp.eq.f32",
  "setp.ne.f32",
  "setp.lt.f32",
  "setp.le.f32",
  "setp.gt.f32",
  "setp.ge.f32",
  "setp.lo.u32",
  "setp.ls.u32",
  "setp.hi.u32",
  "setp.hs.u32",
  "setp.equ.f32",
  "setp.neu.f32",
  "setp.ltu.f32",
  "setp.leu.f32",
  "setp.gtu.f32",
  "setp.geu.f32",
  "setp.num.f32",
  "setp.nan.f32",
  "set.lt.f32.f32",
  "set.gtu.u32.f32",
  "selp.b32",
  "slct.s32.f32",
  "slct.u32.s32",
  "cvt.rni.s32.f32",
  "cvt.rni.sat.s32.f32",
  "cvt.rzi.s32.f32",
  "cvt.rzi.sat.s32.f32",
  "cvt.rmi.s32.f32",
  "cvt.rmi.sat.s32.f32",
  "cvt.rpi.s32.f32",
  "cvt.rpi.sat.s32.f32",
  "cvt.rzi.s32.f64",
  "cvt.rni.u32.f32",
  "cvt.rni.sat.u32.f32",
  "cvt.rzi.u32.f32",
  "cvt.rzi.sat.u32.f32",
  "cvt.rmi.u32.f32",
  "cvt.rmi.sat.u32.f32",
  "cvt.rpi.u32.f32",
  "cvt.rpi.sat.u32.f32",
  "cvt.rzi.u32.f64",
  "cvt.rni.s16.f32",
  "cvt.rni.sat.s16.f32",
  "cvt.rzi.s16.f32",
  "cvt.rzi.sat.s16.f32",
  "cvt.rmi.s16.f32",
  "cvt.rmi.sat.s16.f32",
  "cvt.rpi.s16.f32",
  "cvt.rpi.sat.s16.f32",
  "cvt.rni.u16.f32",
  "cvt.rni.sat.u16.f32",
  "cvt.rzi.u16.f32",
  "cvt.rzi.sat.u16.f32",
  "cvt.rmi.u16.f32",
  "cvt.rmi.sat.u16.f32",
  "cvt.rpi.u16.f32",
  "cvt.rpi.sat.u16.f32",
  "cvt.rni.s8.f32",
  "cvt.rni.sat.s8.f32",
  "cvt.rzi.s8.f32",
  "cvt.rzi.sat.s8.f32",
  "cvt.rmi.s8.f32",
  "cvt.rmi.sat.s8.f32",
  "cvt.rpi.s8.f32",
  "cvt.rpi.sat.s8.f32",
  "cvt.rni.u8.f32",
  "cvt.rni.sat.u8.f32",
  "cvt.rzi.u8.f32",
  "cvt.rzi.sat.u8.f32",
  "cvt.rmi.u8.f32",
  "cvt.rmi.sat.u8.f32",
  "cvt.rpi.u8.f32",
  "cvt.rpi.sat.u8.f32",
  "cvt.rni.s64.f32 lo",
  "cvt.rni.s64.f32 hi",
  "cvt.rni.sat.s64.f32 lo",
  "cvt.rni.sat.s64.f32 hi",
  "cvt.rzi.s64.f32 lo",
  "cvt.rzi.s64.f32 hi",
  "cvt.rzi.sat.s64.f32 lo",
  "cvt.rzi.sat.s64.f32 hi",
  "cvt.rmi.s64.f32 lo",
  "cvt.rmi.s64.f32 hi",
  "cvt.rmi.sat.s64.f32 lo",
  "cvt.rmi.sat.s64.f32 hi",
  "cvt.rpi.s64.f32 lo",
  "cvt.rpi.s64.f32 hi",
  "cvt.rpi.sat.s64.f32 lo",
  "cvt.rpi.sat.s64.f32 hi",
  "cvt.rni.u64.f32 lo",
  "cvt.rni.u64.f32 hi",
  "cvt.rni.sat.u64.f32 lo",
  "cvt.rni.sat.u64.f32 hi",
  "cvt.rzi.u64.f32 lo",
  "cvt.rzi.u64.f32 hi",
  "cvt.rzi.sat.u64.f32 lo",
  "cvt.rzi.sat.u64.f32 hi",
  "cvt.rmi.u64.f32 lo",
  "cvt.rmi.u64.f32 hi",
  "cvt.rmi.sat.u64.f32 lo",
  "cvt.rmi.sat.u64.f32 hi",
  "cvt.rpi.u64.f32 lo",
  "cvt.rpi.u64.f32 hi",
  "cvt.rpi.sat.u64.f32 lo",
  "cvt.rpi.sat.u64.f32 hi",
  "cvt.rn.f32.s32",
  "cvt.rz.f32.s32",
  "cvt.rm.f32.s32",
  "cvt.rp.f32.s32",
  "cvt.rn.f32.u32",
  "cvt.rz.f32.u32",
  "cvt.rm.f32.u32",
  "cvt.rp.f32.u32",
  "cvt.rn.f32.s64",
  "cvt.rn.f64.s64 hi",
  "cvt.rz.f32.s64",
  "cvt.rz.f64.s64 hi",
  "cvt.rm.f32.s64",
  "cvt.rm.f64.s64 hi",
  "cvt.rp.f32.s64",
  "cvt.rp.f64.s64 hi",
  "cvt.rn.f32.u64",
  "cvt.rn.f64.u64 hi",
  "cvt.rz.f32.u64",
  "cvt.rz.f64.u64 hi",
  "cvt.rm.f32.u64",
  "cvt.rm.f64.u64 hi",
  "cvt.rp.f32.u64",
  "cvt.rp.f64.u64 hi",
  "cvt.rn.f32.f64",
  "cvt.rn.ftz.f32.f64",
  "cvt.rn.f16.f32",
  "cvt.rn.f16.f64",
  "cvt.rni.f32.f32",
  "cvt.rn.f16.s32",
  "cvt.rz.f32.f64",
  "cvt.rz.ftz.f32.f64",
  "cvt.rz.f16.f32",
  "cvt.rz.f16.f64",
  "cvt.rzi.f32.f32",
  "cvt.rz.f16.s32",
  "cvt.rm.f32.f64",
  "cvt.rm.ftz.f32.f64",
  "cvt.rm.f16.f32",
  "cvt.rm.f16.f64",
  "cvt.rmi.f32.f32",
  "cvt.rm.f16.s32",
  "cvt.rp.f32.f64",
  "cvt.rp.ftz.f32.f64",
  "cvt.rp.f16.f32",
  "cvt.rp.f16.f64",
  "cvt.rpi.f32.f32",
  "cvt.rp.f16.s32",
  "cvt.f32.f16",
  "cvt.f64.f32 hi",
  "cvt.ftz.f64.f32 hi",
  "cvt.rzi.s32.f16",
  "cvt.rn.bf16.f32",
  "cvt.rn.bf16x2.f32",
  "cvt.sat.f32.f32",
  "cvt.ftz.f32.f32",
  "cvt.sat.s8.s32",
  "cvt.sat.u8.u32",
  "cvt.sat.s16.u32",
  "cvt.sat.u16.s32",
  "cvt.sat.s8.u32",
  "cvt.sat.u8.s8",
  "cvt.pack.sat.s16.s32",
  "cvt.pack.sat.u8.s32.b32",
  "add.rn.f16x2",
  "sub.rn.f16x2",
  "mul.rn.f16x2",
  "fma.rn.f16x2",
  "fma.rn.bf16x2",
  "min.f16x2",
  "min.bf16x2",
  "max.f16x2",
  "max.bf16x2",
  "neg.f16x2",
  "abs.f16x2",
  "neg.bf16x2",
  "setp.lt.f16x2",
  "set.lt.u32.f16x2",
  "cvt.rzi.s64.f64 lo",
  "cvt.rzi.s64.f64 hi",
  "cvt.rzi.u64.f64 lo",
  "cvt.rzi.u64.f64 hi",
  "cvt.rzi.s16.f64",
  "cvt.rzi.u16.f64",
  "cvt.rzi.u32.f16",
  "cvt.ftz.f64.f32 lo",
  "cvt.f64.f32 lo",
  "neg.f32",
  "abs.f64 hi",
  "neg.f64 hi",
  "abs.f64 lo",
  "neg.f16",
  "abs.bf16",
  "testp.normal.f64 zeros",
  "testp.normal.f64",
  "testp.subnormal.f64",
  "testp.notanumber.f64",
  "testp.finite.f64",
  "sqrt.approx.f32 NaN only",
  "rcp.rn.ftz.f32",
  "sqrt.rn.ftz.f32",
  "min.ftz.f32",
  "sub.rn.ftz.f32",
  "rem.u64 by-zero-ish lo",
  "div.s64 by-c lo",
};
int main(int argc, char** argv) {
  const bool print = argc > 1 && std::strcmp(argv[1], "--print") == 0;
  const int dump = argc > 2 && std::strcmp(argv[1], "--dump") == 0 ? atoi(argv[2]) : -1;
  const int nv = sizeof kTags / sizeof kTags[0];
  // Random bits, and values that exercise the modifiers: f32 and packed-half
  // edges (+-0, +-1, NaN, subnormals, near-overflow, near-1, rounding ties).
  static const unsigned edge[] = {
      0x00000000u, 0x80000000u, 0x3f800000u, 0xbf800000u, 0x7fc00000u, 0xff800001u, 0x00000001u, 0x007fffffu,
      0x7f7fffffu, 0x3f7fffffu, 0x3f800001u, 0x3f801000u, 0x3dcccccdu, 0x40000000u, 0xc0400000u, 0x7f800000u,
      0x3c00bc00u, 0x7e003c00u, 0x00010002u, 0x7bff7c00u, 0x3bff3c01u, 0x80000000u, 0x3f80bf80u, 0x7fc0ff80u,
      0x12345678u, 0x9abcdef0u, 0x007fffffu, 0x7fffffffu, 0x00800000u, 0xffffffffu, 0x0f1e2d3cu, 0x00000003u};
  unsigned h[3 * kN];
  unsigned long long s = 0x9E3779B97F4A7C15ull;
  for (int i = 0; i < 3 * kN; ++i) {
    s ^= s << 13; s ^= s >> 7; s ^= s << 17;
    h[i] = static_cast<unsigned>(s);
    if ((s >> 40) % 3 == 0) h[i] = edge[(s >> 48) % 32];
  }
  unsigned *din, *dout;
  cudaMalloc(&din, sizeof h);
  cudaMalloc(&dout, kN * 4);
  cudaMemcpy(din, h, sizeof h, cudaMemcpyHostToDevice);
  int bad = 0;
  for (int v = 0; v < nv; ++v) {
    k<<<1, kN>>>(v, din, dout);
    if (cudaDeviceSynchronize() != cudaSuccess) { printf("variant %d (%s) failed to run\n", v, kTags[v]); return 1; }
    unsigned o[kN];
    cudaMemcpy(o, dout, sizeof o, cudaMemcpyDeviceToHost);
    unsigned long long hash = 1469598103934665603ull;
    for (unsigned x : o) { hash ^= x; hash *= 1099511628211ull; }
    if (v == dump) {
      for (int i = 0; i < kN; ++i) printf("%3d a=%08x b=%08x c=%08x d=%08x\n", i, h[3 * i], h[3 * i + 1], h[3 * i + 2], o[i]);
      return 0;
    }
    if (print) { printf("    {\"%s\", 0x%016llxull},\n", kTags[v], hash); continue; }
    if (dump >= 0) continue;
    if (v >= (int)(sizeof kExpected / sizeof kExpected[0]) || hash != kExpected[v].hash) {
      if (bad++ < 40) printf("%s: 0x%016llx, the card gave 0x%016llx\n", kTags[v], hash,
                             v < (int)(sizeof kExpected / sizeof kExpected[0]) ? kExpected[v].hash : 0ull);
    }
  }
  if (print) return 0;
  const int ne = sizeof kExpected / sizeof kExpected[0];
  printf("%d PTX sweep variants, %d differ\n%s\n", nv, bad, bad || ne != nv ? "FAIL" : "PASS");
  return bad ? 1 : 0;
}
