// The memory forms real compilers emit: ld/st with every cache operator,
// .volatile and the .relaxed/.acquire/.release scopes, atomics with their
// semantics and scopes, fences, generic addressing and cvta, mbarrier, cp.async,
// ldmatrix and movmatrix, each variant run by 256 threads (eight warps), with
// a word of global and of shared memory per thread; each variant's results and the
// memory it left are hashed and compared with an RTX 3060's (sm_86), recorded
// in ptx_memory_forms_expected.inc (`ptx_memory_forms --print` prints them; `--dump N`
// prints variant N's values). Generated by ptx_memory_forms_gen.py. Prints PASS on
// the last line, and runs the same on a GPU.
#include <cstdio>
#include <cstdlib>
#include <cstring>
struct Expected { const char* tag; unsigned long long hash; };
static const Expected kExpected[] = {
#include "ptx_memory_forms_expected.inc"
};
constexpr int kN = 256;
__global__ void k(int v, const unsigned* in, unsigned* out, unsigned long long* g) {
  __shared__ unsigned sh[kN];
  const int i = threadIdx.x;
  const unsigned a = in[3 * i], b = in[3 * i + 1], c = in[3 * i + 2];
  g[i] = c | ((unsigned long long)b << 32);
  sh[i] = c;
  __syncthreads();
  const unsigned sa = (unsigned)__cvta_generic_to_shared(sh);
  unsigned d = 0;
  switch (v) {
    case 0: asm volatile("ld.global.ca.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 1: asm volatile("ld.global.cg.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 2: asm volatile("ld.global.cs.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 3: asm volatile("ld.global.lu.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 4: asm volatile("ld.global.cv.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 5: asm volatile("{ st.global.wb.u32 [%4], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 6: asm volatile("{ st.global.cg.u32 [%4], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 7: asm volatile("{ st.global.cs.u32 [%4], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 8: asm volatile("{ st.global.wt.u32 [%4], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 9: asm volatile("ld.global.L2::128B.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 10: asm volatile("ld.volatile.global.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 11: asm volatile("{ st.volatile.global.u32 [%4], %1; ld.volatile.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 12: asm volatile("ld.relaxed.cta.global.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 13: asm volatile("ld.relaxed.gpu.global.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 14: asm volatile("ld.relaxed.sys.global.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 15: asm volatile("ld.acquire.cta.global.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 16: asm volatile("ld.acquire.gpu.global.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 17: asm volatile("ld.acquire.sys.global.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 18: asm volatile("{ st.relaxed.cta.global.u32 [%4], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 19: asm volatile("{ st.relaxed.gpu.global.u32 [%4], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 20: asm volatile("{ st.relaxed.sys.global.u32 [%4], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 21: asm volatile("{ st.release.cta.global.u32 [%4], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 22: asm volatile("{ st.release.gpu.global.u32 [%4], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 23: asm volatile("{ st.release.sys.global.u32 [%4], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 24: asm volatile("atom.relaxed.cta.global.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 25: asm volatile("atom.relaxed.gpu.global.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 26: asm volatile("atom.relaxed.sys.global.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 27: asm volatile("{ .reg .u32 o; ld.global.u32 o, [%4]; atom.relaxed.gpu.global.cas.b32 %0, [%4], o, %1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 28: asm volatile("atom.acquire.cta.global.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 29: asm volatile("atom.acquire.gpu.global.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 30: asm volatile("atom.acquire.sys.global.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 31: asm volatile("{ .reg .u32 o; ld.global.u32 o, [%4]; atom.acquire.gpu.global.cas.b32 %0, [%4], o, %1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 32: asm volatile("atom.release.cta.global.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 33: asm volatile("atom.release.gpu.global.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 34: asm volatile("atom.release.sys.global.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 35: asm volatile("{ .reg .u32 o; ld.global.u32 o, [%4]; atom.release.gpu.global.cas.b32 %0, [%4], o, %1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 36: asm volatile("atom.acq_rel.cta.global.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 37: asm volatile("atom.acq_rel.gpu.global.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 38: asm volatile("atom.acq_rel.sys.global.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 39: asm volatile("{ .reg .u32 o; ld.global.u32 o, [%4]; atom.acq_rel.gpu.global.cas.b32 %0, [%4], o, %1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 40: asm volatile("{ red.relaxed.cta.global.add.u32 [%4], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 41: asm volatile("atom.cta.global.exch.b32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 42: asm volatile("{ red.relaxed.gpu.global.add.u32 [%4], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 43: asm volatile("atom.gpu.global.exch.b32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 44: asm volatile("{ red.relaxed.sys.global.add.u32 [%4], %1; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 45: asm volatile("atom.sys.global.exch.b32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 46: asm volatile("{ fence.sc.cta; add.u32 %0, %1, %2; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 47: asm volatile("{ fence.sc.gpu; add.u32 %0, %1, %2; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 48: asm volatile("{ fence.sc.sys; add.u32 %0, %1, %2; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 49: asm volatile("{ fence.acq_rel.cta; add.u32 %0, %1, %2; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 50: asm volatile("{ fence.acq_rel.gpu; add.u32 %0, %1, %2; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 51: asm volatile("{ fence.acq_rel.sys; add.u32 %0, %1, %2; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 52: asm volatile("{ membar.cta; add.u32 %0, %1, %2; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 53: asm volatile("{ membar.gl; add.u32 %0, %1, %2; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 54: asm volatile("{ membar.sys; add.u32 %0, %1, %2; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 55: asm volatile("{ fence.proxy.alias; add.u32 %0, %1, %2; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 56: asm volatile("{ .reg .u32 ad; shl.b32 ad, %6, 2; add.u32 ad, ad, %5; ld.shared.u32 %0, [ad]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 57: asm volatile("{ .reg .u32 ad, x; .reg .pred p; and.b32 x, %6, 1; setp.eq.u32 p, x, 0; shl.b32 ad, %6, 2; add.u32 ad, ad, %5; @p st.shared.v2.u32 [ad], {%1, %2}; bar.sync 0; ld.shared.u32 %0, [ad]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 58: asm volatile("{ .reg .u32 ad, x, y, z, w; and.b32 ad, %6, 0xfc; shl.b32 ad, ad, 2; add.u32 ad, ad, %5; ld.shared.v4.u32 {x, y, z, w}, [ad]; add.u32 %0, x, y; add.u32 %0, %0, z; xor.b32 %0, %0, w; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 59: asm volatile("{ .reg .u16 x; .reg .u32 ad; add.u32 ad, %6, %5; ld.shared.u8 x, [ad]; cvt.u32.u16 %0, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 60: asm volatile("{ .reg .u32 ad; shl.b32 ad, %6, 2; add.u32 ad, ad, %5; ld.volatile.shared.u32 %0, [ad]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 61: asm volatile("{ .reg .u32 ad; shl.b32 ad, %6, 2; add.u32 ad, ad, %5; ld.relaxed.cta.shared.u32 %0, [ad]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 62: asm volatile("{ .reg .u32 ad; shl.b32 ad, %6, 2; add.u32 ad, ad, %5; atom.relaxed.cta.shared.add.u32 %0, [ad], %1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 63: asm volatile("ld.u32 %0, [%4];" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 64: asm volatile("{ st.u32 [%4], %1; ld.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 65: asm volatile("atom.add.u32 %0, [%4], %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 66: asm volatile("{ .reg .u64 p, q; cvta.to.global.u64 p, %4; cvta.global.u64 q, p; ld.u32 %0, [q]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 67: asm volatile("{ .reg .u64 p, q; .reg .u32 ad; shl.b32 ad, %6, 2; add.u32 ad, ad, %5; cvt.u64.u32 p, ad; cvta.shared.u64 q, p; ld.u32 %0, [q]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 68: asm volatile("{ .reg .u64 p, q; .reg .pred s; cvt.u64.u32 p, %5; cvta.shared.u64 q, p; isspacep.shared s, q; selp.u32 %0, 1, 0, s; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 69: asm volatile("{ .reg .pred s; isspacep.global s, %4; selp.u32 %0, 1, 0, s; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 70: asm volatile("{ .reg .pred s; isspacep.local s, %4; selp.u32 %0, 1, 0, s; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 71: asm volatile("{ .reg .u64 st; .reg .pred p; .reg .u32 ad; add.u32 ad, %5, 1016; setp.eq.u32 p, %6, 0; @p mbarrier.init.shared.b64 [ad], 256; bar.sync 0; mbarrier.arrive.shared.b64 st, [ad]; bar.sync 0; mbarrier.test_wait.shared.b64 p, [ad], st; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 72: asm volatile("{ .reg .u32 ad; shl.b32 ad, %6, 2; add.u32 ad, ad, %5; cp.async.ca.shared.global [ad], [%4], 4; cp.async.wait_all; ld.shared.u32 %0, [ad]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 73: asm volatile("{ .reg .u32 ad; shl.b32 ad, %6, 2; add.u32 ad, ad, %5; cp.async.ca.shared.global [ad], [%4], 4, 2; cp.async.wait_all; ld.shared.u32 %0, [ad]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 74: asm volatile("{ .reg .u32 ad, x, y, z, w; .reg .pred p; and.b32 x, %6, 1; setp.lt.u32 p, %6, 63; @p setp.eq.u32 p, x, 0; shl.b32 ad, %6, 4; add.u32 ad, ad, %5; @p cp.async.cg.shared.global [ad], [%4], 16, 8; cp.async.commit_group; cp.async.wait_group 0; bar.sync 0; @p ld.shared.v4.u32 {x, y, z, w}, [ad]; @p xor.b32 %0, x, z; @p add.u32 %0, %0, w; @!p mov.u32 %0, 0; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 75: asm volatile("{ .reg .u32 ad; and.b32 ad, %6, 7; shl.b32 ad, ad, 4; add.u32 ad, ad, %5; ldmatrix.sync.aligned.m8n8.x1.shared.b16 {%0}, [ad]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 76: asm volatile("{ .reg .u32 ad, y; and.b32 ad, %6, 15; shl.b32 ad, ad, 4; add.u32 ad, ad, %5; ldmatrix.sync.aligned.m8n8.x2.trans.shared.b16 {%0, y}, [ad]; xor.b32 %0, %0, y; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 77: asm volatile("{ .reg .u32 ad, y, z, w; and.b32 ad, %6, 31; shl.b32 ad, ad, 4; add.u32 ad, ad, %5; ldmatrix.sync.aligned.m8n8.x4.shared.b16 {%0, y, z, w}, [ad]; add.u32 %0, %0, y; xor.b32 %0, %0, z; add.u32 %0, %0, w; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 78: asm volatile("movmatrix.sync.aligned.m8n8.trans.b16 %0, %1;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 79: asm volatile("{ nanosleep.u32 7; mov.u32 %0, %1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 80: asm volatile("{ prefetch.global.L2 [%4]; mov.u32 %0, %1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 81: asm volatile("{ prefetchu.L1 [%4]; mov.u32 %0, %1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 82: asm volatile("{ .reg .u64 p; and.b64 p, %4, -128; mov.u32 %0, %1; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 83: asm volatile("{ .reg .b64 pol; createpolicy.fractional.L2::evict_last.b64 pol, 1.0; ld.global.L2::cache_hint.u32 %0, [%4], pol; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 84: asm volatile("{ .reg .u32 x, y; ld.global.v2.u32 {x, y}, [%4]; sub.u32 %0, x, y; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 85: asm volatile("{ st.global.v2.u32 [%4], {%2, %1}; ld.global.u32 %0, [%4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 86: asm volatile("{ .reg .b64 x; ld.global.b64 x, [%4]; mov.b64 {%0, _}, x; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 87: asm volatile("{ .reg .u64 x; mov.b64 x, {%1, %2}; red.global.add.u64 [%4], x; ld.global.u32 %0, [%4+4]; }" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 88: asm volatile("atom.global.inc.u32 %0, [%4], 5;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
    case 89: asm volatile("atom.global.dec.u32 %0, [%4], 5;" : "=r"(d) : "r"(a), "r"(b), "r"(c), "l"(&g[i]), "r"(sa), "r"((unsigned)i) : "memory"); break;
  }
  out[2 * i] = d;
  out[2 * i + 1] = (unsigned)g[i] ^ (unsigned)(g[i] >> 32);
}
static const char* kTags[] = {
  "ld.global.ca",
  "ld.global.cg",
  "ld.global.cs",
  "ld.global.lu",
  "ld.global.cv",
  "st.global.wb",
  "st.global.cg",
  "st.global.cs",
  "st.global.wt",
  "ld.global.L2::128B",
  "ld.volatile.global",
  "st.volatile.global",
  "ld.relaxed.cta.global",
  "ld.relaxed.gpu.global",
  "ld.relaxed.sys.global",
  "ld.acquire.cta.global",
  "ld.acquire.gpu.global",
  "ld.acquire.sys.global",
  "st.relaxed.cta.global",
  "st.relaxed.gpu.global",
  "st.relaxed.sys.global",
  "st.release.cta.global",
  "st.release.gpu.global",
  "st.release.sys.global",
  "atom.relaxed.cta.global.add",
  "atom.relaxed.gpu.global.add",
  "atom.relaxed.sys.global.add",
  "atom.relaxed.gpu.global.cas",
  "atom.acquire.cta.global.add",
  "atom.acquire.gpu.global.add",
  "atom.acquire.sys.global.add",
  "atom.acquire.gpu.global.cas",
  "atom.release.cta.global.add",
  "atom.release.gpu.global.add",
  "atom.release.sys.global.add",
  "atom.release.gpu.global.cas",
  "atom.acq_rel.cta.global.add",
  "atom.acq_rel.gpu.global.add",
  "atom.acq_rel.sys.global.add",
  "atom.acq_rel.gpu.global.cas",
  "red.relaxed.cta.global.add",
  "atom.cta.global.exch",
  "red.relaxed.gpu.global.add",
  "atom.gpu.global.exch",
  "red.relaxed.sys.global.add",
  "atom.sys.global.exch",
  "fence.sc.cta",
  "fence.sc.gpu",
  "fence.sc.sys",
  "fence.acq_rel.cta",
  "fence.acq_rel.gpu",
  "fence.acq_rel.sys",
  "membar.cta",
  "membar.gl",
  "membar.sys",
  "fence.proxy.alias",
  "ld.shared",
  "st.shared.v2",
  "ld.shared.v4",
  "ld.shared.b8",
  "ld.volatile.shared",
  "ld.relaxed.cta.shared",
  "atom.shared.cta.add",
  "ld generic",
  "st generic",
  "atom generic",
  "cvta.to.global round trip",
  "cvta shared round trip",
  "isspacep.shared of shared",
  "isspacep.global of global",
  "isspacep.local of global",
  "mbarrier arrive/test",
  "cp.async.ca 4",
  "cp.async.ca 4 src 2",
  "cp.async.cg 16",
  "ldmatrix.x1",
  "ldmatrix.x2.trans",
  "ldmatrix.x4",
  "movmatrix.trans",
  "nanosleep",
  "prefetch.global.L2",
  "prefetchu.L1",
  "discard.global.L2",
  "createpolicy",
  "ld.global.v2",
  "st.global.v2",
  "ld.global.b64",
  "red.global.add.u64",
  "atom.global.inc wrap",
  "atom.global.dec wrap",
};
int main(int argc, char** argv) {
  const bool print = argc > 1 && std::strcmp(argv[1], "--print") == 0;
  const int dump = argc > 2 && std::strcmp(argv[1], "--dump") == 0 ? atoi(argv[2]) : -1;
  const int nv = sizeof kTags / sizeof kTags[0];
  static const unsigned edge[] = {
      0x00000000u, 0x80000000u, 0x3f800000u, 0xbf800000u, 0x7fc00000u, 0xff800001u, 0x00000001u, 0x007fffffu,
      0x7f7fffffu, 0x3f7fffffu, 0x3f800001u, 0x3f801000u, 0x3dcccccdu, 0x40000000u, 0xc0400000u, 0x7f800000u,
      0x3c00bc00u, 0x7e003c00u, 0x00010002u, 0x7bff7c00u, 0x3bff3c01u, 0x80000000u, 0x3f80bf80u, 0x7fc0ff80u,
      0x12345678u, 0x9abcdef0u, 0x007fffffu, 0x7fffffffu, 0x00800000u, 0xffffffffu, 0x0f1e2d3cu, 0x00000003u};
  unsigned h[3 * kN];
  unsigned long long s = 0x9E3779B97F4A7C15ull;
  for (int i = 0; i < 3 * kN; ++i) {
    s ^= s << 13; s ^= s >> 7; s ^= s << 17;
    h[i] = static_cast<unsigned>(s);
    if ((s >> 40) % 3 == 0) h[i] = edge[(s >> 48) % 32];
  }
  unsigned *din, *dout;
  unsigned long long* dg;
  cudaMalloc(&din, sizeof h);
  cudaMalloc(&dout, 2 * kN * 4);
  cudaMalloc(&dg, kN * 8);
  cudaMemcpy(din, h, sizeof h, cudaMemcpyHostToDevice);
  int bad = 0;
  for (int v = 0; v < nv; ++v) {
    k<<<1, kN>>>(v, din, dout, dg);
    if (cudaDeviceSynchronize() != cudaSuccess) { printf("variant %d (%s) failed to run\n", v, kTags[v]); return 1; }
    unsigned o[2 * kN];
    cudaMemcpy(o, dout, sizeof o, cudaMemcpyDeviceToHost);
    unsigned long long hash = 1469598103934665603ull;
    for (unsigned x : o) { hash ^= x; hash *= 1099511628211ull; }
    if (v == dump) {
      for (int i = 0; i < kN; ++i)
        printf("%3d a=%08x b=%08x c=%08x d=%08x m=%08x\n", i, h[3 * i], h[3 * i + 1], h[3 * i + 2], o[2 * i], o[2 * i + 1]);
      return 0;
    }
    if (print) { printf("    {\"%s\", 0x%016llxull},\n", kTags[v], hash); continue; }
    if (dump >= 0) continue;
    const int ne = sizeof kExpected / sizeof kExpected[0];
    if (v >= ne || hash != kExpected[v].hash)
      if (bad++ < 40) printf("%s: 0x%016llx, the card gave 0x%016llx\n", kTags[v], hash, v < ne ? kExpected[v].hash : 0ull);
  }
  if (print) return 0;
  const int ne = sizeof kExpected / sizeof kExpected[0];
  printf("%d memory-qualifier forms, %d differ\n%s\n", nv, bad, bad || ne != nv ? "FAIL" : "PASS");
  return bad ? 1 : 0;
}
