// PTX forms a differential probe against an RTX 3060 found missing or
// wrong, each variant over the same 256 operand triples, its results hashed
// and compared with the card's (sm_86), recorded in ptx_forms_expected.inc
// (`ptx_forms --print` prints them; `--dump N` prints variant N's values).
// Generated by ptx_forms_gen.py. Prints PASS on the last line, and runs the
// same on a GPU.
#include <cstdio>
#include <cstdlib>
#include <cstring>
struct Expected { const char* tag; unsigned long long hash; };
static const Expected kExpected[] = {
#include "ptx_forms_expected.inc"
};
constexpr int kN = 256;
__global__ void k(int v, const unsigned* in, unsigned* out) {
  const int i = threadIdx.x;
  const unsigned a = in[3 * i], b = in[3 * i + 1], c = in[3 * i + 2];
  unsigned d = 0;
  switch (v) {
    case 0: asm volatile("prmt.b32.f4e %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 1: asm volatile("prmt.b32.b4e %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 2: asm volatile("prmt.b32.rc8 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 3: asm volatile("prmt.b32.ecl %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 4: asm volatile("prmt.b32.ecr %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 5: asm volatile("prmt.b32.rc16 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 6: asm volatile("{ .reg .pred p, q; setp.ne.u32 q, %3, 0; setp.lt.and.u32 p, %1, %2, q; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 7: asm volatile("{ .reg .pred p, q, r; setp.ne.u32 r, %3, 0; setp.lt.and.u32 p|q, %1, %2, !r; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 8: asm volatile("{ .reg .pred p, q; setp.ne.u32 q, %3, 0; setp.ge.and.s32 p, %1, %2, q; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 9: asm volatile("{ .reg .pred p, q, r; setp.ne.u32 r, %3, 0; setp.ge.and.s32 p|q, %1, %2, !r; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 10: asm volatile("{ .reg .pred p, q; setp.ne.u32 q, %3, 0; setp.ne.and.f32 p, %1, %2, q; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 11: asm volatile("{ .reg .pred p, q, r; setp.ne.u32 r, %3, 0; setp.ne.and.f32 p|q, %1, %2, !r; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 12: asm volatile("{ .reg .pred p, q; setp.ne.u32 q, %3, 0; setp.gtu.and.f32 p, %1, %2, q; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 13: asm volatile("{ .reg .pred p, q, r; setp.ne.u32 r, %3, 0; setp.gtu.and.f32 p|q, %1, %2, !r; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 14: asm volatile("{ .reg .pred r; setp.ne.u32 r, %3, 0; set.lt.and.u32.s32 %0, %1, %2, r; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 15: asm volatile("{ .reg .pred r; setp.ne.u32 r, %3, 0; set.le.and.f32.f32 %0, %1, %2, !r; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 16: asm volatile("{ .reg .pred p, q; setp.ne.u32 q, %3, 0; setp.lt.or.u32 p, %1, %2, q; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 17: asm volatile("{ .reg .pred p, q, r; setp.ne.u32 r, %3, 0; setp.lt.or.u32 p|q, %1, %2, !r; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 18: asm volatile("{ .reg .pred p, q; setp.ne.u32 q, %3, 0; setp.ge.or.s32 p, %1, %2, q; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 19: asm volatile("{ .reg .pred p, q, r; setp.ne.u32 r, %3, 0; setp.ge.or.s32 p|q, %1, %2, !r; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 20: asm volatile("{ .reg .pred p, q; setp.ne.u32 q, %3, 0; setp.ne.or.f32 p, %1, %2, q; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 21: asm volatile("{ .reg .pred p, q, r; setp.ne.u32 r, %3, 0; setp.ne.or.f32 p|q, %1, %2, !r; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 22: asm volatile("{ .reg .pred p, q; setp.ne.u32 q, %3, 0; setp.gtu.or.f32 p, %1, %2, q; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 23: asm volatile("{ .reg .pred p, q, r; setp.ne.u32 r, %3, 0; setp.gtu.or.f32 p|q, %1, %2, !r; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 24: asm volatile("{ .reg .pred r; setp.ne.u32 r, %3, 0; set.lt.or.u32.s32 %0, %1, %2, r; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 25: asm volatile("{ .reg .pred r; setp.ne.u32 r, %3, 0; set.le.or.f32.f32 %0, %1, %2, !r; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 26: asm volatile("{ .reg .pred p, q; setp.ne.u32 q, %3, 0; setp.lt.xor.u32 p, %1, %2, q; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 27: asm volatile("{ .reg .pred p, q, r; setp.ne.u32 r, %3, 0; setp.lt.xor.u32 p|q, %1, %2, !r; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 28: asm volatile("{ .reg .pred p, q; setp.ne.u32 q, %3, 0; setp.ge.xor.s32 p, %1, %2, q; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 29: asm volatile("{ .reg .pred p, q, r; setp.ne.u32 r, %3, 0; setp.ge.xor.s32 p|q, %1, %2, !r; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 30: asm volatile("{ .reg .pred p, q; setp.ne.u32 q, %3, 0; setp.ne.xor.f32 p, %1, %2, q; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 31: asm volatile("{ .reg .pred p, q, r; setp.ne.u32 r, %3, 0; setp.ne.xor.f32 p|q, %1, %2, !r; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 32: asm volatile("{ .reg .pred p, q; setp.ne.u32 q, %3, 0; setp.gtu.xor.f32 p, %1, %2, q; selp.u32 %0, 1, 0, p; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 33: asm volatile("{ .reg .pred p, q, r; setp.ne.u32 r, %3, 0; setp.gtu.xor.f32 p|q, %1, %2, !r; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 34: asm volatile("{ .reg .pred r; setp.ne.u32 r, %3, 0; set.lt.xor.u32.s32 %0, %1, %2, r; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 35: asm volatile("{ .reg .pred r; setp.ne.u32 r, %3, 0; set.le.xor.f32.f32 %0, %1, %2, !r; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 36: asm volatile("{ .reg .pred p, q; setp.lt.u32 p|q, %1, %2; selp.u32 %0, 1, 2, p; selp.u32 %0, %0, 4, q; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 37: asm volatile("mul24.lo.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 38: asm volatile("mul24.lo.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 39: asm volatile("mul24.hi.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 40: asm volatile("mul24.hi.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 41: asm volatile("mad24.lo.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 42: asm volatile("mad24.lo.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 43: asm volatile("mad24.hi.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 44: asm volatile("mad24.hi.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 45: asm volatile("mad24.hi.sat.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 46: asm volatile("add.sat.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 47: asm volatile("sub.sat.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 48: asm volatile("mad.hi.sat.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 49: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; fma.rn.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 50: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; fma.rn.sat.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 51: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; fma.rn.ftz.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 52: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mad.rn.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 53: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; add.rn.sat.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 54: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mul.rn.sat.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 55: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; fma.rz.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 56: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; fma.rz.sat.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 57: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; fma.rz.ftz.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 58: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mad.rz.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 59: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; add.rz.sat.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 60: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mul.rz.sat.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 61: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; fma.rm.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 62: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; fma.rm.sat.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 63: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; fma.rm.ftz.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 64: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mad.rm.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 65: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; add.rm.sat.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 66: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mul.rm.sat.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 67: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; fma.rp.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 68: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; fma.rp.sat.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 69: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; fma.rp.ftz.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 70: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mad.rp.f32 a, a, b, c; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 71: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; add.rp.sat.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 72: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; mul.rp.sat.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 73: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; sub.sat.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 74: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rz.f64 a, a, b, c; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 75: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rz.f64 a, a, b, c; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 76: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rm.f64 a, a, b, c; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 77: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rm.f64 a, a, b, c; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 78: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rp.f64 a, a, b, c; mov.b64 {%0, _}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 79: asm volatile("{ .reg .f64 a,b,c; mov.b64 a, {%1, %2}; mov.b64 b, {%2, %3}; mov.b64 c, {%3, %1}; fma.rp.f64 a, a, b, c; mov.b64 {_, %0}, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 80: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; min.xorsign.abs.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 81: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; min.NaN.xorsign.abs.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 82: asm volatile("min.xorsign.abs.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 83: asm volatile("min.NaN.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 84: asm volatile("min.NaN.xorsign.abs.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 85: asm volatile("min.xorsign.abs.bf16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 86: asm volatile("min.NaN.bf16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 87: asm volatile("min.NaN.xorsign.abs.bf16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 88: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; max.xorsign.abs.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 89: asm volatile("{ .reg .f32 a,b,c; mov.b32 a, %1; mov.b32 b, %2; mov.b32 c, %3; max.NaN.xorsign.abs.f32 a, a, b; mov.b32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 90: asm volatile("max.xorsign.abs.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 91: asm volatile("max.NaN.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 92: asm volatile("max.NaN.xorsign.abs.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 93: asm volatile("max.xorsign.abs.bf16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 94: asm volatile("max.NaN.bf16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 95: asm volatile("max.NaN.xorsign.abs.bf16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 96: asm volatile("add.sat.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 97: asm volatile("add.ftz.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 98: asm volatile("add.ftz.sat.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 99: asm volatile("sub.sat.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 100: asm volatile("sub.ftz.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 101: asm volatile("sub.ftz.sat.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 102: asm volatile("mul.sat.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 103: asm volatile("mul.ftz.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 104: asm volatile("mul.ftz.sat.f16x2 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 105: asm volatile("fma.rn.sat.f16x2 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 106: asm volatile("fma.rn.ftz.f16x2 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 107: asm volatile("fma.rn.relu.f16x2 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 108: asm volatile("fma.rn.ftz.sat.f16x2 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 109: asm volatile("fma.rn.ftz.relu.f16x2 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 110: asm volatile("fma.rn.relu.bf16x2 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 111: asm volatile("{ .reg .f32 a,b; mov.b32 a, %1; mov.b32 b, %2; cvt.rn.f16x2.f32 %0, a, b; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 112: asm volatile("{ .reg .f32 a,b; mov.b32 a, %1; mov.b32 b, %2; cvt.rz.f16x2.f32 %0, a, b; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 113: asm volatile("{ .reg .f32 a,b; mov.b32 a, %1; mov.b32 b, %2; cvt.rn.relu.f16x2.f32 %0, a, b; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 114: asm volatile("{ .reg .f32 a,b; mov.b32 a, %1; mov.b32 b, %2; cvt.rz.relu.f16x2.f32 %0, a, b; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 115: asm volatile("{ .reg .f32 a,b; mov.b32 a, %1; mov.b32 b, %2; cvt.rn.satfinite.f16x2.f32 %0, a, b; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 116: asm volatile("{ .reg .f32 a,b; mov.b32 a, %1; mov.b32 b, %2; cvt.rz.relu.satfinite.f16x2.f32 %0, a, b; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 117: asm volatile("{ .reg .f32 a,b; mov.b32 a, %1; mov.b32 b, %2; cvt.rn.bf16x2.f32 %0, a, b; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 118: asm volatile("{ .reg .f32 a,b; mov.b32 a, %1; mov.b32 b, %2; cvt.rz.bf16x2.f32 %0, a, b; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 119: asm volatile("{ .reg .f32 a,b; mov.b32 a, %1; mov.b32 b, %2; cvt.rn.relu.bf16x2.f32 %0, a, b; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 120: asm volatile("{ .reg .f32 a,b; mov.b32 a, %1; mov.b32 b, %2; cvt.rz.relu.bf16x2.f32 %0, a, b; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 121: asm volatile("{ .reg .f32 a,b; mov.b32 a, %1; mov.b32 b, %2; cvt.rn.satfinite.bf16x2.f32 %0, a, b; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 122: asm volatile("{ .reg .f32 a,b; mov.b32 a, %1; mov.b32 b, %2; cvt.rz.relu.satfinite.bf16x2.f32 %0, a, b; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 123: asm volatile("{ .reg .f32 a; .reg .b16 h; mov.b32 a, %1; cvt.rn.relu.f16.f32 h, a; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 124: asm volatile("{ .reg .f32 a; .reg .b16 h; mov.b32 a, %1; cvt.rn.relu.bf16.f32 h, a; mov.b32 %0, {h, h}; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 125: asm volatile("{ .reg .f32 a; mov.b32 a, %1; cvt.rna.tf32.f32 %0, a; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 126: asm volatile("{ .reg .f16x2 h; mov.b32 h, %1; mov.b32 %0, h; }" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
  }
  out[i] = d;
}
static const char* kTags[] = {
  "prmt.f4e",
  "prmt.b4e",
  "prmt.rc8",
  "prmt.ecl",
  "prmt.ecr",
  "prmt.rc16",
  "setp.lt.and.u32 p",
  "setp.lt.and.u32 p|q !c",
  "setp.ge.and.s32 p",
  "setp.ge.and.s32 p|q !c",
  "setp.ne.and.f32 p",
  "setp.ne.and.f32 p|q !c",
  "setp.gtu.and.f32 p",
  "setp.gtu.and.f32 p|q !c",
  "set.lt.and.u32.s32",
  "set.le.and.f32.f32",
  "setp.lt.or.u32 p",
  "setp.lt.or.u32 p|q !c",
  "setp.ge.or.s32 p",
  "setp.ge.or.s32 p|q !c",
  "setp.ne.or.f32 p",
  "setp.ne.or.f32 p|q !c",
  "setp.gtu.or.f32 p",
  "setp.gtu.or.f32 p|q !c",
  "set.lt.or.u32.s32",
  "set.le.or.f32.f32",
  "setp.lt.xor.u32 p",
  "setp.lt.xor.u32 p|q !c",
  "setp.ge.xor.s32 p",
  "setp.ge.xor.s32 p|q !c",
  "setp.ne.xor.f32 p",
  "setp.ne.xor.f32 p|q !c",
  "setp.gtu.xor.f32 p",
  "setp.gtu.xor.f32 p|q !c",
  "set.lt.xor.u32.s32",
  "set.le.xor.f32.f32",
  "setp.lt.u32 p|q",
  "mul24.lo.u32",
  "mul24.lo.s32",
  "mul24.hi.u32",
  "mul24.hi.s32",
  "mad24.lo.u32",
  "mad24.lo.s32",
  "mad24.hi.u32",
  "mad24.hi.s32",
  "mad24.hi.sat.s32",
  "add.sat.s32",
  "sub.sat.s32",
  "mad.hi.sat.s32",
  "fma.rn.f32",
  "fma.rn.sat.f32",
  "fma.rn.ftz.f32",
  "mad.rn.f32",
  "add.rn.sat.f32",
  "mul.rn.sat.f32",
  "fma.rz.f32",
  "fma.rz.sat.f32",
  "fma.rz.ftz.f32",
  "mad.rz.f32",
  "add.rz.sat.f32",
  "mul.rz.sat.f32",
  "fma.rm.f32",
  "fma.rm.sat.f32",
  "fma.rm.ftz.f32",
  "mad.rm.f32",
  "add.rm.sat.f32",
  "mul.rm.sat.f32",
  "fma.rp.f32",
  "fma.rp.sat.f32",
  "fma.rp.ftz.f32",
  "mad.rp.f32",
  "add.rp.sat.f32",
  "mul.rp.sat.f32",
  "sub.sat.f32",
  "fma.rz.f64 lo",
  "fma.rz.f64 hi",
  "fma.rm.f64 lo",
  "fma.rm.f64 hi",
  "fma.rp.f64 lo",
  "fma.rp.f64 hi",
  "min.xorsign.abs.f32",
  "min.NaN.xorsign.abs.f32",
  "min.xorsign.abs.f16x2",
  "min.NaN.f16x2",
  "min.NaN.xorsign.abs.f16x2",
  "min.xorsign.abs.bf16x2",
  "min.NaN.bf16x2",
  "min.NaN.xorsign.abs.bf16x2",
  "max.xorsign.abs.f32",
  "max.NaN.xorsign.abs.f32",
  "max.xorsign.abs.f16x2",
  "max.NaN.f16x2",
  "max.NaN.xorsign.abs.f16x2",
  "max.xorsign.abs.bf16x2",
  "max.NaN.bf16x2",
  "max.NaN.xorsign.abs.bf16x2",
  "add.sat.f16x2",
  "add.ftz.f16x2",
  "add.ftz.sat.f16x2",
  "sub.sat.f16x2",
  "sub.ftz.f16x2",
  "sub.ftz.sat.f16x2",
  "mul.sat.f16x2",
  "mul.ftz.f16x2",
  "mul.ftz.sat.f16x2",
  "fma.rn.sat.f16x2",
  "fma.rn.ftz.f16x2",
  "fma.rn.relu.f16x2",
  "fma.rn.ftz.sat.f16x2",
  "fma.rn.ftz.relu.f16x2",
  "fma.rn.relu.bf16x2",
  "cvt.rn.f16x2.f32",
  "cvt.rz.f16x2.f32",
  "cvt.rn.relu.f16x2.f32",
  "cvt.rz.relu.f16x2.f32",
  "cvt.rn.satfinite.f16x2.f32",
  "cvt.rz.relu.satfinite.f16x2.f32",
  "cvt.rn.bf16x2.f32",
  "cvt.rz.bf16x2.f32",
  "cvt.rn.relu.bf16x2.f32",
  "cvt.rz.relu.bf16x2.f32",
  "cvt.rn.satfinite.bf16x2.f32",
  "cvt.rz.relu.satfinite.bf16x2.f32",
  "cvt.rn.relu.f16.f32",
  "cvt.rn.relu.bf16.f32",
  "cvt.rna.tf32.f32",
  "mov.b32 f16x2",
};
int main(int argc, char** argv) {
  const bool print = argc > 1 && std::strcmp(argv[1], "--print") == 0;
  const int dump = argc > 2 && std::strcmp(argv[1], "--dump") == 0 ? atoi(argv[2]) : -1;
  const int nv = sizeof kTags / sizeof kTags[0];
  // Random bits, and values that exercise the modifiers: f32 and packed-half
  // edges (+-0, +-1, NaN, subnormals, near-overflow, near-1, rounding ties).
  static const unsigned edge[] = {
      0x00000000u, 0x80000000u, 0x3f800000u, 0xbf800000u, 0x7fc00000u, 0xff800001u, 0x00000001u, 0x007fffffu,
      0x7f7fffffu, 0x3f7fffffu, 0x3f800001u, 0x3f801000u, 0x3dcccccdu, 0x40000000u, 0xc0400000u, 0x7f800000u,
      0x3c00bc00u, 0x7e003c00u, 0x00010002u, 0x7bff7c00u, 0x3bff3c01u, 0x80000000u, 0x3f80bf80u, 0x7fc0ff80u,
      0x12345678u, 0x9abcdef0u, 0x007fffffu, 0x7fffffffu, 0x00800000u, 0xffffffffu, 0x0f1e2d3cu, 0x00000003u};
  unsigned h[3 * kN];
  unsigned long long s = 0x9E3779B97F4A7C15ull;
  for (int i = 0; i < 3 * kN; ++i) {
    s ^= s << 13; s ^= s >> 7; s ^= s << 17;
    h[i] = static_cast<unsigned>(s);
    if ((s >> 40) % 3 == 0) h[i] = edge[(s >> 48) % 32];
  }
  unsigned *din, *dout;
  cudaMalloc(&din, sizeof h);
  cudaMalloc(&dout, kN * 4);
  cudaMemcpy(din, h, sizeof h, cudaMemcpyHostToDevice);
  int bad = 0;
  for (int v = 0; v < nv; ++v) {
    k<<<1, kN>>>(v, din, dout);
    if (cudaDeviceSynchronize() != cudaSuccess) { printf("variant %d (%s) failed to run\n", v, kTags[v]); return 1; }
    unsigned o[kN];
    cudaMemcpy(o, dout, sizeof o, cudaMemcpyDeviceToHost);
    unsigned long long hash = 1469598103934665603ull;
    for (unsigned x : o) { hash ^= x; hash *= 1099511628211ull; }
    if (v == dump) {
      for (int i = 0; i < kN; ++i) printf("%3d a=%08x b=%08x c=%08x d=%08x\n", i, h[3 * i], h[3 * i + 1], h[3 * i + 2], o[i]);
      return 0;
    }
    if (print) { printf("    {\"%s\", 0x%016llxull},\n", kTags[v], hash); continue; }
    if (dump >= 0) continue;
    if (v >= (int)(sizeof kExpected / sizeof kExpected[0]) || hash != kExpected[v].hash) {
      if (bad++ < 40) printf("%s: 0x%016llx, the card gave 0x%016llx\n", kTags[v], hash,
                             v < (int)(sizeof kExpected / sizeof kExpected[0]) ? kExpected[v].hash : 0ull);
    }
  }
  if (print) return 0;
  const int ne = sizeof kExpected / sizeof kExpected[0];
  printf("%d PTX forms, %d differ\n%s\n", nv, bad, bad || ne != nv ? "FAIL" : "PASS");
  return bad ? 1 : 0;
}
