// Every video instruction (PTX ISA 9.7.20) in a spread of types, operand
// selectors, saturation, secondary operations, merges and masks, run over the
// same 256 operand triples, each variant's results hashed and compared with an
// RTX 3060's (sm_86), recorded in video_forms_expected.inc (`video_forms
// --print` prints them). Generated by video_forms_gen.py.
// Prints PASS on the last line, and runs the same on a GPU.
#include <cstdio>
#include <cstdlib>
#include <cstring>
struct Expected { const char* tag; unsigned long long hash; };
static const Expected kExpected[] = {
#include "video_forms_expected.inc"
};
constexpr int kN = 256;
__global__ void k(int v, const unsigned* in, unsigned* out) {
  const int i = threadIdx.x;
  const unsigned a = in[3 * i], b = in[3 * i + 1], c = in[3 * i + 2];
  unsigned d = 0;
  switch (v) {
    case 0: asm volatile("vadd.u32.u32.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 1: asm volatile("vadd.u32.u32.u32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 2: asm volatile("vadd.u32.u32.u32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 3: asm volatile("vadd.u32.u32.u32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 4: asm volatile("vadd.u32.u32.u32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 5: asm volatile("vadd.u32.u32.u32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 6: asm volatile("vadd.u32.u32.u32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 7: asm volatile("vadd.u32.u32.u32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 8: asm volatile("vadd.u32.u32.u32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 9: asm volatile("vadd.u32.u32.u32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 10: asm volatile("vadd.u32.u32.u32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 11: asm volatile("vadd.u32.u32.u32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 12: asm volatile("vadd.u32.u32.u32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 13: asm volatile("vadd.u32.u32.u32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 14: asm volatile("vadd.s32.s32.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 15: asm volatile("vadd.s32.s32.s32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 16: asm volatile("vadd.s32.s32.s32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 17: asm volatile("vadd.s32.s32.s32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 18: asm volatile("vadd.s32.s32.s32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 19: asm volatile("vadd.s32.s32.s32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 20: asm volatile("vadd.s32.s32.s32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 21: asm volatile("vadd.s32.s32.s32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 22: asm volatile("vadd.s32.s32.s32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 23: asm volatile("vadd.s32.s32.s32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 24: asm volatile("vadd.s32.s32.s32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 25: asm volatile("vadd.s32.s32.s32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 26: asm volatile("vadd.s32.s32.s32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 27: asm volatile("vadd.s32.s32.s32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 28: asm volatile("vadd.s32.u32.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 29: asm volatile("vadd.s32.u32.s32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 30: asm volatile("vadd.s32.u32.s32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 31: asm volatile("vadd.s32.u32.s32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 32: asm volatile("vadd.s32.u32.s32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 33: asm volatile("vadd.s32.u32.s32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 34: asm volatile("vadd.s32.u32.s32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 35: asm volatile("vadd.s32.u32.s32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 36: asm volatile("vadd.s32.u32.s32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 37: asm volatile("vadd.s32.u32.s32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 38: asm volatile("vadd.s32.u32.s32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 39: asm volatile("vadd.s32.u32.s32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 40: asm volatile("vadd.s32.u32.s32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 41: asm volatile("vadd.s32.u32.s32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 42: asm volatile("vadd.u32.s32.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 43: asm volatile("vadd.u32.s32.u32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 44: asm volatile("vadd.u32.s32.u32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 45: asm volatile("vadd.u32.s32.u32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 46: asm volatile("vadd.u32.s32.u32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 47: asm volatile("vadd.u32.s32.u32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 48: asm volatile("vadd.u32.s32.u32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 49: asm volatile("vadd.u32.s32.u32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 50: asm volatile("vadd.u32.s32.u32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 51: asm volatile("vadd.u32.s32.u32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 52: asm volatile("vadd.u32.s32.u32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 53: asm volatile("vadd.u32.s32.u32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 54: asm volatile("vadd.u32.s32.u32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 55: asm volatile("vadd.u32.s32.u32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 56: asm volatile("vsub.u32.u32.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 57: asm volatile("vsub.u32.u32.u32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 58: asm volatile("vsub.u32.u32.u32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 59: asm volatile("vsub.u32.u32.u32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 60: asm volatile("vsub.u32.u32.u32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 61: asm volatile("vsub.u32.u32.u32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 62: asm volatile("vsub.u32.u32.u32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 63: asm volatile("vsub.u32.u32.u32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 64: asm volatile("vsub.u32.u32.u32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 65: asm volatile("vsub.u32.u32.u32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 66: asm volatile("vsub.u32.u32.u32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 67: asm volatile("vsub.u32.u32.u32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 68: asm volatile("vsub.u32.u32.u32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 69: asm volatile("vsub.u32.u32.u32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 70: asm volatile("vsub.s32.s32.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 71: asm volatile("vsub.s32.s32.s32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 72: asm volatile("vsub.s32.s32.s32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 73: asm volatile("vsub.s32.s32.s32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 74: asm volatile("vsub.s32.s32.s32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 75: asm volatile("vsub.s32.s32.s32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 76: asm volatile("vsub.s32.s32.s32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 77: asm volatile("vsub.s32.s32.s32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 78: asm volatile("vsub.s32.s32.s32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 79: asm volatile("vsub.s32.s32.s32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 80: asm volatile("vsub.s32.s32.s32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 81: asm volatile("vsub.s32.s32.s32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 82: asm volatile("vsub.s32.s32.s32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 83: asm volatile("vsub.s32.s32.s32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 84: asm volatile("vsub.s32.u32.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 85: asm volatile("vsub.s32.u32.s32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 86: asm volatile("vsub.s32.u32.s32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 87: asm volatile("vsub.s32.u32.s32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 88: asm volatile("vsub.s32.u32.s32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 89: asm volatile("vsub.s32.u32.s32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 90: asm volatile("vsub.s32.u32.s32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 91: asm volatile("vsub.s32.u32.s32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 92: asm volatile("vsub.s32.u32.s32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 93: asm volatile("vsub.s32.u32.s32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 94: asm volatile("vsub.s32.u32.s32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 95: asm volatile("vsub.s32.u32.s32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 96: asm volatile("vsub.s32.u32.s32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 97: asm volatile("vsub.s32.u32.s32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 98: asm volatile("vsub.u32.s32.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 99: asm volatile("vsub.u32.s32.u32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 100: asm volatile("vsub.u32.s32.u32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 101: asm volatile("vsub.u32.s32.u32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 102: asm volatile("vsub.u32.s32.u32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 103: asm volatile("vsub.u32.s32.u32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 104: asm volatile("vsub.u32.s32.u32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 105: asm volatile("vsub.u32.s32.u32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 106: asm volatile("vsub.u32.s32.u32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 107: asm volatile("vsub.u32.s32.u32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 108: asm volatile("vsub.u32.s32.u32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 109: asm volatile("vsub.u32.s32.u32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 110: asm volatile("vsub.u32.s32.u32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 111: asm volatile("vsub.u32.s32.u32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 112: asm volatile("vabsdiff.u32.u32.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 113: asm volatile("vabsdiff.u32.u32.u32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 114: asm volatile("vabsdiff.u32.u32.u32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 115: asm volatile("vabsdiff.u32.u32.u32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 116: asm volatile("vabsdiff.u32.u32.u32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 117: asm volatile("vabsdiff.u32.u32.u32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 118: asm volatile("vabsdiff.u32.u32.u32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 119: asm volatile("vabsdiff.u32.u32.u32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 120: asm volatile("vabsdiff.u32.u32.u32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 121: asm volatile("vabsdiff.u32.u32.u32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 122: asm volatile("vabsdiff.u32.u32.u32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 123: asm volatile("vabsdiff.u32.u32.u32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 124: asm volatile("vabsdiff.u32.u32.u32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 125: asm volatile("vabsdiff.u32.u32.u32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 126: asm volatile("vabsdiff.s32.s32.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 127: asm volatile("vabsdiff.s32.s32.s32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 128: asm volatile("vabsdiff.s32.s32.s32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 129: asm volatile("vabsdiff.s32.s32.s32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 130: asm volatile("vabsdiff.s32.s32.s32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 131: asm volatile("vabsdiff.s32.s32.s32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 132: asm volatile("vabsdiff.s32.s32.s32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 133: asm volatile("vabsdiff.s32.s32.s32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 134: asm volatile("vabsdiff.s32.s32.s32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 135: asm volatile("vabsdiff.s32.s32.s32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 136: asm volatile("vabsdiff.s32.s32.s32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 137: asm volatile("vabsdiff.s32.s32.s32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 138: asm volatile("vabsdiff.s32.s32.s32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 139: asm volatile("vabsdiff.s32.s32.s32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 140: asm volatile("vabsdiff.s32.u32.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 141: asm volatile("vabsdiff.s32.u32.s32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 142: asm volatile("vabsdiff.s32.u32.s32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 143: asm volatile("vabsdiff.s32.u32.s32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 144: asm volatile("vabsdiff.s32.u32.s32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 145: asm volatile("vabsdiff.s32.u32.s32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 146: asm volatile("vabsdiff.s32.u32.s32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 147: asm volatile("vabsdiff.s32.u32.s32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 148: asm volatile("vabsdiff.s32.u32.s32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 149: asm volatile("vabsdiff.s32.u32.s32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 150: asm volatile("vabsdiff.s32.u32.s32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 151: asm volatile("vabsdiff.s32.u32.s32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 152: asm volatile("vabsdiff.s32.u32.s32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 153: asm volatile("vabsdiff.s32.u32.s32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 154: asm volatile("vabsdiff.u32.s32.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 155: asm volatile("vabsdiff.u32.s32.u32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 156: asm volatile("vabsdiff.u32.s32.u32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 157: asm volatile("vabsdiff.u32.s32.u32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 158: asm volatile("vabsdiff.u32.s32.u32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 159: asm volatile("vabsdiff.u32.s32.u32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 160: asm volatile("vabsdiff.u32.s32.u32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 161: asm volatile("vabsdiff.u32.s32.u32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 162: asm volatile("vabsdiff.u32.s32.u32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 163: asm volatile("vabsdiff.u32.s32.u32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 164: asm volatile("vabsdiff.u32.s32.u32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 165: asm volatile("vabsdiff.u32.s32.u32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 166: asm volatile("vabsdiff.u32.s32.u32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 167: asm volatile("vabsdiff.u32.s32.u32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 168: asm volatile("vmin.u32.u32.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 169: asm volatile("vmin.u32.u32.u32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 170: asm volatile("vmin.u32.u32.u32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 171: asm volatile("vmin.u32.u32.u32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 172: asm volatile("vmin.u32.u32.u32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 173: asm volatile("vmin.u32.u32.u32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 174: asm volatile("vmin.u32.u32.u32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 175: asm volatile("vmin.u32.u32.u32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 176: asm volatile("vmin.u32.u32.u32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 177: asm volatile("vmin.u32.u32.u32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 178: asm volatile("vmin.u32.u32.u32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 179: asm volatile("vmin.u32.u32.u32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 180: asm volatile("vmin.u32.u32.u32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 181: asm volatile("vmin.u32.u32.u32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 182: asm volatile("vmin.s32.s32.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 183: asm volatile("vmin.s32.s32.s32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 184: asm volatile("vmin.s32.s32.s32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 185: asm volatile("vmin.s32.s32.s32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 186: asm volatile("vmin.s32.s32.s32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 187: asm volatile("vmin.s32.s32.s32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 188: asm volatile("vmin.s32.s32.s32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 189: asm volatile("vmin.s32.s32.s32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 190: asm volatile("vmin.s32.s32.s32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 191: asm volatile("vmin.s32.s32.s32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 192: asm volatile("vmin.s32.s32.s32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 193: asm volatile("vmin.s32.s32.s32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 194: asm volatile("vmin.s32.s32.s32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 195: asm volatile("vmin.s32.s32.s32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 196: asm volatile("vmin.s32.u32.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 197: asm volatile("vmin.s32.u32.s32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 198: asm volatile("vmin.s32.u32.s32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 199: asm volatile("vmin.s32.u32.s32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 200: asm volatile("vmin.s32.u32.s32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 201: asm volatile("vmin.s32.u32.s32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 202: asm volatile("vmin.s32.u32.s32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 203: asm volatile("vmin.s32.u32.s32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 204: asm volatile("vmin.s32.u32.s32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 205: asm volatile("vmin.s32.u32.s32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 206: asm volatile("vmin.s32.u32.s32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 207: asm volatile("vmin.s32.u32.s32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 208: asm volatile("vmin.s32.u32.s32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 209: asm volatile("vmin.s32.u32.s32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 210: asm volatile("vmin.u32.s32.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 211: asm volatile("vmin.u32.s32.u32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 212: asm volatile("vmin.u32.s32.u32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 213: asm volatile("vmin.u32.s32.u32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 214: asm volatile("vmin.u32.s32.u32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 215: asm volatile("vmin.u32.s32.u32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 216: asm volatile("vmin.u32.s32.u32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 217: asm volatile("vmin.u32.s32.u32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 218: asm volatile("vmin.u32.s32.u32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 219: asm volatile("vmin.u32.s32.u32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 220: asm volatile("vmin.u32.s32.u32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 221: asm volatile("vmin.u32.s32.u32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 222: asm volatile("vmin.u32.s32.u32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 223: asm volatile("vmin.u32.s32.u32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 224: asm volatile("vmax.u32.u32.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 225: asm volatile("vmax.u32.u32.u32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 226: asm volatile("vmax.u32.u32.u32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 227: asm volatile("vmax.u32.u32.u32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 228: asm volatile("vmax.u32.u32.u32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 229: asm volatile("vmax.u32.u32.u32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 230: asm volatile("vmax.u32.u32.u32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 231: asm volatile("vmax.u32.u32.u32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 232: asm volatile("vmax.u32.u32.u32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 233: asm volatile("vmax.u32.u32.u32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 234: asm volatile("vmax.u32.u32.u32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 235: asm volatile("vmax.u32.u32.u32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 236: asm volatile("vmax.u32.u32.u32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 237: asm volatile("vmax.u32.u32.u32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 238: asm volatile("vmax.s32.s32.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 239: asm volatile("vmax.s32.s32.s32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 240: asm volatile("vmax.s32.s32.s32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 241: asm volatile("vmax.s32.s32.s32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 242: asm volatile("vmax.s32.s32.s32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 243: asm volatile("vmax.s32.s32.s32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 244: asm volatile("vmax.s32.s32.s32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 245: asm volatile("vmax.s32.s32.s32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 246: asm volatile("vmax.s32.s32.s32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 247: asm volatile("vmax.s32.s32.s32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 248: asm volatile("vmax.s32.s32.s32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 249: asm volatile("vmax.s32.s32.s32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 250: asm volatile("vmax.s32.s32.s32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 251: asm volatile("vmax.s32.s32.s32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 252: asm volatile("vmax.s32.u32.s32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 253: asm volatile("vmax.s32.u32.s32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 254: asm volatile("vmax.s32.u32.s32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 255: asm volatile("vmax.s32.u32.s32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 256: asm volatile("vmax.s32.u32.s32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 257: asm volatile("vmax.s32.u32.s32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 258: asm volatile("vmax.s32.u32.s32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 259: asm volatile("vmax.s32.u32.s32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 260: asm volatile("vmax.s32.u32.s32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 261: asm volatile("vmax.s32.u32.s32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 262: asm volatile("vmax.s32.u32.s32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 263: asm volatile("vmax.s32.u32.s32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 264: asm volatile("vmax.s32.u32.s32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 265: asm volatile("vmax.s32.u32.s32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 266: asm volatile("vmax.u32.s32.u32 %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 267: asm volatile("vmax.u32.s32.u32 %0, %1.b1, %2.h1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 268: asm volatile("vmax.u32.s32.u32 %0, %1.h0, %2.b3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 269: asm volatile("vmax.u32.s32.u32.sat %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 270: asm volatile("vmax.u32.s32.u32.add %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 271: asm volatile("vmax.u32.s32.u32.min %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 272: asm volatile("vmax.u32.s32.u32.max %0, %1.b2, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 273: asm volatile("vmax.u32.s32.u32.sat.add %0, %1, %2.h0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 274: asm volatile("vmax.u32.s32.u32 %0.b0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 275: asm volatile("vmax.u32.s32.u32.sat %0.b0, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 276: asm volatile("vmax.u32.s32.u32 %0.b3, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 277: asm volatile("vmax.u32.s32.u32.sat %0.b3, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 278: asm volatile("vmax.u32.s32.u32 %0.h1, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 279: asm volatile("vmax.u32.s32.u32.sat %0.h1, %1.h1, %2.b0, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 280: asm volatile("vadd.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 281: asm volatile("vadd.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 282: asm volatile("vabsdiff.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 283: asm volatile("vabsdiff.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 284: asm volatile("vmin.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 285: asm volatile("vmin.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 286: asm volatile("vshl.u32.u32.u32.clamp %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 287: asm volatile("vshl.u32.u32.u32.clamp %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 288: asm volatile("vshl.u32.u32.u32.wrap %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 289: asm volatile("vshl.u32.u32.u32.wrap %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 290: asm volatile("vshl.u32.u32.u32.sat.clamp %0, %1, %2.b1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 291: asm volatile("vshl.u32.u32.u32.clamp.add %0, %1, %2.b2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 292: asm volatile("vshl.u32.u32.u32.wrap %0.h0, %1, %2.b3, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 293: asm volatile("vshl.s32.s32.u32.clamp %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 294: asm volatile("vshl.s32.s32.u32.clamp %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 295: asm volatile("vshl.s32.s32.u32.wrap %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 296: asm volatile("vshl.s32.s32.u32.wrap %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 297: asm volatile("vshl.s32.s32.u32.sat.clamp %0, %1, %2.b1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 298: asm volatile("vshl.s32.s32.u32.clamp.add %0, %1, %2.b2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 299: asm volatile("vshl.s32.s32.u32.wrap %0.h0, %1, %2.b3, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 300: asm volatile("vshl.s32.u32.u32.clamp %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 301: asm volatile("vshl.s32.u32.u32.clamp %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 302: asm volatile("vshl.s32.u32.u32.wrap %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 303: asm volatile("vshl.s32.u32.u32.wrap %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 304: asm volatile("vshl.s32.u32.u32.sat.clamp %0, %1, %2.b1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 305: asm volatile("vshl.s32.u32.u32.clamp.add %0, %1, %2.b2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 306: asm volatile("vshl.s32.u32.u32.wrap %0.h0, %1, %2.b3, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 307: asm volatile("vshl.u32.s32.u32.clamp %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 308: asm volatile("vshl.u32.s32.u32.clamp %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 309: asm volatile("vshl.u32.s32.u32.wrap %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 310: asm volatile("vshl.u32.s32.u32.wrap %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 311: asm volatile("vshl.u32.s32.u32.sat.clamp %0, %1, %2.b1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 312: asm volatile("vshl.u32.s32.u32.clamp.add %0, %1, %2.b2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 313: asm volatile("vshl.u32.s32.u32.wrap %0.h0, %1, %2.b3, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 314: asm volatile("vshr.u32.u32.u32.clamp %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 315: asm volatile("vshr.u32.u32.u32.clamp %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 316: asm volatile("vshr.u32.u32.u32.wrap %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 317: asm volatile("vshr.u32.u32.u32.wrap %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 318: asm volatile("vshr.u32.u32.u32.sat.clamp %0, %1, %2.b1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 319: asm volatile("vshr.u32.u32.u32.clamp.add %0, %1, %2.b2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 320: asm volatile("vshr.u32.u32.u32.wrap %0.h0, %1, %2.b3, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 321: asm volatile("vshr.s32.s32.u32.clamp %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 322: asm volatile("vshr.s32.s32.u32.clamp %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 323: asm volatile("vshr.s32.s32.u32.wrap %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 324: asm volatile("vshr.s32.s32.u32.wrap %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 325: asm volatile("vshr.s32.s32.u32.sat.clamp %0, %1, %2.b1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 326: asm volatile("vshr.s32.s32.u32.clamp.add %0, %1, %2.b2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 327: asm volatile("vshr.s32.s32.u32.wrap %0.h0, %1, %2.b3, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 328: asm volatile("vshr.s32.u32.u32.clamp %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 329: asm volatile("vshr.s32.u32.u32.clamp %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 330: asm volatile("vshr.s32.u32.u32.wrap %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 331: asm volatile("vshr.s32.u32.u32.wrap %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 332: asm volatile("vshr.s32.u32.u32.sat.clamp %0, %1, %2.b1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 333: asm volatile("vshr.s32.u32.u32.clamp.add %0, %1, %2.b2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 334: asm volatile("vshr.s32.u32.u32.wrap %0.h0, %1, %2.b3, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 335: asm volatile("vshr.u32.s32.u32.clamp %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 336: asm volatile("vshr.u32.s32.u32.clamp %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 337: asm volatile("vshr.u32.s32.u32.wrap %0, %1, %2;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 338: asm volatile("vshr.u32.s32.u32.wrap %0, %1.h1, %2.b0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 339: asm volatile("vshr.u32.s32.u32.sat.clamp %0, %1, %2.b1;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 340: asm volatile("vshr.u32.s32.u32.clamp.add %0, %1, %2.b2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 341: asm volatile("vshr.u32.s32.u32.wrap %0.h0, %1, %2.b3, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 342: asm volatile("vmad.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 343: asm volatile("vmad.u32.u32.u32 %0, %1.h1, %2.b2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 344: asm volatile("vmad.u32.u32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 345: asm volatile("vmad.u32.u32.u32.shr7 %0, %1.h0, %2.h1, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 346: asm volatile("vmad.u32.u32.u32.sat.shr15 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 347: asm volatile("vmad.u32.u32.u32.po %0, %1.b1, %2.b3, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 348: asm volatile("vmad.u32.u32.u32.po.sat.shr7 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 349: asm volatile("vmad.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 350: asm volatile("vmad.s32.s32.s32 %0, %1.h1, %2.b2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 351: asm volatile("vmad.s32.s32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 352: asm volatile("vmad.s32.s32.s32.shr7 %0, %1.h0, %2.h1, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 353: asm volatile("vmad.s32.s32.s32.sat.shr15 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 354: asm volatile("vmad.s32.s32.s32.po %0, %1.b1, %2.b3, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 355: asm volatile("vmad.s32.s32.s32.po.sat.shr7 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 356: asm volatile("vmad.s32.s32.s32 %0, -%1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 357: asm volatile("vmad.s32.s32.s32 %0, %1, %2, -%3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 358: asm volatile("vmad.s32.s32.s32.sat %0, %1.h0, -%2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 359: asm volatile("vmad.s32.u32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 360: asm volatile("vmad.s32.u32.s32 %0, %1.h1, %2.b2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 361: asm volatile("vmad.s32.u32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 362: asm volatile("vmad.s32.u32.s32.shr7 %0, %1.h0, %2.h1, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 363: asm volatile("vmad.s32.u32.s32.sat.shr15 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 364: asm volatile("vmad.s32.u32.s32.po %0, %1.b1, %2.b3, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 365: asm volatile("vmad.s32.u32.s32.po.sat.shr7 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 366: asm volatile("vmad.s32.u32.s32 %0, -%1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 367: asm volatile("vmad.s32.u32.s32 %0, %1, %2, -%3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 368: asm volatile("vmad.s32.u32.s32.sat %0, %1.h0, -%2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 369: asm volatile("vmad.s32.s32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 370: asm volatile("vmad.s32.s32.u32 %0, %1.h1, %2.b2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 371: asm volatile("vmad.s32.s32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 372: asm volatile("vmad.s32.s32.u32.shr7 %0, %1.h0, %2.h1, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 373: asm volatile("vmad.s32.s32.u32.sat.shr15 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 374: asm volatile("vmad.s32.s32.u32.po %0, %1.b1, %2.b3, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 375: asm volatile("vmad.s32.s32.u32.po.sat.shr7 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 376: asm volatile("vmad.s32.s32.u32 %0, -%1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 377: asm volatile("vmad.s32.s32.u32 %0, %1, %2, -%3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 378: asm volatile("vmad.s32.s32.u32.sat %0, %1.h0, -%2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 379: asm volatile("vset.u32.u32.eq %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 380: asm volatile("vset.u32.u32.ne %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 381: asm volatile("vset.u32.u32.lt %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 382: asm volatile("vset.u32.u32.le %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 383: asm volatile("vset.u32.u32.gt %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 384: asm volatile("vset.u32.u32.ge %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 385: asm volatile("vset.u32.u32.lt.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 386: asm volatile("vset.u32.u32.ge.max %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 387: asm volatile("vset.u32.u32.ne %0.b2, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 388: asm volatile("vset.s32.s32.eq %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 389: asm volatile("vset.s32.s32.ne %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 390: asm volatile("vset.s32.s32.lt %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 391: asm volatile("vset.s32.s32.le %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 392: asm volatile("vset.s32.s32.gt %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 393: asm volatile("vset.s32.s32.ge %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 394: asm volatile("vset.s32.s32.lt.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 395: asm volatile("vset.s32.s32.ge.max %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 396: asm volatile("vset.s32.s32.ne %0.b2, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 397: asm volatile("vset.s32.u32.eq %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 398: asm volatile("vset.s32.u32.ne %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 399: asm volatile("vset.s32.u32.lt %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 400: asm volatile("vset.s32.u32.le %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 401: asm volatile("vset.s32.u32.gt %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 402: asm volatile("vset.s32.u32.ge %0, %1.b1, %2.h0;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 403: asm volatile("vset.s32.u32.lt.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 404: asm volatile("vset.s32.u32.ge.max %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 405: asm volatile("vset.s32.u32.ne %0.b2, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 406: asm volatile("vadd2.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 407: asm volatile("vadd2.u32.u32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 408: asm volatile("vadd2.u32.u32.u32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 409: asm volatile("vadd2.u32.u32.u32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 410: asm volatile("vadd2.u32.u32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 411: asm volatile("vadd2.u32.u32.u32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 412: asm volatile("vadd2.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 413: asm volatile("vadd2.s32.s32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 414: asm volatile("vadd2.s32.s32.s32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 415: asm volatile("vadd2.s32.s32.s32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 416: asm volatile("vadd2.s32.s32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 417: asm volatile("vadd2.s32.s32.s32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 418: asm volatile("vadd2.s32.u32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 419: asm volatile("vadd2.s32.u32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 420: asm volatile("vadd2.s32.u32.s32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 421: asm volatile("vadd2.s32.u32.s32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 422: asm volatile("vadd2.s32.u32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 423: asm volatile("vadd2.s32.u32.s32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 424: asm volatile("vsub2.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 425: asm volatile("vsub2.u32.u32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 426: asm volatile("vsub2.u32.u32.u32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 427: asm volatile("vsub2.u32.u32.u32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 428: asm volatile("vsub2.u32.u32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 429: asm volatile("vsub2.u32.u32.u32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 430: asm volatile("vsub2.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 431: asm volatile("vsub2.s32.s32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 432: asm volatile("vsub2.s32.s32.s32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 433: asm volatile("vsub2.s32.s32.s32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 434: asm volatile("vsub2.s32.s32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 435: asm volatile("vsub2.s32.s32.s32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 436: asm volatile("vsub2.s32.u32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 437: asm volatile("vsub2.s32.u32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 438: asm volatile("vsub2.s32.u32.s32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 439: asm volatile("vsub2.s32.u32.s32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 440: asm volatile("vsub2.s32.u32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 441: asm volatile("vsub2.s32.u32.s32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 442: asm volatile("vavrg2.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 443: asm volatile("vavrg2.u32.u32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 444: asm volatile("vavrg2.u32.u32.u32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 445: asm volatile("vavrg2.u32.u32.u32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 446: asm volatile("vavrg2.u32.u32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 447: asm volatile("vavrg2.u32.u32.u32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 448: asm volatile("vavrg2.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 449: asm volatile("vavrg2.s32.s32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 450: asm volatile("vavrg2.s32.s32.s32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 451: asm volatile("vavrg2.s32.s32.s32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 452: asm volatile("vavrg2.s32.s32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 453: asm volatile("vavrg2.s32.s32.s32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 454: asm volatile("vavrg2.s32.u32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 455: asm volatile("vavrg2.s32.u32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 456: asm volatile("vavrg2.s32.u32.s32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 457: asm volatile("vavrg2.s32.u32.s32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 458: asm volatile("vavrg2.s32.u32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 459: asm volatile("vavrg2.s32.u32.s32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 460: asm volatile("vabsdiff2.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 461: asm volatile("vabsdiff2.u32.u32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 462: asm volatile("vabsdiff2.u32.u32.u32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 463: asm volatile("vabsdiff2.u32.u32.u32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 464: asm volatile("vabsdiff2.u32.u32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 465: asm volatile("vabsdiff2.u32.u32.u32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 466: asm volatile("vabsdiff2.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 467: asm volatile("vabsdiff2.s32.s32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 468: asm volatile("vabsdiff2.s32.s32.s32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 469: asm volatile("vabsdiff2.s32.s32.s32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 470: asm volatile("vabsdiff2.s32.s32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 471: asm volatile("vabsdiff2.s32.s32.s32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 472: asm volatile("vabsdiff2.s32.u32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 473: asm volatile("vabsdiff2.s32.u32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 474: asm volatile("vabsdiff2.s32.u32.s32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 475: asm volatile("vabsdiff2.s32.u32.s32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 476: asm volatile("vabsdiff2.s32.u32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 477: asm volatile("vabsdiff2.s32.u32.s32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 478: asm volatile("vmin2.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 479: asm volatile("vmin2.u32.u32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 480: asm volatile("vmin2.u32.u32.u32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 481: asm volatile("vmin2.u32.u32.u32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 482: asm volatile("vmin2.u32.u32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 483: asm volatile("vmin2.u32.u32.u32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 484: asm volatile("vmin2.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 485: asm volatile("vmin2.s32.s32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 486: asm volatile("vmin2.s32.s32.s32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 487: asm volatile("vmin2.s32.s32.s32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 488: asm volatile("vmin2.s32.s32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 489: asm volatile("vmin2.s32.s32.s32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 490: asm volatile("vmin2.s32.u32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 491: asm volatile("vmin2.s32.u32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 492: asm volatile("vmin2.s32.u32.s32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 493: asm volatile("vmin2.s32.u32.s32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 494: asm volatile("vmin2.s32.u32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 495: asm volatile("vmin2.s32.u32.s32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 496: asm volatile("vmax2.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 497: asm volatile("vmax2.u32.u32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 498: asm volatile("vmax2.u32.u32.u32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 499: asm volatile("vmax2.u32.u32.u32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 500: asm volatile("vmax2.u32.u32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 501: asm volatile("vmax2.u32.u32.u32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 502: asm volatile("vmax2.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 503: asm volatile("vmax2.s32.s32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 504: asm volatile("vmax2.s32.s32.s32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 505: asm volatile("vmax2.s32.s32.s32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 506: asm volatile("vmax2.s32.s32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 507: asm volatile("vmax2.s32.s32.s32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 508: asm volatile("vmax2.s32.u32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 509: asm volatile("vmax2.s32.u32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 510: asm volatile("vmax2.s32.u32.s32 %0.h1, %1.h21, %2.h03, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 511: asm volatile("vmax2.s32.u32.s32.sat %0.h0, %1.h00, %2.h33, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 512: asm volatile("vmax2.s32.u32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 513: asm volatile("vmax2.s32.u32.s32.add %0.h1, %1.h12, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 514: asm volatile("vadd4.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 515: asm volatile("vadd4.u32.u32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 516: asm volatile("vadd4.u32.u32.u32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 517: asm volatile("vadd4.u32.u32.u32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 518: asm volatile("vadd4.u32.u32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 519: asm volatile("vadd4.u32.u32.u32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 520: asm volatile("vadd4.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 521: asm volatile("vadd4.s32.s32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 522: asm volatile("vadd4.s32.s32.s32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 523: asm volatile("vadd4.s32.s32.s32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 524: asm volatile("vadd4.s32.s32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 525: asm volatile("vadd4.s32.s32.s32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 526: asm volatile("vadd4.u32.s32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 527: asm volatile("vadd4.u32.s32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 528: asm volatile("vadd4.u32.s32.u32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 529: asm volatile("vadd4.u32.s32.u32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 530: asm volatile("vadd4.u32.s32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 531: asm volatile("vadd4.u32.s32.u32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 532: asm volatile("vsub4.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 533: asm volatile("vsub4.u32.u32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 534: asm volatile("vsub4.u32.u32.u32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 535: asm volatile("vsub4.u32.u32.u32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 536: asm volatile("vsub4.u32.u32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 537: asm volatile("vsub4.u32.u32.u32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 538: asm volatile("vsub4.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 539: asm volatile("vsub4.s32.s32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 540: asm volatile("vsub4.s32.s32.s32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 541: asm volatile("vsub4.s32.s32.s32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 542: asm volatile("vsub4.s32.s32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 543: asm volatile("vsub4.s32.s32.s32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 544: asm volatile("vsub4.u32.s32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 545: asm volatile("vsub4.u32.s32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 546: asm volatile("vsub4.u32.s32.u32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 547: asm volatile("vsub4.u32.s32.u32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 548: asm volatile("vsub4.u32.s32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 549: asm volatile("vsub4.u32.s32.u32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 550: asm volatile("vavrg4.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 551: asm volatile("vavrg4.u32.u32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 552: asm volatile("vavrg4.u32.u32.u32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 553: asm volatile("vavrg4.u32.u32.u32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 554: asm volatile("vavrg4.u32.u32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 555: asm volatile("vavrg4.u32.u32.u32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 556: asm volatile("vavrg4.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 557: asm volatile("vavrg4.s32.s32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 558: asm volatile("vavrg4.s32.s32.s32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 559: asm volatile("vavrg4.s32.s32.s32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 560: asm volatile("vavrg4.s32.s32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 561: asm volatile("vavrg4.s32.s32.s32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 562: asm volatile("vavrg4.u32.s32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 563: asm volatile("vavrg4.u32.s32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 564: asm volatile("vavrg4.u32.s32.u32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 565: asm volatile("vavrg4.u32.s32.u32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 566: asm volatile("vavrg4.u32.s32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 567: asm volatile("vavrg4.u32.s32.u32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 568: asm volatile("vabsdiff4.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 569: asm volatile("vabsdiff4.u32.u32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 570: asm volatile("vabsdiff4.u32.u32.u32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 571: asm volatile("vabsdiff4.u32.u32.u32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 572: asm volatile("vabsdiff4.u32.u32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 573: asm volatile("vabsdiff4.u32.u32.u32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 574: asm volatile("vabsdiff4.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 575: asm volatile("vabsdiff4.s32.s32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 576: asm volatile("vabsdiff4.s32.s32.s32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 577: asm volatile("vabsdiff4.s32.s32.s32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 578: asm volatile("vabsdiff4.s32.s32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 579: asm volatile("vabsdiff4.s32.s32.s32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 580: asm volatile("vabsdiff4.u32.s32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 581: asm volatile("vabsdiff4.u32.s32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 582: asm volatile("vabsdiff4.u32.s32.u32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 583: asm volatile("vabsdiff4.u32.s32.u32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 584: asm volatile("vabsdiff4.u32.s32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 585: asm volatile("vabsdiff4.u32.s32.u32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 586: asm volatile("vmin4.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 587: asm volatile("vmin4.u32.u32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 588: asm volatile("vmin4.u32.u32.u32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 589: asm volatile("vmin4.u32.u32.u32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 590: asm volatile("vmin4.u32.u32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 591: asm volatile("vmin4.u32.u32.u32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 592: asm volatile("vmin4.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 593: asm volatile("vmin4.s32.s32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 594: asm volatile("vmin4.s32.s32.s32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 595: asm volatile("vmin4.s32.s32.s32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 596: asm volatile("vmin4.s32.s32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 597: asm volatile("vmin4.s32.s32.s32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 598: asm volatile("vmin4.u32.s32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 599: asm volatile("vmin4.u32.s32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 600: asm volatile("vmin4.u32.s32.u32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 601: asm volatile("vmin4.u32.s32.u32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 602: asm volatile("vmin4.u32.s32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 603: asm volatile("vmin4.u32.s32.u32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 604: asm volatile("vmax4.u32.u32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 605: asm volatile("vmax4.u32.u32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 606: asm volatile("vmax4.u32.u32.u32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 607: asm volatile("vmax4.u32.u32.u32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 608: asm volatile("vmax4.u32.u32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 609: asm volatile("vmax4.u32.u32.u32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 610: asm volatile("vmax4.s32.s32.s32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 611: asm volatile("vmax4.s32.s32.s32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 612: asm volatile("vmax4.s32.s32.s32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 613: asm volatile("vmax4.s32.s32.s32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 614: asm volatile("vmax4.s32.s32.s32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 615: asm volatile("vmax4.s32.s32.s32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 616: asm volatile("vmax4.u32.s32.u32 %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 617: asm volatile("vmax4.u32.s32.u32.sat %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 618: asm volatile("vmax4.u32.s32.u32 %0.b20, %1.b7250, %2.b0123, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 619: asm volatile("vmax4.u32.s32.u32.sat %0.b31, %1.b4444, %2.b6061, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 620: asm volatile("vmax4.u32.s32.u32.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 621: asm volatile("vmax4.u32.s32.u32.add %0.b310, %1.b3210, %2.b1357, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 622: asm volatile("vset2.u32.u32.eq %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 623: asm volatile("vset4.u32.u32.eq %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 624: asm volatile("vset2.u32.u32.lt %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 625: asm volatile("vset4.u32.u32.lt %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 626: asm volatile("vset2.u32.u32.ge %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 627: asm volatile("vset4.u32.u32.ge %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 628: asm volatile("vset2.u32.u32.ne %0.h0, %1.h30, %2.h12, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 629: asm volatile("vset4.u32.u32.gt %0.b21, %1.b7654, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 630: asm volatile("vset2.u32.u32.le.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 631: asm volatile("vset4.u32.u32.lt.add %0.b320, %1, %2.b5432, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 632: asm volatile("vset2.s32.s32.eq %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 633: asm volatile("vset4.s32.s32.eq %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 634: asm volatile("vset2.s32.s32.lt %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 635: asm volatile("vset4.s32.s32.lt %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 636: asm volatile("vset2.s32.s32.ge %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 637: asm volatile("vset4.s32.s32.ge %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 638: asm volatile("vset2.s32.s32.ne %0.h0, %1.h30, %2.h12, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 639: asm volatile("vset4.s32.s32.gt %0.b21, %1.b7654, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 640: asm volatile("vset2.s32.s32.le.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 641: asm volatile("vset4.s32.s32.lt.add %0.b320, %1, %2.b5432, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 642: asm volatile("vset2.u32.s32.eq %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 643: asm volatile("vset4.u32.s32.eq %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 644: asm volatile("vset2.u32.s32.lt %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 645: asm volatile("vset4.u32.s32.lt %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 646: asm volatile("vset2.u32.s32.ge %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 647: asm volatile("vset4.u32.s32.ge %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 648: asm volatile("vset2.u32.s32.ne %0.h0, %1.h30, %2.h12, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 649: asm volatile("vset4.u32.s32.gt %0.b21, %1.b7654, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 650: asm volatile("vset2.u32.s32.le.add %0, %1, %2, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
    case 651: asm volatile("vset4.u32.s32.lt.add %0.b320, %1, %2.b5432, %3;" : "=r"(d) : "r"(a), "r"(b), "r"(c)); break;
  }
  out[i] = d;
}
static const char* kTags[] = {
  "vadd.u32.u32.u32 a- b-",
  "vadd.u32.u32.u32 a.b1 b.h1",
  "vadd.u32.u32.u32 a.h0 b.b3",
  "vadd.u32.u32.u32.sat",
  "vadd.u32.u32.u32.add",
  "vadd.u32.u32.u32.min",
  "vadd.u32.u32.u32.max",
  "vadd.u32.u32.u32.sat.add",
  "vadd.u32.u32.u32 d.b0",
  "vadd.u32.u32.u32.sat d.b0",
  "vadd.u32.u32.u32 d.b3",
  "vadd.u32.u32.u32.sat d.b3",
  "vadd.u32.u32.u32 d.h1",
  "vadd.u32.u32.u32.sat d.h1",
  "vadd.s32.s32.s32 a- b-",
  "vadd.s32.s32.s32 a.b1 b.h1",
  "vadd.s32.s32.s32 a.h0 b.b3",
  "vadd.s32.s32.s32.sat",
  "vadd.s32.s32.s32.add",
  "vadd.s32.s32.s32.min",
  "vadd.s32.s32.s32.max",
  "vadd.s32.s32.s32.sat.add",
  "vadd.s32.s32.s32 d.b0",
  "vadd.s32.s32.s32.sat d.b0",
  "vadd.s32.s32.s32 d.b3",
  "vadd.s32.s32.s32.sat d.b3",
  "vadd.s32.s32.s32 d.h1",
  "vadd.s32.s32.s32.sat d.h1",
  "vadd.s32.u32.s32 a- b-",
  "vadd.s32.u32.s32 a.b1 b.h1",
  "vadd.s32.u32.s32 a.h0 b.b3",
  "vadd.s32.u32.s32.sat",
  "vadd.s32.u32.s32.add",
  "vadd.s32.u32.s32.min",
  "vadd.s32.u32.s32.max",
  "vadd.s32.u32.s32.sat.add",
  "vadd.s32.u32.s32 d.b0",
  "vadd.s32.u32.s32.sat d.b0",
  "vadd.s32.u32.s32 d.b3",
  "vadd.s32.u32.s32.sat d.b3",
  "vadd.s32.u32.s32 d.h1",
  "vadd.s32.u32.s32.sat d.h1",
  "vadd.u32.s32.u32 a- b-",
  "vadd.u32.s32.u32 a.b1 b.h1",
  "vadd.u32.s32.u32 a.h0 b.b3",
  "vadd.u32.s32.u32.sat",
  "vadd.u32.s32.u32.add",
  "vadd.u32.s32.u32.min",
  "vadd.u32.s32.u32.max",
  "vadd.u32.s32.u32.sat.add",
  "vadd.u32.s32.u32 d.b0",
  "vadd.u32.s32.u32.sat d.b0",
  "vadd.u32.s32.u32 d.b3",
  "vadd.u32.s32.u32.sat d.b3",
  "vadd.u32.s32.u32 d.h1",
  "vadd.u32.s32.u32.sat d.h1",
  "vsub.u32.u32.u32 a- b-",
  "vsub.u32.u32.u32 a.b1 b.h1",
  "vsub.u32.u32.u32 a.h0 b.b3",
  "vsub.u32.u32.u32.sat",
  "vsub.u32.u32.u32.add",
  "vsub.u32.u32.u32.min",
  "vsub.u32.u32.u32.max",
  "vsub.u32.u32.u32.sat.add",
  "vsub.u32.u32.u32 d.b0",
  "vsub.u32.u32.u32.sat d.b0",
  "vsub.u32.u32.u32 d.b3",
  "vsub.u32.u32.u32.sat d.b3",
  "vsub.u32.u32.u32 d.h1",
  "vsub.u32.u32.u32.sat d.h1",
  "vsub.s32.s32.s32 a- b-",
  "vsub.s32.s32.s32 a.b1 b.h1",
  "vsub.s32.s32.s32 a.h0 b.b3",
  "vsub.s32.s32.s32.sat",
  "vsub.s32.s32.s32.add",
  "vsub.s32.s32.s32.min",
  "vsub.s32.s32.s32.max",
  "vsub.s32.s32.s32.sat.add",
  "vsub.s32.s32.s32 d.b0",
  "vsub.s32.s32.s32.sat d.b0",
  "vsub.s32.s32.s32 d.b3",
  "vsub.s32.s32.s32.sat d.b3",
  "vsub.s32.s32.s32 d.h1",
  "vsub.s32.s32.s32.sat d.h1",
  "vsub.s32.u32.s32 a- b-",
  "vsub.s32.u32.s32 a.b1 b.h1",
  "vsub.s32.u32.s32 a.h0 b.b3",
  "vsub.s32.u32.s32.sat",
  "vsub.s32.u32.s32.add",
  "vsub.s32.u32.s32.min",
  "vsub.s32.u32.s32.max",
  "vsub.s32.u32.s32.sat.add",
  "vsub.s32.u32.s32 d.b0",
  "vsub.s32.u32.s32.sat d.b0",
  "vsub.s32.u32.s32 d.b3",
  "vsub.s32.u32.s32.sat d.b3",
  "vsub.s32.u32.s32 d.h1",
  "vsub.s32.u32.s32.sat d.h1",
  "vsub.u32.s32.u32 a- b-",
  "vsub.u32.s32.u32 a.b1 b.h1",
  "vsub.u32.s32.u32 a.h0 b.b3",
  "vsub.u32.s32.u32.sat",
  "vsub.u32.s32.u32.add",
  "vsub.u32.s32.u32.min",
  "vsub.u32.s32.u32.max",
  "vsub.u32.s32.u32.sat.add",
  "vsub.u32.s32.u32 d.b0",
  "vsub.u32.s32.u32.sat d.b0",
  "vsub.u32.s32.u32 d.b3",
  "vsub.u32.s32.u32.sat d.b3",
  "vsub.u32.s32.u32 d.h1",
  "vsub.u32.s32.u32.sat d.h1",
  "vabsdiff.u32.u32.u32 a- b-",
  "vabsdiff.u32.u32.u32 a.b1 b.h1",
  "vabsdiff.u32.u32.u32 a.h0 b.b3",
  "vabsdiff.u32.u32.u32.sat",
  "vabsdiff.u32.u32.u32.add",
  "vabsdiff.u32.u32.u32.min",
  "vabsdiff.u32.u32.u32.max",
  "vabsdiff.u32.u32.u32.sat.add",
  "vabsdiff.u32.u32.u32 d.b0",
  "vabsdiff.u32.u32.u32.sat d.b0",
  "vabsdiff.u32.u32.u32 d.b3",
  "vabsdiff.u32.u32.u32.sat d.b3",
  "vabsdiff.u32.u32.u32 d.h1",
  "vabsdiff.u32.u32.u32.sat d.h1",
  "vabsdiff.s32.s32.s32 a- b-",
  "vabsdiff.s32.s32.s32 a.b1 b.h1",
  "vabsdiff.s32.s32.s32 a.h0 b.b3",
  "vabsdiff.s32.s32.s32.sat",
  "vabsdiff.s32.s32.s32.add",
  "vabsdiff.s32.s32.s32.min",
  "vabsdiff.s32.s32.s32.max",
  "vabsdiff.s32.s32.s32.sat.add",
  "vabsdiff.s32.s32.s32 d.b0",
  "vabsdiff.s32.s32.s32.sat d.b0",
  "vabsdiff.s32.s32.s32 d.b3",
  "vabsdiff.s32.s32.s32.sat d.b3",
  "vabsdiff.s32.s32.s32 d.h1",
  "vabsdiff.s32.s32.s32.sat d.h1",
  "vabsdiff.s32.u32.s32 a- b-",
  "vabsdiff.s32.u32.s32 a.b1 b.h1",
  "vabsdiff.s32.u32.s32 a.h0 b.b3",
  "vabsdiff.s32.u32.s32.sat",
  "vabsdiff.s32.u32.s32.add",
  "vabsdiff.s32.u32.s32.min",
  "vabsdiff.s32.u32.s32.max",
  "vabsdiff.s32.u32.s32.sat.add",
  "vabsdiff.s32.u32.s32 d.b0",
  "vabsdiff.s32.u32.s32.sat d.b0",
  "vabsdiff.s32.u32.s32 d.b3",
  "vabsdiff.s32.u32.s32.sat d.b3",
  "vabsdiff.s32.u32.s32 d.h1",
  "vabsdiff.s32.u32.s32.sat d.h1",
  "vabsdiff.u32.s32.u32 a- b-",
  "vabsdiff.u32.s32.u32 a.b1 b.h1",
  "vabsdiff.u32.s32.u32 a.h0 b.b3",
  "vabsdiff.u32.s32.u32.sat",
  "vabsdiff.u32.s32.u32.add",
  "vabsdiff.u32.s32.u32.min",
  "vabsdiff.u32.s32.u32.max",
  "vabsdiff.u32.s32.u32.sat.add",
  "vabsdiff.u32.s32.u32 d.b0",
  "vabsdiff.u32.s32.u32.sat d.b0",
  "vabsdiff.u32.s32.u32 d.b3",
  "vabsdiff.u32.s32.u32.sat d.b3",
  "vabsdiff.u32.s32.u32 d.h1",
  "vabsdiff.u32.s32.u32.sat d.h1",
  "vmin.u32.u32.u32 a- b-",
  "vmin.u32.u32.u32 a.b1 b.h1",
  "vmin.u32.u32.u32 a.h0 b.b3",
  "vmin.u32.u32.u32.sat",
  "vmin.u32.u32.u32.add",
  "vmin.u32.u32.u32.min",
  "vmin.u32.u32.u32.max",
  "vmin.u32.u32.u32.sat.add",
  "vmin.u32.u32.u32 d.b0",
  "vmin.u32.u32.u32.sat d.b0",
  "vmin.u32.u32.u32 d.b3",
  "vmin.u32.u32.u32.sat d.b3",
  "vmin.u32.u32.u32 d.h1",
  "vmin.u32.u32.u32.sat d.h1",
  "vmin.s32.s32.s32 a- b-",
  "vmin.s32.s32.s32 a.b1 b.h1",
  "vmin.s32.s32.s32 a.h0 b.b3",
  "vmin.s32.s32.s32.sat",
  "vmin.s32.s32.s32.add",
  "vmin.s32.s32.s32.min",
  "vmin.s32.s32.s32.max",
  "vmin.s32.s32.s32.sat.add",
  "vmin.s32.s32.s32 d.b0",
  "vmin.s32.s32.s32.sat d.b0",
  "vmin.s32.s32.s32 d.b3",
  "vmin.s32.s32.s32.sat d.b3",
  "vmin.s32.s32.s32 d.h1",
  "vmin.s32.s32.s32.sat d.h1",
  "vmin.s32.u32.s32 a- b-",
  "vmin.s32.u32.s32 a.b1 b.h1",
  "vmin.s32.u32.s32 a.h0 b.b3",
  "vmin.s32.u32.s32.sat",
  "vmin.s32.u32.s32.add",
  "vmin.s32.u32.s32.min",
  "vmin.s32.u32.s32.max",
  "vmin.s32.u32.s32.sat.add",
  "vmin.s32.u32.s32 d.b0",
  "vmin.s32.u32.s32.sat d.b0",
  "vmin.s32.u32.s32 d.b3",
  "vmin.s32.u32.s32.sat d.b3",
  "vmin.s32.u32.s32 d.h1",
  "vmin.s32.u32.s32.sat d.h1",
  "vmin.u32.s32.u32 a- b-",
  "vmin.u32.s32.u32 a.b1 b.h1",
  "vmin.u32.s32.u32 a.h0 b.b3",
  "vmin.u32.s32.u32.sat",
  "vmin.u32.s32.u32.add",
  "vmin.u32.s32.u32.min",
  "vmin.u32.s32.u32.max",
  "vmin.u32.s32.u32.sat.add",
  "vmin.u32.s32.u32 d.b0",
  "vmin.u32.s32.u32.sat d.b0",
  "vmin.u32.s32.u32 d.b3",
  "vmin.u32.s32.u32.sat d.b3",
  "vmin.u32.s32.u32 d.h1",
  "vmin.u32.s32.u32.sat d.h1",
  "vmax.u32.u32.u32 a- b-",
  "vmax.u32.u32.u32 a.b1 b.h1",
  "vmax.u32.u32.u32 a.h0 b.b3",
  "vmax.u32.u32.u32.sat",
  "vmax.u32.u32.u32.add",
  "vmax.u32.u32.u32.min",
  "vmax.u32.u32.u32.max",
  "vmax.u32.u32.u32.sat.add",
  "vmax.u32.u32.u32 d.b0",
  "vmax.u32.u32.u32.sat d.b0",
  "vmax.u32.u32.u32 d.b3",
  "vmax.u32.u32.u32.sat d.b3",
  "vmax.u32.u32.u32 d.h1",
  "vmax.u32.u32.u32.sat d.h1",
  "vmax.s32.s32.s32 a- b-",
  "vmax.s32.s32.s32 a.b1 b.h1",
  "vmax.s32.s32.s32 a.h0 b.b3",
  "vmax.s32.s32.s32.sat",
  "vmax.s32.s32.s32.add",
  "vmax.s32.s32.s32.min",
  "vmax.s32.s32.s32.max",
  "vmax.s32.s32.s32.sat.add",
  "vmax.s32.s32.s32 d.b0",
  "vmax.s32.s32.s32.sat d.b0",
  "vmax.s32.s32.s32 d.b3",
  "vmax.s32.s32.s32.sat d.b3",
  "vmax.s32.s32.s32 d.h1",
  "vmax.s32.s32.s32.sat d.h1",
  "vmax.s32.u32.s32 a- b-",
  "vmax.s32.u32.s32 a.b1 b.h1",
  "vmax.s32.u32.s32 a.h0 b.b3",
  "vmax.s32.u32.s32.sat",
  "vmax.s32.u32.s32.add",
  "vmax.s32.u32.s32.min",
  "vmax.s32.u32.s32.max",
  "vmax.s32.u32.s32.sat.add",
  "vmax.s32.u32.s32 d.b0",
  "vmax.s32.u32.s32.sat d.b0",
  "vmax.s32.u32.s32 d.b3",
  "vmax.s32.u32.s32.sat d.b3",
  "vmax.s32.u32.s32 d.h1",
  "vmax.s32.u32.s32.sat d.h1",
  "vmax.u32.s32.u32 a- b-",
  "vmax.u32.s32.u32 a.b1 b.h1",
  "vmax.u32.s32.u32 a.h0 b.b3",
  "vmax.u32.s32.u32.sat",
  "vmax.u32.s32.u32.add",
  "vmax.u32.s32.u32.min",
  "vmax.u32.s32.u32.max",
  "vmax.u32.s32.u32.sat.add",
  "vmax.u32.s32.u32 d.b0",
  "vmax.u32.s32.u32.sat d.b0",
  "vmax.u32.s32.u32 d.b3",
  "vmax.u32.s32.u32.sat d.b3",
  "vmax.u32.s32.u32 d.h1",
  "vmax.u32.s32.u32.sat d.h1",
  "vadd.u32.u32.u32 c-only",
  "vadd.s32.s32.s32 c-only",
  "vabsdiff.u32.u32.u32 c-only",
  "vabsdiff.s32.s32.s32 c-only",
  "vmin.u32.u32.u32 c-only",
  "vmin.s32.s32.s32 c-only",
  "vshl.u32.u32.u32.clamp",
  "vshl.u32.u32.u32.clamp sel",
  "vshl.u32.u32.u32.wrap",
  "vshl.u32.u32.u32.wrap sel",
  "vshl.u32.u32.u32.sat.clamp",
  "vshl.u32.u32.u32.clamp.add",
  "vshl.u32.u32.u32.wrap d.h0",
  "vshl.s32.s32.u32.clamp",
  "vshl.s32.s32.u32.clamp sel",
  "vshl.s32.s32.u32.wrap",
  "vshl.s32.s32.u32.wrap sel",
  "vshl.s32.s32.u32.sat.clamp",
  "vshl.s32.s32.u32.clamp.add",
  "vshl.s32.s32.u32.wrap d.h0",
  "vshl.s32.u32.u32.clamp",
  "vshl.s32.u32.u32.clamp sel",
  "vshl.s32.u32.u32.wrap",
  "vshl.s32.u32.u32.wrap sel",
  "vshl.s32.u32.u32.sat.clamp",
  "vshl.s32.u32.u32.clamp.add",
  "vshl.s32.u32.u32.wrap d.h0",
  "vshl.u32.s32.u32.clamp",
  "vshl.u32.s32.u32.clamp sel",
  "vshl.u32.s32.u32.wrap",
  "vshl.u32.s32.u32.wrap sel",
  "vshl.u32.s32.u32.sat.clamp",
  "vshl.u32.s32.u32.clamp.add",
  "vshl.u32.s32.u32.wrap d.h0",
  "vshr.u32.u32.u32.clamp",
  "vshr.u32.u32.u32.clamp sel",
  "vshr.u32.u32.u32.wrap",
  "vshr.u32.u32.u32.wrap sel",
  "vshr.u32.u32.u32.sat.clamp",
  "vshr.u32.u32.u32.clamp.add",
  "vshr.u32.u32.u32.wrap d.h0",
  "vshr.s32.s32.u32.clamp",
  "vshr.s32.s32.u32.clamp sel",
  "vshr.s32.s32.u32.wrap",
  "vshr.s32.s32.u32.wrap sel",
  "vshr.s32.s32.u32.sat.clamp",
  "vshr.s32.s32.u32.clamp.add",
  "vshr.s32.s32.u32.wrap d.h0",
  "vshr.s32.u32.u32.clamp",
  "vshr.s32.u32.u32.clamp sel",
  "vshr.s32.u32.u32.wrap",
  "vshr.s32.u32.u32.wrap sel",
  "vshr.s32.u32.u32.sat.clamp",
  "vshr.s32.u32.u32.clamp.add",
  "vshr.s32.u32.u32.wrap d.h0",
  "vshr.u32.s32.u32.clamp",
  "vshr.u32.s32.u32.clamp sel",
  "vshr.u32.s32.u32.wrap",
  "vshr.u32.s32.u32.wrap sel",
  "vshr.u32.s32.u32.sat.clamp",
  "vshr.u32.s32.u32.clamp.add",
  "vshr.u32.s32.u32.wrap d.h0",
  "vmad.u32.u32.u32",
  "vmad.u32.u32.u32 sel",
  "vmad.u32.u32.u32.sat",
  "vmad.u32.u32.u32.shr7",
  "vmad.u32.u32.u32.sat.shr15",
  "vmad.u32.u32.u32.po",
  "vmad.u32.u32.u32.po.sat.shr7",
  "vmad.s32.s32.s32",
  "vmad.s32.s32.s32 sel",
  "vmad.s32.s32.s32.sat",
  "vmad.s32.s32.s32.shr7",
  "vmad.s32.s32.s32.sat.shr15",
  "vmad.s32.s32.s32.po",
  "vmad.s32.s32.s32.po.sat.shr7",
  "vmad.s32.s32.s32 -a",
  "vmad.s32.s32.s32 -c",
  "vmad.s32.s32.s32.sat -b",
  "vmad.s32.u32.s32",
  "vmad.s32.u32.s32 sel",
  "vmad.s32.u32.s32.sat",
  "vmad.s32.u32.s32.shr7",
  "vmad.s32.u32.s32.sat.shr15",
  "vmad.s32.u32.s32.po",
  "vmad.s32.u32.s32.po.sat.shr7",
  "vmad.s32.u32.s32 -a",
  "vmad.s32.u32.s32 -c",
  "vmad.s32.u32.s32.sat -b",
  "vmad.s32.s32.u32",
  "vmad.s32.s32.u32 sel",
  "vmad.s32.s32.u32.sat",
  "vmad.s32.s32.u32.shr7",
  "vmad.s32.s32.u32.sat.shr15",
  "vmad.s32.s32.u32.po",
  "vmad.s32.s32.u32.po.sat.shr7",
  "vmad.s32.s32.u32 -a",
  "vmad.s32.s32.u32 -c",
  "vmad.s32.s32.u32.sat -b",
  "vset.u32.u32.eq",
  "vset.u32.u32.ne",
  "vset.u32.u32.lt",
  "vset.u32.u32.le",
  "vset.u32.u32.gt",
  "vset.u32.u32.ge",
  "vset.u32.u32.lt.add",
  "vset.u32.u32.ge.max",
  "vset.u32.u32.ne d.b2",
  "vset.s32.s32.eq",
  "vset.s32.s32.ne",
  "vset.s32.s32.lt",
  "vset.s32.s32.le",
  "vset.s32.s32.gt",
  "vset.s32.s32.ge",
  "vset.s32.s32.lt.add",
  "vset.s32.s32.ge.max",
  "vset.s32.s32.ne d.b2",
  "vset.s32.u32.eq",
  "vset.s32.u32.ne",
  "vset.s32.u32.lt",
  "vset.s32.u32.le",
  "vset.s32.u32.gt",
  "vset.s32.u32.ge",
  "vset.s32.u32.lt.add",
  "vset.s32.u32.ge.max",
  "vset.s32.u32.ne d.b2",
  "vadd2.u32.u32.u32",
  "vadd2.u32.u32.u32.sat",
  "vadd2.u32.u32.u32 mask/sel",
  "vadd2.u32.u32.u32.sat mask",
  "vadd2.u32.u32.u32.add",
  "vadd2.u32.u32.u32.add mask",
  "vadd2.s32.s32.s32",
  "vadd2.s32.s32.s32.sat",
  "vadd2.s32.s32.s32 mask/sel",
  "vadd2.s32.s32.s32.sat mask",
  "vadd2.s32.s32.s32.add",
  "vadd2.s32.s32.s32.add mask",
  "vadd2.s32.u32.s32",
  "vadd2.s32.u32.s32.sat",
  "vadd2.s32.u32.s32 mask/sel",
  "vadd2.s32.u32.s32.sat mask",
  "vadd2.s32.u32.s32.add",
  "vadd2.s32.u32.s32.add mask",
  "vsub2.u32.u32.u32",
  "vsub2.u32.u32.u32.sat",
  "vsub2.u32.u32.u32 mask/sel",
  "vsub2.u32.u32.u32.sat mask",
  "vsub2.u32.u32.u32.add",
  "vsub2.u32.u32.u32.add mask",
  "vsub2.s32.s32.s32",
  "vsub2.s32.s32.s32.sat",
  "vsub2.s32.s32.s32 mask/sel",
  "vsub2.s32.s32.s32.sat mask",
  "vsub2.s32.s32.s32.add",
  "vsub2.s32.s32.s32.add mask",
  "vsub2.s32.u32.s32",
  "vsub2.s32.u32.s32.sat",
  "vsub2.s32.u32.s32 mask/sel",
  "vsub2.s32.u32.s32.sat mask",
  "vsub2.s32.u32.s32.add",
  "vsub2.s32.u32.s32.add mask",
  "vavrg2.u32.u32.u32",
  "vavrg2.u32.u32.u32.sat",
  "vavrg2.u32.u32.u32 mask/sel",
  "vavrg2.u32.u32.u32.sat mask",
  "vavrg2.u32.u32.u32.add",
  "vavrg2.u32.u32.u32.add mask",
  "vavrg2.s32.s32.s32",
  "vavrg2.s32.s32.s32.sat",
  "vavrg2.s32.s32.s32 mask/sel",
  "vavrg2.s32.s32.s32.sat mask",
  "vavrg2.s32.s32.s32.add",
  "vavrg2.s32.s32.s32.add mask",
  "vavrg2.s32.u32.s32",
  "vavrg2.s32.u32.s32.sat",
  "vavrg2.s32.u32.s32 mask/sel",
  "vavrg2.s32.u32.s32.sat mask",
  "vavrg2.s32.u32.s32.add",
  "vavrg2.s32.u32.s32.add mask",
  "vabsdiff2.u32.u32.u32",
  "vabsdiff2.u32.u32.u32.sat",
  "vabsdiff2.u32.u32.u32 mask/sel",
  "vabsdiff2.u32.u32.u32.sat mask",
  "vabsdiff2.u32.u32.u32.add",
  "vabsdiff2.u32.u32.u32.add mask",
  "vabsdiff2.s32.s32.s32",
  "vabsdiff2.s32.s32.s32.sat",
  "vabsdiff2.s32.s32.s32 mask/sel",
  "vabsdiff2.s32.s32.s32.sat mask",
  "vabsdiff2.s32.s32.s32.add",
  "vabsdiff2.s32.s32.s32.add mask",
  "vabsdiff2.s32.u32.s32",
  "vabsdiff2.s32.u32.s32.sat",
  "vabsdiff2.s32.u32.s32 mask/sel",
  "vabsdiff2.s32.u32.s32.sat mask",
  "vabsdiff2.s32.u32.s32.add",
  "vabsdiff2.s32.u32.s32.add mask",
  "vmin2.u32.u32.u32",
  "vmin2.u32.u32.u32.sat",
  "vmin2.u32.u32.u32 mask/sel",
  "vmin2.u32.u32.u32.sat mask",
  "vmin2.u32.u32.u32.add",
  "vmin2.u32.u32.u32.add mask",
  "vmin2.s32.s32.s32",
  "vmin2.s32.s32.s32.sat",
  "vmin2.s32.s32.s32 mask/sel",
  "vmin2.s32.s32.s32.sat mask",
  "vmin2.s32.s32.s32.add",
  "vmin2.s32.s32.s32.add mask",
  "vmin2.s32.u32.s32",
  "vmin2.s32.u32.s32.sat",
  "vmin2.s32.u32.s32 mask/sel",
  "vmin2.s32.u32.s32.sat mask",
  "vmin2.s32.u32.s32.add",
  "vmin2.s32.u32.s32.add mask",
  "vmax2.u32.u32.u32",
  "vmax2.u32.u32.u32.sat",
  "vmax2.u32.u32.u32 mask/sel",
  "vmax2.u32.u32.u32.sat mask",
  "vmax2.u32.u32.u32.add",
  "vmax2.u32.u32.u32.add mask",
  "vmax2.s32.s32.s32",
  "vmax2.s32.s32.s32.sat",
  "vmax2.s32.s32.s32 mask/sel",
  "vmax2.s32.s32.s32.sat mask",
  "vmax2.s32.s32.s32.add",
  "vmax2.s32.s32.s32.add mask",
  "vmax2.s32.u32.s32",
  "vmax2.s32.u32.s32.sat",
  "vmax2.s32.u32.s32 mask/sel",
  "vmax2.s32.u32.s32.sat mask",
  "vmax2.s32.u32.s32.add",
  "vmax2.s32.u32.s32.add mask",
  "vadd4.u32.u32.u32",
  "vadd4.u32.u32.u32.sat",
  "vadd4.u32.u32.u32 mask/sel",
  "vadd4.u32.u32.u32.sat mask",
  "vadd4.u32.u32.u32.add",
  "vadd4.u32.u32.u32.add mask",
  "vadd4.s32.s32.s32",
  "vadd4.s32.s32.s32.sat",
  "vadd4.s32.s32.s32 mask/sel",
  "vadd4.s32.s32.s32.sat mask",
  "vadd4.s32.s32.s32.add",
  "vadd4.s32.s32.s32.add mask",
  "vadd4.u32.s32.u32",
  "vadd4.u32.s32.u32.sat",
  "vadd4.u32.s32.u32 mask/sel",
  "vadd4.u32.s32.u32.sat mask",
  "vadd4.u32.s32.u32.add",
  "vadd4.u32.s32.u32.add mask",
  "vsub4.u32.u32.u32",
  "vsub4.u32.u32.u32.sat",
  "vsub4.u32.u32.u32 mask/sel",
  "vsub4.u32.u32.u32.sat mask",
  "vsub4.u32.u32.u32.add",
  "vsub4.u32.u32.u32.add mask",
  "vsub4.s32.s32.s32",
  "vsub4.s32.s32.s32.sat",
  "vsub4.s32.s32.s32 mask/sel",
  "vsub4.s32.s32.s32.sat mask",
  "vsub4.s32.s32.s32.add",
  "vsub4.s32.s32.s32.add mask",
  "vsub4.u32.s32.u32",
  "vsub4.u32.s32.u32.sat",
  "vsub4.u32.s32.u32 mask/sel",
  "vsub4.u32.s32.u32.sat mask",
  "vsub4.u32.s32.u32.add",
  "vsub4.u32.s32.u32.add mask",
  "vavrg4.u32.u32.u32",
  "vavrg4.u32.u32.u32.sat",
  "vavrg4.u32.u32.u32 mask/sel",
  "vavrg4.u32.u32.u32.sat mask",
  "vavrg4.u32.u32.u32.add",
  "vavrg4.u32.u32.u32.add mask",
  "vavrg4.s32.s32.s32",
  "vavrg4.s32.s32.s32.sat",
  "vavrg4.s32.s32.s32 mask/sel",
  "vavrg4.s32.s32.s32.sat mask",
  "vavrg4.s32.s32.s32.add",
  "vavrg4.s32.s32.s32.add mask",
  "vavrg4.u32.s32.u32",
  "vavrg4.u32.s32.u32.sat",
  "vavrg4.u32.s32.u32 mask/sel",
  "vavrg4.u32.s32.u32.sat mask",
  "vavrg4.u32.s32.u32.add",
  "vavrg4.u32.s32.u32.add mask",
  "vabsdiff4.u32.u32.u32",
  "vabsdiff4.u32.u32.u32.sat",
  "vabsdiff4.u32.u32.u32 mask/sel",
  "vabsdiff4.u32.u32.u32.sat mask",
  "vabsdiff4.u32.u32.u32.add",
  "vabsdiff4.u32.u32.u32.add mask",
  "vabsdiff4.s32.s32.s32",
  "vabsdiff4.s32.s32.s32.sat",
  "vabsdiff4.s32.s32.s32 mask/sel",
  "vabsdiff4.s32.s32.s32.sat mask",
  "vabsdiff4.s32.s32.s32.add",
  "vabsdiff4.s32.s32.s32.add mask",
  "vabsdiff4.u32.s32.u32",
  "vabsdiff4.u32.s32.u32.sat",
  "vabsdiff4.u32.s32.u32 mask/sel",
  "vabsdiff4.u32.s32.u32.sat mask",
  "vabsdiff4.u32.s32.u32.add",
  "vabsdiff4.u32.s32.u32.add mask",
  "vmin4.u32.u32.u32",
  "vmin4.u32.u32.u32.sat",
  "vmin4.u32.u32.u32 mask/sel",
  "vmin4.u32.u32.u32.sat mask",
  "vmin4.u32.u32.u32.add",
  "vmin4.u32.u32.u32.add mask",
  "vmin4.s32.s32.s32",
  "vmin4.s32.s32.s32.sat",
  "vmin4.s32.s32.s32 mask/sel",
  "vmin4.s32.s32.s32.sat mask",
  "vmin4.s32.s32.s32.add",
  "vmin4.s32.s32.s32.add mask",
  "vmin4.u32.s32.u32",
  "vmin4.u32.s32.u32.sat",
  "vmin4.u32.s32.u32 mask/sel",
  "vmin4.u32.s32.u32.sat mask",
  "vmin4.u32.s32.u32.add",
  "vmin4.u32.s32.u32.add mask",
  "vmax4.u32.u32.u32",
  "vmax4.u32.u32.u32.sat",
  "vmax4.u32.u32.u32 mask/sel",
  "vmax4.u32.u32.u32.sat mask",
  "vmax4.u32.u32.u32.add",
  "vmax4.u32.u32.u32.add mask",
  "vmax4.s32.s32.s32",
  "vmax4.s32.s32.s32.sat",
  "vmax4.s32.s32.s32 mask/sel",
  "vmax4.s32.s32.s32.sat mask",
  "vmax4.s32.s32.s32.add",
  "vmax4.s32.s32.s32.add mask",
  "vmax4.u32.s32.u32",
  "vmax4.u32.s32.u32.sat",
  "vmax4.u32.s32.u32 mask/sel",
  "vmax4.u32.s32.u32.sat mask",
  "vmax4.u32.s32.u32.add",
  "vmax4.u32.s32.u32.add mask",
  "vset2.u32.u32.eq",
  "vset4.u32.u32.eq",
  "vset2.u32.u32.lt",
  "vset4.u32.u32.lt",
  "vset2.u32.u32.ge",
  "vset4.u32.u32.ge",
  "vset2.u32.u32.ne mask",
  "vset4.u32.u32.gt mask",
  "vset2.u32.u32.le.add",
  "vset4.u32.u32.lt.add",
  "vset2.s32.s32.eq",
  "vset4.s32.s32.eq",
  "vset2.s32.s32.lt",
  "vset4.s32.s32.lt",
  "vset2.s32.s32.ge",
  "vset4.s32.s32.ge",
  "vset2.s32.s32.ne mask",
  "vset4.s32.s32.gt mask",
  "vset2.s32.s32.le.add",
  "vset4.s32.s32.lt.add",
  "vset2.u32.s32.eq",
  "vset4.u32.s32.eq",
  "vset2.u32.s32.lt",
  "vset4.u32.s32.lt",
  "vset2.u32.s32.ge",
  "vset4.u32.s32.ge",
  "vset2.u32.s32.ne mask",
  "vset4.u32.s32.gt mask",
  "vset2.u32.s32.le.add",
  "vset4.u32.s32.lt.add",
};
int main(int argc, char** argv) {
  const bool print = argc > 1 && std::strcmp(argv[1], "--print") == 0;
  const int dump = argc > 2 && std::strcmp(argv[1], "--dump") == 0 ? atoi(argv[2]) : -1;
  const int nv = sizeof kTags / sizeof kTags[0];
  unsigned h[3 * kN];
  unsigned long long s = 0x9E3779B97F4A7C15ull;
  const unsigned edge[] = {0u, 1u, 0x7Fu, 0x80u, 0xFFu, 0x7FFFu, 0x8000u, 0xFFFFu, 0x7FFFFFFFu, 0x80000000u, 0xFFFFFFFFu,
                           0x01FF807Fu, 0x80017FFEu, 0x00000020u, 0x0000001Fu, 0x00000021u};
  for (int i = 0; i < 3 * kN; ++i) {
    s ^= s << 13; s ^= s >> 7; s ^= s << 17;
    h[i] = (i < 3 * 16 * 3) ? edge[(i / 3 + i % 3 * 5) % 16] : static_cast<unsigned>(s);
  }
  for (int i = 0; i < 16; ++i) { h[3 * i] = edge[i]; h[3 * i + 1] = edge[(i * 7 + 3) % 16]; h[3 * i + 2] = edge[(i * 5 + 1) % 16]; }
  unsigned *din, *dout;
  cudaMalloc(&din, sizeof h);
  cudaMalloc(&dout, kN * 4);
  cudaMemcpy(din, h, sizeof h, cudaMemcpyHostToDevice);
  int bad = 0;
  for (int v = 0; v < nv; ++v) {
    k<<<1, kN>>>(v, din, dout);
    if (cudaDeviceSynchronize() != cudaSuccess) { printf("variant %d (%s) failed to run\n", v, kTags[v]); return 1; }
    unsigned o[kN];
    cudaMemcpy(o, dout, sizeof o, cudaMemcpyDeviceToHost);
    unsigned long long hash = 1469598103934665603ull;
    for (unsigned x : o) { hash ^= x; hash *= 1099511628211ull; }
    if (v == dump) {
      for (int i = 0; i < kN; ++i) printf("%3d a=%08x b=%08x c=%08x d=%08x\n", i, h[3 * i], h[3 * i + 1], h[3 * i + 2], o[i]);
      return 0;
    }
    if (print) { printf("    {\"%s\", 0x%016llxull},\n", kTags[v], hash); continue; }
    if (v >= (int)(sizeof kExpected / sizeof kExpected[0]) || hash != kExpected[v].hash) {
      if (bad++ < 30) printf("%s: 0x%016llx, the card gave 0x%016llx\n", kTags[v], hash,
                             v < (int)(sizeof kExpected / sizeof kExpected[0]) ? kExpected[v].hash : 0ull);
    }
  }
  if (print) return 0;
  printf("%d video forms, %d differ\n", nv, bad);
  puts(bad ? "FAIL" : "PASS");
  return bad ? 1 : 0;
}
