// Every CUDA error code, with its runtime-API name, driver-API name and
// description, in one table both shims read.
//
// It used to be two tables, each listing the handful of codes its own shim
// returned. That was wrong in two directions: a program prints the name of
// whatever code it got, including codes a library it links returned, and the
// runtime answered "cudaErrorUnknown" for all of those -- a real, named code
// reported as the one code that means "no idea". The driver side answered
// CUDA_ERROR_INVALID_VALUE and a NULL string for codes as ordinary as
// CUDA_ERROR_NO_DEVICE.
//
// Codes are numbers rather than enumerators on purpose. The numeric values are
// the ABI and never change, but the enumerator list grows with each toolkit,
// and this is compiled against CUDA 12 as well as 13. The names are the
// identifiers the public headers (driver_types.h, cuda.h) declare; the
// descriptions are written for this table.
#pragma once

namespace vgpu::cuda {

struct ErrorInfo {
  int code;
  const char* runtime_name;  // nullptr: the runtime API has no such code
  const char* driver_name;   // nullptr: the driver API has no such code
  const char* text;
};

inline constexpr ErrorInfo kErrors[] = {
    {0, "cudaSuccess", "CUDA_SUCCESS", "no error"},
    {1, "cudaErrorInvalidValue", "CUDA_ERROR_INVALID_VALUE", "invalid argument"},
    {2, "cudaErrorMemoryAllocation", "CUDA_ERROR_OUT_OF_MEMORY", "out of memory"},
    {3, "cudaErrorInitializationError", "CUDA_ERROR_NOT_INITIALIZED", "initialization error"},
    {4, "cudaErrorCudartUnloading", "CUDA_ERROR_DEINITIALIZED", "driver shutting down"},
    {5, "cudaErrorProfilerDisabled", "CUDA_ERROR_PROFILER_DISABLED",
     "profiler disabled while using external profiling tool"},
    {6, "cudaErrorProfilerNotInitialized", "CUDA_ERROR_PROFILER_NOT_INITIALIZED",
     "profiler not initialized"},
    {7, "cudaErrorProfilerAlreadyStarted", "CUDA_ERROR_PROFILER_ALREADY_STARTED",
     "profiler already started"},
    {8, "cudaErrorProfilerAlreadyStopped", "CUDA_ERROR_PROFILER_ALREADY_STOPPED",
     "profiler already stopped"},
    {9, "cudaErrorInvalidConfiguration", nullptr, "invalid configuration argument"},
    {12, "cudaErrorInvalidPitchValue", nullptr, "invalid pitch argument"},
    {13, "cudaErrorInvalidSymbol", nullptr, "invalid device symbol"},
    {16, "cudaErrorInvalidHostPointer", nullptr, "invalid host pointer"},
    {17, "cudaErrorInvalidDevicePointer", nullptr, "invalid device pointer"},
    {18, "cudaErrorInvalidTexture", nullptr, "invalid texture reference"},
    {19, "cudaErrorInvalidTextureBinding", nullptr, "texture is not bound to a valid texture"},
    {20, "cudaErrorInvalidChannelDescriptor", nullptr, "invalid channel descriptor"},
    {21, "cudaErrorInvalidMemcpyDirection", nullptr, "invalid copy direction for memcpy"},
    {22, "cudaErrorAddressOfConstant", nullptr, "invalid address of constant"},
    {23, "cudaErrorTextureFetchFailed", nullptr, "fetch from texture failed"},
    {24, "cudaErrorTextureNotBound", nullptr, "texture is not bound"},
    {25, "cudaErrorSynchronizationError", nullptr, "synchronization error"},
    {26, "cudaErrorInvalidFilterSetting", nullptr, "invalid texture filter setting"},
    {27, "cudaErrorInvalidNormSetting", nullptr, "invalid texture normalization setting"},
    {28, "cudaErrorMixedDeviceExecution", nullptr, "mixing different types of devices is not allowed"},
    {31, "cudaErrorNotYetImplemented", nullptr, "feature not yet implemented"},
    {32, "cudaErrorMemoryValueTooLarge", nullptr, "memory size or pointer value too large"},
    {34, "cudaErrorStubLibrary", "CUDA_ERROR_STUB_LIBRARY", "CUDA driver is a stub library"},
    {35, "cudaErrorInsufficientDriver", nullptr,
     "CUDA driver version is insufficient for CUDA runtime version"},
    {36, "cudaErrorCallRequiresNewerDriver", "CUDA_ERROR_CALL_REQUIRES_NEWER_DRIVER",
     "API call is not supported in the installed CUDA driver"},
    {37, "cudaErrorInvalidSurface", nullptr, "invalid surface reference"},
    {43, "cudaErrorDuplicateVariableName", nullptr, "duplicate global variable name"},
    {44, "cudaErrorDuplicateTextureName", nullptr, "duplicate texture name"},
    {45, "cudaErrorDuplicateSurfaceName", nullptr, "duplicate surface name"},
    {46, "cudaErrorDevicesUnavailable", "CUDA_ERROR_DEVICE_UNAVAILABLE",
     "CUDA-capable device(s) is/are busy or unavailable"},
    {49, "cudaErrorIncompatibleDriverContext", nullptr, "incompatible driver context"},
    {52, "cudaErrorMissingConfiguration", nullptr, "__global__ function call is not configured"},
    {53, "cudaErrorPriorLaunchFailure", nullptr, "unspecified launch failure in prior launch"},
    {65, "cudaErrorLaunchMaxDepthExceeded", nullptr, "launch exceeded maximum depth"},
    {66, "cudaErrorLaunchFileScopedTex", nullptr, "launch used a file-scoped texture"},
    {67, "cudaErrorLaunchFileScopedSurf", nullptr, "launch used a file-scoped surface"},
    {68, "cudaErrorSyncDepthExceeded", nullptr, "call to cudaDeviceSynchronize exceeded maximum depth"},
    {69, "cudaErrorLaunchPendingCountExceeded", nullptr, "launch pending count exceeded"},
    {98, "cudaErrorInvalidDeviceFunction", nullptr, "invalid device function"},
    {100, "cudaErrorNoDevice", "CUDA_ERROR_NO_DEVICE", "no CUDA-capable device is detected"},
    {101, "cudaErrorInvalidDevice", "CUDA_ERROR_INVALID_DEVICE", "invalid device ordinal"},
    {102, "cudaErrorDeviceNotLicensed", "CUDA_ERROR_DEVICE_NOT_LICENSED",
     "device doesn't have valid Grid license"},
    {103, "cudaErrorSoftwareValidityNotEstablished", nullptr,
     "integrity checks on the software were not established"},
    {127, "cudaErrorStartupFailure", nullptr, "internal startup failure"},
    {200, "cudaErrorInvalidKernelImage", "CUDA_ERROR_INVALID_IMAGE", "device kernel image is invalid"},
    {201, "cudaErrorDeviceUninitialized", "CUDA_ERROR_INVALID_CONTEXT", "invalid device context"},
    {202, nullptr, "CUDA_ERROR_CONTEXT_ALREADY_CURRENT", "context already current"},
    {205, "cudaErrorMapBufferObjectFailed", "CUDA_ERROR_MAP_FAILED", "mapping of buffer object failed"},
    {206, "cudaErrorUnmapBufferObjectFailed", "CUDA_ERROR_UNMAP_FAILED",
     "unmapping of buffer object failed"},
    {207, "cudaErrorArrayIsMapped", "CUDA_ERROR_ARRAY_IS_MAPPED", "array is mapped"},
    {208, "cudaErrorAlreadyMapped", "CUDA_ERROR_ALREADY_MAPPED", "resource already mapped"},
    {209, "cudaErrorNoKernelImageForDevice", "CUDA_ERROR_NO_BINARY_FOR_GPU",
     "no kernel image is available for execution on the device"},
    {210, "cudaErrorAlreadyAcquired", "CUDA_ERROR_ALREADY_ACQUIRED", "resource already acquired"},
    {211, "cudaErrorNotMapped", "CUDA_ERROR_NOT_MAPPED", "resource not mapped"},
    {212, "cudaErrorNotMappedAsArray", "CUDA_ERROR_NOT_MAPPED_AS_ARRAY", "resource not mapped as array"},
    {213, "cudaErrorNotMappedAsPointer", "CUDA_ERROR_NOT_MAPPED_AS_POINTER",
     "resource not mapped as pointer"},
    {214, "cudaErrorECCUncorrectable", "CUDA_ERROR_ECC_UNCORRECTABLE",
     "uncorrectable ECC error encountered"},
    {215, "cudaErrorUnsupportedLimit", "CUDA_ERROR_UNSUPPORTED_LIMIT",
     "limit is not supported on this architecture"},
    {216, "cudaErrorDeviceAlreadyInUse", "CUDA_ERROR_CONTEXT_ALREADY_IN_USE",
     "exclusive-thread device already in use by a different thread"},
    {217, "cudaErrorPeerAccessUnsupported", "CUDA_ERROR_PEER_ACCESS_UNSUPPORTED",
     "peer access is not supported between these two devices"},
    {218, "cudaErrorInvalidPtx", "CUDA_ERROR_INVALID_PTX", "a PTX JIT compilation failed"},
    {219, "cudaErrorInvalidGraphicsContext", "CUDA_ERROR_INVALID_GRAPHICS_CONTEXT",
     "invalid OpenGL or DirectX context"},
    {220, "cudaErrorNvlinkUncorrectable", "CUDA_ERROR_NVLINK_UNCORRECTABLE",
     "uncorrectable NVLink error detected during the execution"},
    {221, "cudaErrorJitCompilerNotFound", "CUDA_ERROR_JIT_COMPILER_NOT_FOUND",
     "PTX JIT compiler library not found"},
    {222, "cudaErrorUnsupportedPtxVersion", "CUDA_ERROR_UNSUPPORTED_PTX_VERSION",
     "the provided PTX was compiled with an unsupported toolchain"},
    {223, "cudaErrorJitCompilationDisabled", "CUDA_ERROR_JIT_COMPILATION_DISABLED",
     "PTX JIT compilation was disabled"},
    {224, "cudaErrorUnsupportedExecAffinity", "CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY",
     "the requested execution affinity is not supported"},
    {225, "cudaErrorUnsupportedDevSideSync", "CUDA_ERROR_UNSUPPORTED_DEVSIDE_SYNC",
     "the PTX contains an unsupported call to cudaDeviceSynchronize"},
    {226, "cudaErrorContained", "CUDA_ERROR_CONTAINED",
     "an error was contained; the process must be restarted to use CUDA again"},
    {300, "cudaErrorInvalidSource", "CUDA_ERROR_INVALID_SOURCE", "device kernel source is invalid"},
    {301, "cudaErrorFileNotFound", "CUDA_ERROR_FILE_NOT_FOUND", "file not found"},
    {302, "cudaErrorSharedObjectSymbolNotFound", "CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND",
     "shared object symbol not found"},
    {303, "cudaErrorSharedObjectInitFailed", "CUDA_ERROR_SHARED_OBJECT_INIT_FAILED",
     "shared object initialization failed"},
    {304, "cudaErrorOperatingSystem", "CUDA_ERROR_OPERATING_SYSTEM",
     "OS call failed or operation not supported on this OS"},
    {400, "cudaErrorInvalidResourceHandle", "CUDA_ERROR_INVALID_HANDLE", "invalid resource handle"},
    {401, "cudaErrorIllegalState", "CUDA_ERROR_ILLEGAL_STATE",
     "the operation cannot be performed in the present state"},
    {402, "cudaErrorLossyQuery", "CUDA_ERROR_LOSSY_QUERY",
     "the query would discard semantically important information"},
    {500, "cudaErrorSymbolNotFound", "CUDA_ERROR_NOT_FOUND", "named symbol not found"},
    {600, "cudaErrorNotReady", "CUDA_ERROR_NOT_READY", "device not ready"},
    {700, "cudaErrorIllegalAddress", "CUDA_ERROR_ILLEGAL_ADDRESS",
     "an illegal memory access was encountered"},
    {701, "cudaErrorLaunchOutOfResources", "CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES",
     "too many resources requested for launch"},
    {702, "cudaErrorLaunchTimeout", "CUDA_ERROR_LAUNCH_TIMEOUT",
     "the launch timed out and was terminated"},
    {703, "cudaErrorLaunchIncompatibleTexturing", "CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING",
     "launch failed because of an incompatible texturing mode"},
    {704, "cudaErrorPeerAccessAlreadyEnabled", "CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED",
     "peer access is already enabled"},
    {705, "cudaErrorPeerAccessNotEnabled", "CUDA_ERROR_PEER_ACCESS_NOT_ENABLED",
     "peer access has not been enabled"},
    {708, "cudaErrorSetOnActiveProcess", "CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE",
     "cannot set while the device is active in this process"},
    {709, "cudaErrorContextIsDestroyed", "CUDA_ERROR_CONTEXT_IS_DESTROYED", "context is destroyed"},
    {710, "cudaErrorAssert", "CUDA_ERROR_ASSERT", "device-side assert triggered"},
    {711, "cudaErrorTooManyPeers", "CUDA_ERROR_TOO_MANY_PEERS", "peer mapping resources exhausted"},
    {712, "cudaErrorHostMemoryAlreadyRegistered", "CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED",
     "part or all of the requested memory range is already mapped"},
    {713, "cudaErrorHostMemoryNotRegistered", "CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED",
     "pointer does not correspond to a registered memory region"},
    {714, "cudaErrorHardwareStackError", "CUDA_ERROR_HARDWARE_STACK_ERROR", "hardware stack error"},
    {715, "cudaErrorIllegalInstruction", "CUDA_ERROR_ILLEGAL_INSTRUCTION",
     "an illegal instruction was encountered"},
    {716, "cudaErrorMisalignedAddress", "CUDA_ERROR_MISALIGNED_ADDRESS", "misaligned address"},
    {717, "cudaErrorInvalidAddressSpace", "CUDA_ERROR_INVALID_ADDRESS_SPACE",
     "operation not supported on global/shared address space"},
    {718, "cudaErrorInvalidPc", "CUDA_ERROR_INVALID_PC", "invalid program counter"},
    {719, "cudaErrorLaunchFailure", "CUDA_ERROR_LAUNCH_FAILED", "unspecified launch failure"},
    {720, "cudaErrorCooperativeLaunchTooLarge", "CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE",
     "too many blocks in cooperative launch"},
    {721, "cudaErrorTensorMemoryLeak", "CUDA_ERROR_TENSOR_MEMORY_LEAK",
     "tensor memory was not completely deallocated"},
    {800, "cudaErrorNotPermitted", "CUDA_ERROR_NOT_PERMITTED", "operation not permitted"},
    {801, "cudaErrorNotSupported", "CUDA_ERROR_NOT_SUPPORTED", "operation not supported"},
    {802, "cudaErrorSystemNotReady", "CUDA_ERROR_SYSTEM_NOT_READY", "system not yet initialized"},
    {803, "cudaErrorSystemDriverMismatch", "CUDA_ERROR_SYSTEM_DRIVER_MISMATCH",
     "system has unsupported display driver / cuda driver combination"},
    {804, "cudaErrorCompatNotSupportedOnDevice", "CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE",
     "forward compatibility was attempted on non supported HW"},
    {805, "cudaErrorMpsConnectionFailed", "CUDA_ERROR_MPS_CONNECTION_FAILED",
     "MPS client failed to connect to the MPS control daemon or the MPS server"},
    {806, "cudaErrorMpsRpcFailure", "CUDA_ERROR_MPS_RPC_FAILURE",
     "the remote procedural call between the MPS server and the MPS client failed"},
    {807, "cudaErrorMpsServerNotReady", "CUDA_ERROR_MPS_SERVER_NOT_READY",
     "MPS server is not ready to accept new MPS client requests"},
    {808, "cudaErrorMpsMaxClientsReached", "CUDA_ERROR_MPS_MAX_CLIENTS_REACHED",
     "the hardware resources required to create MPS client have been exhausted"},
    {809, "cudaErrorMpsMaxConnectionsReached", "CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED",
     "the hardware resources required to support device connections have been exhausted"},
    {810, "cudaErrorMpsClientTerminated", "CUDA_ERROR_MPS_CLIENT_TERMINATED",
     "the MPS client has been terminated by the server"},
    {811, "cudaErrorCdpNotSupported", "CUDA_ERROR_CDP_NOT_SUPPORTED",
     "dynamic parallelism is not supported in this configuration"},
    {812, "cudaErrorCdpVersionMismatch", "CUDA_ERROR_CDP_VERSION_MISMATCH",
     "unsupported interaction between different versions of dynamic parallelism"},
    {900, "cudaErrorStreamCaptureUnsupported", "CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED",
     "operation not permitted when stream is capturing"},
    {901, "cudaErrorStreamCaptureInvalidated", "CUDA_ERROR_STREAM_CAPTURE_INVALIDATED",
     "operation failed due to a previous error during capture"},
    {902, "cudaErrorStreamCaptureMerge", "CUDA_ERROR_STREAM_CAPTURE_MERGE",
     "operation would result in a merge of separate capture sequences"},
    {903, "cudaErrorStreamCaptureUnmatched", "CUDA_ERROR_STREAM_CAPTURE_UNMATCHED",
     "capture was not initiated in this stream"},
    {904, "cudaErrorStreamCaptureUnjoined", "CUDA_ERROR_STREAM_CAPTURE_UNJOINED",
     "capture sequence contains a fork that was not joined to the primary stream"},
    {905, "cudaErrorStreamCaptureIsolation", "CUDA_ERROR_STREAM_CAPTURE_ISOLATION",
     "a dependency would cross the capture sequence boundary"},
    {906, "cudaErrorStreamCaptureImplicit", "CUDA_ERROR_STREAM_CAPTURE_IMPLICIT",
     "operation would make the legacy stream depend on a capturing stream"},
    {907, "cudaErrorCapturedEvent", "CUDA_ERROR_CAPTURED_EVENT",
     "operation not permitted on an event last recorded in a capturing stream"},
    {908, "cudaErrorStreamCaptureWrongThread", "CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD",
     "a capture sequence was ended in a different thread from the one that started it"},
    {909, "cudaErrorTimeout", "CUDA_ERROR_TIMEOUT", "the wait operation has timed out"},
    {910, "cudaErrorGraphExecUpdateFailure", "CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE",
     "the graph update was not performed because it included changes which violated constraints"},
    {911, "cudaErrorExternalDevice", "CUDA_ERROR_EXTERNAL_DEVICE",
     "an error occurred on a device external to the GPU"},
    {912, "cudaErrorInvalidClusterSize", "CUDA_ERROR_INVALID_CLUSTER_SIZE",
     "a thread-block cluster size is invalid"},
    {913, "cudaErrorFunctionNotLoaded", "CUDA_ERROR_FUNCTION_NOT_LOADED",
     "the function is not loaded on the device"},
    {914, "cudaErrorInvalidResourceType", "CUDA_ERROR_INVALID_RESOURCE_TYPE",
     "the resource type is not valid for this operation"},
    {915, "cudaErrorInvalidResourceConfiguration", "CUDA_ERROR_INVALID_RESOURCE_CONFIGURATION",
     "the resource configuration is not valid for this operation"},
    {916, nullptr, "CUDA_ERROR_KEY_ROTATION", "a key rotation is in progress"},
    {999, "cudaErrorUnknown", "CUDA_ERROR_UNKNOWN", "unknown error"},
};

inline const ErrorInfo* find_error(int code) {
  for (const ErrorInfo& e : kErrors)
    if (e.code == code) return &e;
  return nullptr;
}

}  // namespace vgpu::cuda
